import {useEffect,useState,type FormEvent} from 'react';
import {db,rpc} from '../../lib/supabase/client';
import type {Database} from '../../lib/supabase/database.types';
import {EmptyState,StatusBadge} from '../../components/ui/WorkflowOverview';
type Tables=Database['public']['Tables'];
type Assignment=Tables['work_assignments']['Row'];
type Unit=Tables['work_payable_units']['Row'] & {approved_amount:string;paid_amount:string;balance:string;settlement_status:string};
type Entry=Tables['work_payable_events']['Row'];
type Statement={rows:Unit[];count:number;can_manage:boolean;totals:{currency:string;estimated:string;approved:string;paid:string;balance:string}};
type Command=Database['public']['Functions']['act_work_payable']['Args'];
const today=()=>new Date().toISOString().slice(0,10);
const label=(v:string)=>v.replaceAll('_',' ');
export function PayablesWorkspace({userId,organization,embedded=false}:{userId:string;organization:string|null;embedded?:boolean}){
 const [assignments,setAssignments]=useState<Assignment[]>([]),[assignment,setAssignment]=useState(''),[statement,setStatement]=useState<Statement|null>(null),[unit,setUnit]=useState<Unit|null>(null),[events,setEvents]=useState<Entry[]>([]),[listPage,setListPage]=useState(0),[page,setPage]=useState(0),[eventPage,setEventPage]=useState(0),[search,setSearch]=useState(''),[projectSearch,setProjectSearch]=useState(''),[revision,setRevision]=useState(0),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState<Command|null>(null),[action,setAction]=useState('approve');
 const [amendments,setAmendments]=useState<Tables['work_contract_amendments']['Row'][]>([]);
 useEffect(()=>{let live=true;setAmendments([]);if(!assignment)return;void db!.from('work_contract_amendments').select('*').eq('assignment_id',assignment).order('effective_on',{ascending:false}).limit(100).then(({data,error})=>{if(!live)return;if(error)setError(error.message);else setAmendments(data||[])});return()=>{live=false}},[assignment,revision]);
 const [receipt,setReceipt]=useState(''),[receiptUrl,setReceiptUrl]=useState('');
 useEffect(()=>{setReceipt('');setReceiptUrl('')},[unit?.id]);
 const selected=assignments.find(a=>a.id===assignment);
 useEffect(()=>{let live=true;setLoading(true);setError('');let q=db!.from('work_assignments').select('*').eq('work_mode','paid').order('created_at',{ascending:false}).order('id').range(listPage*50,listPage*50+49);
 q=organization?q.eq('organization_id',organization):q.eq('user_id',userId);
 if(search.trim())q=q.ilike('volunteer_name','%'+search.trim()+'%');if(projectSearch.trim())q=q.ilike('project_title','%'+projectSearch.trim()+'%');
 void q.then(({data,error})=>{if(!live)return;setLoading(false);if(error)setError(error.message);else setAssignments(data||[])});return()=>{live=false}},[organization,userId,listPage,search,projectSearch,revision]);
 useEffect(()=>{let live=true;if(!assignment){setStatement(null);return}setLoading(true);setStatement(null);void rpc('work_payable_statement',{p_assignment:assignment,p_page:page}).then(data=>{if(live){const s=data as unknown as Statement;setStatement(s);setUnit(old=>old?s.rows.find(r=>r.id===old.id)||null:null)}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[assignment,page,revision]);
 useEffect(()=>{let live=true;setEvents([]);if(!unit)return;void db!.from('work_payable_events').select('*').eq('unit_id',unit.id).order('created_at',{ascending:false}).order('id').range(eventPage*50,eventPage*50+49).then(({data,error})=>{if(!live)return;if(error)setError(error.message);else setEvents(data||[])});return()=>{live=false}},[unit?.id,eventPage,revision]);
 function refresh(){setRevision(v=>v+1)}
 async function run(fn:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{const result=await fn();setNotice(message);refresh();return result}catch(e){setError((e as Error).message);throw e}finally{setBusy(false)}}
 async function execute(command:Command){setPending(command);try{await run(()=>rpc('act_work_payable',command),'Accounting event recorded.');setPending(null);setReceipt('')}catch{/* Keep the exact request for a safe retry. */}}
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!unit)return;const f=new FormData(event.currentTarget),amount=String(f.get('amount')||'');if(amount&&!/^-?\d{1,12}(\.\d{1,2})?$/.test(amount)){setError('Use an amount with at most two decimal places.');return}
 void execute({p_unit:unit.id,p_action:action,p_amount:amount?Number(amount):null,p_note:String(f.get('note')),p_reference:action==='pay'?String(f.get('reference')):null,p_date:action==='pay'?String(f.get('date')):null,p_reverses:action==='reverse_payment'?String(f.get('reverses')):null,p_version:unit.version,p_request:crypto.randomUUID(),p_receipt:action==='pay'&&receipt?receipt:null});}
 async function uploadReceipt(file:File){
  if(!['application/pdf','image/jpeg','image/png'].includes(file.type)||file.size<1||file.size>5*1024*1024){setError('Choose a PDF, JPEG or PNG receipt up to 5 MiB.');return}
  setReceipt('');try{await run(async()=>{const id=await rpc('reserve_payable_receipt',{p_assignment:assignment,p_filename:file.name,p_mime:file.type,p_size:file.size});const {error}=await db!.storage.from('work-payable-receipts').upload(id,file,{contentType:file.type,upsert:false});if(error)throw error;setReceipt(id)},'Private receipt uploaded. It will be attached when you record the payment.')}catch{/* No payment is created by uploading a receipt. */}
 }
 async function viewReceipt(id:string){try{await run(async()=>{const path=await rpc('authorize_payable_receipt',{p_receipt:id});const {data,error}=await db!.storage.from('work-payable-receipts').createSignedUrl(path,60,{download:true});if(error)throw error;setReceiptUrl(data.signedUrl)},'Receipt link ready for 60 seconds.')}catch{}}
 const disabled=busy||loading||Boolean(pending);
 return <section className={`payables-workspace${embedded?" embedded":""}`}>
 {!embedded&&<header className="finance-hero compact"><div><span className="eyebrow">{organization?"ORGANIZATION FINANCE":"EARNINGS DETAIL"}</span><h2>{organization?"Field Worker payables":"Claims & payables"}</h2><p>{organization?"Review paid Field Worker contracts, approve eligible payable units and record accounting events without changing the accepted work terms.":"Review paid contracts, submit eligible work claims and inspect the immutable payable journal behind your earnings."}</p></div><button className="secondary" disabled={disabled} onClick={refresh}>Refresh records</button></header>}
 {embedded&&<div className="actions"><button className="secondary" disabled={disabled} onClick={refresh}>Refresh payable records</button></div>}
 <div className="notice">{organization?"Manual payment accounting does not transfer money. Amounts and balances are calculated by the server; currencies are never combined.":"Payable approval and provider withdrawal settlement are separate. This ledger shows the server-calculated entitlement behind your earnings; it does not let a Field Worker approve or pay their own work."}</div>
 {error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice success" role="status">{notice}</p>}
 {pending&&<div className="notice" role="status"><div>The last request is retained. Retry sends the same request ID and details. If you reload this page, inspect the journal before repeating a payment.</div><div className="actions"><button className="primary" disabled={busy} onClick={()=>void execute(pending)}>Retry same request</button><button className="secondary" disabled={busy} onClick={()=>{setPending(null);refresh();setNotice('Reloaded for review. Check the journal before creating another payment.')}}>Review current state</button></div></div>}
 <fieldset disabled={disabled} className="payable-filters"><label className="field">Volunteer name<input value={search} onChange={e=>{setSearch(e.target.value);setListPage(0);setAssignment('');setUnit(null)}}/></label><label className="field">Project title<input value={projectSearch} onChange={e=>{setProjectSearch(e.target.value);setListPage(0);setAssignment('');setUnit(null)}}/></label></fieldset>
 <div className="actions"><button className="secondary" disabled={disabled||listPage===0} onClick={()=>{setListPage(p=>p-1);setAssignment('');setUnit(null)}}>Previous assignments</button><span>Page {listPage+1} · up to 50 assignments</span><button className="secondary" disabled={disabled||assignments.length<50} onClick={()=>{setListPage(p=>p+1);setAssignment('');setUnit(null)}}>Next assignments</button></div>
 <label className="field">Paid assignment<select disabled={disabled} value={assignment} onChange={e=>{setAssignment(e.target.value);setPage(0);setUnit(null);setEventPage(0)}}><option value="">Choose an assignment</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.project_title} · {a.volunteer_name} · {a.currency} {a.rate} · {label(a.status)} · {a.id.slice(0,8)}</option>)}</select></label>
 {loading&&<p role="status">Loading payable records…</p>}{!loading&&!assignments.length&&<EmptyState>No paid assignments available in this workspace. Accepted paid contracts are managed in Workforce marketplace.</EmptyState>}
 {selected&&<section className="panel detail"><h2>Agreed contract</h2><p>{selected.organization_name} · {selected.project_title} · {selected.volunteer_name}</p><p><strong>{selected.currency} {selected.rate}</strong> / {label(selected.compensation_type)} · {selected.start_date} to {selected.end_date}</p><p>{selected.terms_note||'No additional terms recorded.'} {selected.completed_at&&`Completed: ${new Date(selected.completed_at).toLocaleString()}`}</p><p>Accepted: {selected.responded_at?new Date(selected.responded_at).toLocaleString():'Not yet accepted'}. Terms are preserved for each payable unit.</p></section>}
 {statement&&selected&&<>
 <section className="panel detail"><h3>Contract amendments</h3><p>Future rate changes require the volunteer to accept before the effective day. Existing payable snapshots keep their agreed rate. Latest 100 amendments shown.</p>
 {amendments.map(a=><article className="document-row" key={a.id}><strong>{selected.currency} {a.rate} from {a.effective_on} · {label(a.status)}</strong><p>{a.terms_note}</p>{a.status==='offered'&&<div className="actions">{(selected.user_id===userId?['accepted','declined']:statement.can_manage?['cancelled']:[]).map(status=><button key={status} className="secondary" disabled={disabled} onClick={()=>void run(()=>rpc('respond_work_amendment',{p_amendment:a.id,p_status:status}),'Amendment response recorded.').catch(()=>{})}>{status==='accepted'?'Accept terms':status==='declined'?'Decline terms':'Cancel offer'}</button>)}</div>}</article>)}
 {statement.can_manage&&selected.status==='active'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>rpc('offer_work_amendment',{p_assignment:assignment,p_rate:Number(f.get('rate')),p_effective:String(f.get('effective')),p_note:String(f.get('terms'))}),'Future rate offered to the volunteer.').catch(()=>{})}}><fieldset disabled={disabled}><label className="field">Proposed rate ({selected.currency})<input name="rate" inputMode="decimal" required pattern="[0-9]{1,12}(\.[0-9]{1,2})?"/></label><label className="field">Future effective date<input name="effective" type="date" required min={new Date(Date.now()+86400000).toISOString().slice(0,10)} max={selected.end_date}/></label><label className="field">Proposed terms<textarea name="terms" required minLength={5} maxLength={2000}/></label><button className="secondary">Offer amendment</button></fieldset></form>}
 </section>
 <div className="stats">{(['estimated','approved','paid','balance'] as const).map(k=><div className="stat" key={k}><span>{({estimated:'Pending estimate',approved:'Net approved entitlement',paid:'Net recorded payments',balance:'Balance / recovery due'})[k]}</span><h3>{statement.totals.currency} {statement.totals[k]}</h3></div>)}</div><p>Negative balance means recorded payments exceed current entitlement and need reconciliation. Pending estimates exclude disputed and rejected claims.</p>
 {selected.compensation_type==='daily_rate'&&<div className="notice"><strong>Attendance-backed daily rate:</strong> Field Workers no longer create manual day claims. An approved assignment attendance session creates or reuses the day payable unit automatically; financial approval remains separate.</div>}
 {selected.compensation_type==='fixed_assignment'&&<form className="panel detail" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>rpc('claim_work_payable',{p_assignment:assignment,p_day:String(f.get('day')),p_note:String(f.get('note'))}),'Fixed completion claim recorded or existing claim recovered. NGO approval is still required.').catch(()=>{})}}><h3>Claim fixed completion</h3><fieldset disabled={disabled}><label className="field">Completion date (UTC; capped at contract end)<input type="date" name="day" required key={selected.id} defaultValue={selected.completed_at?(selected.completed_at.slice(0,10)<selected.end_date?selected.completed_at.slice(0,10):selected.end_date):today()} min={selected.start_date} max={today()<selected.end_date?today():selected.end_date}/></label><label className="field">Completion evidence note<textarea name="note" required minLength={5} maxLength={2000}/></label><button className="primary">Submit completion claim</button></fieldset></form>}
 {statement.can_manage&&selected.compensation_type==='per_verified_survey'&&<form className="panel detail" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const id=await rpc('reconcile_survey_payable',{p_response:String(f.get('response'))});if(!id)throw Error('No eligible accepted contract found. The survey must be independently approved and first received within the accepted contract dates.');return id},'Survey payable reconciled.').catch(()=>{})}}><h3>Recover an earlier approved survey</h3><p>New approvals create candidates automatically. Use the response ID for an approval made before this upgrade.</p><label className="field">Survey response ID<input name="response" required pattern="[0-9a-fA-F-]{36}" disabled={disabled}/></label><button className="secondary" disabled={disabled}>Reconcile survey</button></form>}
 <section className="panel"><div className="panel-title"><h2>Payable units</h2><span>{statement.count} units</span></div><div className="table-wrap"><table><thead><tr><th>Work</th><th>Status</th><th>Approved</th><th>Paid</th><th>Balance</th><th>Details</th></tr></thead><tbody>{statement.rows.map(r=><tr key={r.id}><td>{label(r.source_kind)} · {r.work_date}<br/><small>{r.id.slice(0,8)}</small></td><td><StatusBadge tone={r.status==='disputed'?'warning':'neutral'}>{label(r.settlement_status)}</StatusBadge></td><td>{r.currency} {r.approved_amount}</td><td>{r.paid_amount}</td><td>{r.balance}</td><td><button className="secondary" disabled={disabled} onClick={()=>{setUnit(r);setAction(statement.can_manage?'approve':'dispute');setEventPage(0)}}>Open unit</button></td></tr>)}</tbody></table></div>{!statement.rows.length&&<EmptyState>No payable units on this page.</EmptyState>}<div className="actions"><button disabled={disabled||page===0} onClick={()=>{setPage(p=>p-1);setUnit(null)}}>Previous</button><span>Page {page+1}</span><button disabled={disabled||(page+1)*50>=statement.count} onClick={()=>{setPage(p=>p+1);setUnit(null)}}>Next</button></div></section>
 {unit&&<section className="panel detail"><h2>Unit accounting</h2><p>{unit.id} · snapshot rate {unit.currency} {unit.rate}</p><p>{unit.note}</p><details><summary>Contract snapshot</summary><pre className="survey-json">{JSON.stringify(unit.terms_snapshot,null,2)}</pre></details>
 <form onSubmit={submit}><fieldset disabled={disabled}><label className="field">Action<select value={action} onChange={e=>setAction(e.target.value)}>{(statement.can_manage?['approve','dispute','resolve','reject','adjust','pay','reverse_payment']:['dispute']).map(a=><option key={a} value={a}>{label(a)}</option>)}</select></label><p>The server checks eligibility, role, current version and balance for every action. Your own earnings cannot be approved or paid by your account. Payable approval also requires sufficient project reserved funding and bridges to finance atomically.</p>
 {(action==='pay'||action==='adjust')&&<label className="field">Amount ({unit.currency})<input name="amount" inputMode="decimal" required placeholder={action==='adjust'?'-20.00':'50.00'}/></label>}
 {action==='pay'&&<><label className="field">Actual payment date<input name="date" type="date" required defaultValue={today()} min={unit.work_date} max={today()}/></label><label className="field">Private receipt (optional, PDF/JPEG/PNG up to 5 MiB)<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>{const f=e.target.files?.[0];if(f)void uploadReceipt(f)}}/></label>{receipt&&<p role="status">Receipt uploaded and ready to attach.</p>}<label className="field">Unique bank / cash voucher reference<input name="reference" required minLength={3} maxLength={160}/></label></>}
 {action==='reverse_payment'&&<label className="field">Payment event ID<input name="reverses" required pattern="[0-9a-fA-F-]{36}" placeholder="Copy the payment event ID from the journal"/></label>}
 <label className="field">Reason / supporting evidence<textarea name="note" required minLength={5} maxLength={2000}/></label><button className="primary">Record {label(action)}</button></fieldset></form>
 <h3>Immutable journal</h3>{receiptUrl&&<p><a href={receiptUrl} target="_blank" rel="noopener noreferrer">Download receipt (link expires after 60 seconds)</a></p>}<p>Payment reversal corrects an accounting entry; it does not issue a bank refund. For a real repayment, document that separately in the reason.</p>{events.map(e=><article className="document-row" key={e.id}><strong>{label(e.kind)} · {unit.currency} {e.amount}</strong><p>{e.note}</p><p>{e.reference&&`Reference: ${e.reference} · `}{e.occurred_on||new Date(e.created_at).toLocaleString()}</p>{e.receipt_id&&<button className="secondary" disabled={busy} onClick={()=>void viewReceipt(e.receipt_id!)}>Prepare receipt download</button>}<small>Event ID: {e.id}{e.reverses&&` · Reverses: ${e.reverses}`}</small></article>)}{!events.length&&<EmptyState>No journal entries on this page.</EmptyState>}<div className="actions"><button disabled={eventPage===0} onClick={()=>setEventPage(p=>p-1)}>Earlier page</button><span>Journal page {eventPage+1}</span><button disabled={events.length<50} onClick={()=>setEventPage(p=>p+1)}>More history</button></div></section>}
 </>}
 </section>;
}
