import { useEffect, useState, type FormEvent } from "react";
import { rpc } from "../../../lib/supabase/client";
import type { Json } from "../../../lib/supabase/database.types";
import { MatchReview } from "./MatchReview";
import { beneficiary,date,identityLabel,type Identity,type Merge,type Page,type Section,type Source } from "./model";
type DataRow = Record<string,Json|undefined>;
const sections:Section[]=["sources","merges","history","decisions","assistance"];
export function CanonicalDetail({id,open,changed}:{id:string;open:(id:string)=>void;changed:()=>void}) {
 const [section,setSection]=useState<Section>("sources"),[offset,setOffset]=useState(0),[revision,setRevision]=useState(0),[identity,setIdentity]=useState<Identity|null>(null),[rows,setRows]=useState<DataRow[]>([]),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[anchor,setAnchor]=useState("");
 useEffect(()=>{let live=true;setBusy(true);setError("");setRows([]);void rpc("canonical_workbench_detail",{p_canonical:id,p_section:section,p_offset:offset,p_limit:25}).then(r=>{if(!live)return;const data=r as unknown as Page<DataRow>&{identity:Identity};setIdentity(data.identity);setRows(data.rows);setMore(data.has_more)}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[id,section,offset,revision]);
 function refresh(){setAnchor("");setRevision(v=>v+1);changed()}
 async function action(task:()=>Promise<unknown>,message:string){if(busy)return;setBusy(true);setError("");try{await task();setNotice(message);refresh()}catch(e){setError((e as Error).message+" Reload before trying again.")}finally{setBusy(false)}}
 function reconcile(e:FormEvent<HTMLFormElement>,s:Source){e.preventDefault();if(!identity)return;const f=new FormData(e.currentTarget);if(f.get("ack")!=="on")return;void action(()=>rpc("reconcile_canonical_identity",{p_person:s.id,p_source_version:s.version,p_canonical_version:identity.version,p_reason:String(f.get("reason"))}),"Canonical display identity updated from the reviewed source. Sharing requires fresh authorization.")}
 function revert(e:FormEvent<HTMLFormElement>,m:Merge){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("ack")!=="on")return;void action(()=>rpc("revert_canonical_merge",{p_event:m.id,p_reason:String(f.get("reason")),p_primary_version:m.primary_version,p_secondary_version:m.secondary_version}),"Merge reversed. Review the restored identities and any new sharing requests.")}
 return <section className="panel detail" aria-label="Canonical identity detail"><div className="panel-title"><h2>{identity?beneficiary(identity.beneficiary_no):"Loading identity…"}</h2><button className="secondary" disabled={busy} onClick={refresh}>Reload identity</button></div>
 {error&&<p className="error-text" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {identity&&<><h3>{identity.display_name}</h3><p>{identity.birth_date||"DOB unknown"} · {identityLabel(identity)} · revision {identity.version}</p><p>Canonical links describe record matching; they do not certify identity documents.</p>
 {identity.merged_into&&<button className="secondary" onClick={()=>open(identity.merged_into!)}>Open surviving identity</button>}
 {identity.review_required&&identity.identity_status!=="merged"&&<p>Review linked sources, resolve disputed merges, then select an authoritative source below. Reconciliation updates the display identity and does not settle disputed relationships.</p>}
 <nav className="document-actions" aria-label="Identity sections">{sections.map(s=><button className="secondary" key={s} disabled={busy} aria-pressed={section===s} onClick={()=>{setSection(s);setOffset(0);setAnchor("")}}>{s=== "decisions"?"Match history":s[0].toUpperCase()+s.slice(1)}</button>)}</nav></>}
 {busy&&<p role="status">Loading…</p>}{!busy&&!rows.length&&!error&&<p>No records in this section.</p>}
 {section==="sources"&&rows.map(row=>{const s=row as unknown as Source;return <article className="document-row" key={s.id}><h3>{s.full_name}</h3><p>{s.birth_date||"DOB unknown"} · {s.organization_name} · {s.project_title}</p><p>Source ID: <code>{s.id}</code> · source revision {s.version}</p><p>Household: {s.household_id}</p><p>Linked {date(s.linked_at)} by {s.linked_by} · {s.link_reason}</p><button className="secondary" disabled={busy} onClick={()=>setAnchor(s.id)}>Review matches for this source</button>
 {identity?.review_required&&<details><summary>Use this source as authoritative display identity</summary><form onSubmit={e=>reconcile(e,s)}><label className="field">Review reason<textarea name="reason" required minLength={5} maxLength={1000}/></label><label><input name="ack" type="checkbox" required/> I reviewed the linked sources and resolved any disputed links.</label><p><button disabled={busy}>Reconcile display identity</button></p></form></details>}</article>})}
 {section==="merges"&&rows.map(row=>{const m=row as unknown as Merge;return <article className="document-row" key={m.id}><h3>{m.secondary_name} → {m.primary_name}</h3><p>{m.reverted?"Reverted":"Active merge"} · {date(m.merged_at)} · actor {m.merged_by}</p><p>{m.reason}</p><p>Event: <code>{m.id}</code> · {Array.isArray(m.moved_project_person_ids)?m.moved_project_person_ids.length:0} moved source records.</p><button className="secondary" onClick={()=>open(m.primary_canonical_id)}>Primary identity</button> <button className="secondary" onClick={()=>open(m.secondary_canonical_id)}>Secondary identity</button>
 {m.reverted?<p>Reverted {date(m.reverted_at)} by {m.reverted_by}: {m.revert_reason}</p>:<details><summary>Review merge reversal</summary><p>Restore the recorded source links to the secondary identity. Both identities require review; affected sharing approvals are invalidated. Later dependent merges must be reversed first. No source records or assistance history are deleted.</p><form onSubmit={e=>revert(e,m)}><label className="field">Reason<textarea name="reason" required minLength={5} maxLength={1000}/></label><label><input name="ack" type="checkbox" required/> I reviewed the merge history and reversal impact.</label><p><button disabled={busy}>Reverse this merge</button></p></form></details>}</article>})}
 {section==="history"&&rows.map(r=><article className="document-row" key={String(r.version)}><strong>Revision {String(r.version)} · {date(String(r.recorded_at))}</strong><p>{String(r.reason)} · actor {String(r.actor_id||"Migration")}</p><details><summary>Identity snapshot</summary><pre className="survey-json">{JSON.stringify(r.snapshot,null,2)}</pre></details></article>)}
 {section==="decisions"&&rows.map((r,i)=><article className="document-row" key={i}><strong>Decision revision {String(r.version)} · {date(String(r.recorded_at))}</strong><p>Sources: {String(r.person_a)} / {String(r.person_b)}</p><details><summary>Decision and review evidence</summary><pre className="survey-json">{JSON.stringify(r.snapshot,null,2)}</pre></details></article>)}
 {section==="assistance"&&rows.map(r=><article className="document-row" key={String(r.id)}><strong>{String(r.category)} · {String(r.program)}</strong><p>{String(r.organization_name)} · {String(r.project_title)}</p><p>{String(r.delivered_on)} · {String(r.status)} · {r.amount_pkr!=null?`PKR ${r.amount_pkr}`:`${r.quantity??""} ${r.unit??""}`}</p><p>{String(r.description||"")}</p><p>Source person: {String(r.person_id)} · funding: {String(r.funding_source||"—")}</p></article>)}
 <div className="document-actions"><button className="secondary" disabled={busy||offset===0} onClick={()=>{setOffset(Math.max(0,offset-25));setAnchor("")}}>Previous</button><span>Page {offset/25+1}</span><button className="secondary" disabled={busy||!more} onClick={()=>{setOffset(offset+25);setAnchor("")}}>Next</button></div>
 {anchor&&<MatchReview key={`${anchor}:${revision}`} personId={anchor} changed={()=>{setNotice("Match decision saved. Review the current identity and sharing state.");refresh()}}/>}
 </section>;
}
