// Generated by npm run types:generate from applied PostgreSQL migrations. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: { Tables: {
accounts: {
Row: {
id: string;
email: string;
full_name: string;
platform_role: string;
status: string;
created_at: string;
};
Insert: {
id: string;
email: string;
full_name?: string;
platform_role?: string;
status?: string;
created_at?: string;
};
Update: {
id?: string;
email?: string;
full_name?: string;
platform_role?: string;
status?: string;
created_at?: string;
};
Relationships: [];
};
assistance_entries: {
Row: {
id: string;
project_id: string;
person_id: string;
kind: string;
category: string;
program: string;
description: string;
amount_pkr: number | null;
quantity: number | null;
unit: string | null;
delivered_on: string;
funding_source: string;
evidence_reference: string;
next_eligible_on: string | null;
identity_snapshot: Json;
created_by: string;
created_at: string;
status: string;
version: number;
void_reason: string | null;
voided_by: string | null;
voided_at: string | null;
};
Insert: {
id: string;
project_id: string;
person_id: string;
kind: string;
category: string;
program: string;
description: string;
amount_pkr?: number | null;
quantity?: number | null;
unit?: string | null;
delivered_on: string;
funding_source: string;
evidence_reference: string;
next_eligible_on?: string | null;
identity_snapshot: Json;
created_by: string;
created_at?: string;
status?: string;
version?: number;
void_reason?: string | null;
voided_by?: string | null;
voided_at?: string | null;
};
Update: {
id?: string;
project_id?: string;
person_id?: string;
kind?: string;
category?: string;
program?: string;
description?: string;
amount_pkr?: number | null;
quantity?: number | null;
unit?: string | null;
delivered_on?: string;
funding_source?: string;
evidence_reference?: string;
next_eligible_on?: string | null;
identity_snapshot?: Json;
created_by?: string;
created_at?: string;
status?: string;
version?: number;
void_reason?: string | null;
voided_by?: string | null;
voided_at?: string | null;
};
Relationships: [];
};
audit_events: {
Row: {
id: number;
actor_id: string | null;
subject_id: string | null;
organization_id: string | null;
action: string;
detail: Json;
created_at: string;
};
Insert: {
id?: number;
actor_id?: string | null;
subject_id?: string | null;
organization_id?: string | null;
action: string;
detail?: Json;
created_at?: string;
};
Update: {
id?: number;
actor_id?: string | null;
subject_id?: string | null;
organization_id?: string | null;
action?: string;
detail?: Json;
created_at?: string;
};
Relationships: [];
};
beneficiary_needs: {
Row: {
id: string;
project_id: string;
person_id: string;
source_response_id: string;
source_response_version: number;
category: string;
description: string;
priority: string;
status: string;
follow_up_on: string | null;
version: number;
last_reason: string;
identity_snapshot: Json;
creation_request: Json;
created_by: string;
created_at: string;
updated_by: string;
updated_at: string;
};
Insert: {
id: string;
project_id: string;
person_id: string;
source_response_id: string;
source_response_version: number;
category: string;
description: string;
priority: string;
status?: string;
follow_up_on?: string | null;
version?: number;
last_reason: string;
identity_snapshot: Json;
creation_request: Json;
created_by: string;
created_at?: string;
updated_by: string;
updated_at?: string;
};
Update: {
id?: string;
project_id?: string;
person_id?: string;
source_response_id?: string;
source_response_version?: number;
category?: string;
description?: string;
priority?: string;
status?: string;
follow_up_on?: string | null;
version?: number;
last_reason?: string;
identity_snapshot?: Json;
creation_request?: Json;
created_by?: string;
created_at?: string;
updated_by?: string;
updated_at?: string;
};
Relationships: [];
};
canonical_match_decisions: {
Row: {
person_a: string;
person_b: string;
status: string;
reason: string;
person_a_version: number;
person_b_version: number;
merge_event_id: string | null;
version: number;
reviewed_by: string;
reviewed_at: string;
};
Insert: {
person_a: string;
person_b: string;
status: string;
reason: string;
person_a_version: number;
person_b_version: number;
merge_event_id?: string | null;
version?: number;
reviewed_by: string;
reviewed_at?: string;
};
Update: {
person_a?: string;
person_b?: string;
status?: string;
reason?: string;
person_a_version?: number;
person_b_version?: number;
merge_event_id?: string | null;
version?: number;
reviewed_by?: string;
reviewed_at?: string;
};
Relationships: [];
};
canonical_match_revisions: {
Row: {
person_a: string;
person_b: string;
version: number;
snapshot: Json;
recorded_at: string;
};
Insert: {
person_a: string;
person_b: string;
version: number;
snapshot: Json;
recorded_at?: string;
};
Update: {
person_a?: string;
person_b?: string;
version?: number;
snapshot?: Json;
recorded_at?: string;
};
Relationships: [];
};
canonical_merge_events: {
Row: {
id: string;
primary_canonical_id: string;
secondary_canonical_id: string;
moved_project_person_ids: Json;
reason: string;
merged_by: string;
merged_at: string;
reverted: boolean;
revert_reason: string | null;
reverted_by: string | null;
reverted_at: string | null;
};
Insert: {
id?: string;
primary_canonical_id: string;
secondary_canonical_id: string;
moved_project_person_ids: Json;
reason: string;
merged_by: string;
merged_at?: string;
reverted?: boolean;
revert_reason?: string | null;
reverted_by?: string | null;
reverted_at?: string | null;
};
Update: {
id?: string;
primary_canonical_id?: string;
secondary_canonical_id?: string;
moved_project_person_ids?: Json;
reason?: string;
merged_by?: string;
merged_at?: string;
reverted?: boolean;
revert_reason?: string | null;
reverted_by?: string | null;
reverted_at?: string | null;
};
Relationships: [];
};
canonical_person_links: {
Row: {
project_person_id: string;
project_id: string;
canonical_person_id: string;
linked_by: string;
link_reason: string;
linked_at: string;
};
Insert: {
project_person_id: string;
project_id: string;
canonical_person_id: string;
linked_by: string;
link_reason?: string;
linked_at?: string;
};
Update: {
project_person_id?: string;
project_id?: string;
canonical_person_id?: string;
linked_by?: string;
link_reason?: string;
linked_at?: string;
};
Relationships: [];
};
canonical_person_revisions: {
Row: {
canonical_person_id: string;
version: number;
snapshot: Json;
reason: string;
actor_id: string | null;
recorded_at: string;
};
Insert: {
canonical_person_id: string;
version: number;
snapshot: Json;
reason: string;
actor_id?: string | null;
recorded_at?: string;
};
Update: {
canonical_person_id?: string;
version?: number;
snapshot?: Json;
reason?: string;
actor_id?: string | null;
recorded_at?: string;
};
Relationships: [];
};
canonical_persons: {
Row: {
id: string;
beneficiary_no: number;
display_name: string;
birth_date: string | null;
identity_status: string;
merged_into: string | null;
version: number;
created_by: string;
created_at: string;
updated_at: string;
review_required: boolean;
};
Insert: {
id?: string;
beneficiary_no?: number;
display_name: string;
birth_date?: string | null;
identity_status?: string;
merged_into?: string | null;
version?: number;
created_by: string;
created_at?: string;
updated_at?: string;
review_required?: boolean;
};
Update: {
id?: string;
beneficiary_no?: number;
display_name?: string;
birth_date?: string | null;
identity_status?: string;
merged_into?: string | null;
version?: number;
created_by?: string;
created_at?: string;
updated_at?: string;
review_required?: boolean;
};
Relationships: [];
};
data_access_events: {
Row: {
id: number;
request_id: string | null;
grant_id: string | null;
actor_id: string;
actor_organization_id: string | null;
event_type: string;
detail: Json;
created_at: string;
};
Insert: {
id?: number;
request_id?: string | null;
grant_id?: string | null;
actor_id: string;
actor_organization_id?: string | null;
event_type: string;
detail?: Json;
created_at?: string;
};
Update: {
id?: number;
request_id?: string | null;
grant_id?: string | null;
actor_id?: string;
actor_organization_id?: string | null;
event_type?: string;
detail?: Json;
created_at?: string;
};
Relationships: [];
};
data_access_grants: {
Row: {
id: string;
request_id: string;
canonical_person_id: string;
canonical_version: number;
grantee_organization_id: string;
source_organization_id: string;
fields: (string)[];
purpose: string;
valid_from: string;
expires_at: string;
status: string;
version: number;
granted_by: string;
granted_at: string;
revoked_by: string | null;
revoked_at: string | null;
revoke_reason: string | null;
};
Insert: {
id?: string;
request_id: string;
canonical_person_id: string;
canonical_version: number;
grantee_organization_id: string;
source_organization_id: string;
fields: (string)[];
purpose: string;
valid_from?: string;
expires_at: string;
status?: string;
version?: number;
granted_by: string;
granted_at?: string;
revoked_by?: string | null;
revoked_at?: string | null;
revoke_reason?: string | null;
};
Update: {
id?: string;
request_id?: string;
canonical_person_id?: string;
canonical_version?: number;
grantee_organization_id?: string;
source_organization_id?: string;
fields?: (string)[];
purpose?: string;
valid_from?: string;
expires_at?: string;
status?: string;
version?: number;
granted_by?: string;
granted_at?: string;
revoked_by?: string | null;
revoked_at?: string | null;
revoke_reason?: string | null;
};
Relationships: [];
};
data_access_requests: {
Row: {
id: string;
canonical_person_id: string;
requesting_project_person_id: string;
requesting_organization_id: string;
source_organization_id: string;
purpose: string;
requested_fields: (string)[];
source_approved_fields: (string)[] | null;
requested_expires_at: string;
status: string;
source_note: string | null;
source_reviewed_by: string | null;
source_reviewed_at: string | null;
poem_note: string | null;
poem_reviewed_by: string | null;
poem_reviewed_at: string | null;
version: number;
created_by: string;
created_at: string;
updated_at: string;
};
Insert: {
id?: string;
canonical_person_id: string;
requesting_project_person_id: string;
requesting_organization_id: string;
source_organization_id: string;
purpose: string;
requested_fields: (string)[];
source_approved_fields?: (string)[] | null;
requested_expires_at: string;
status?: string;
source_note?: string | null;
source_reviewed_by?: string | null;
source_reviewed_at?: string | null;
poem_note?: string | null;
poem_reviewed_by?: string | null;
poem_reviewed_at?: string | null;
version?: number;
created_by: string;
created_at?: string;
updated_at?: string;
};
Update: {
id?: string;
canonical_person_id?: string;
requesting_project_person_id?: string;
requesting_organization_id?: string;
source_organization_id?: string;
purpose?: string;
requested_fields?: (string)[];
source_approved_fields?: (string)[] | null;
requested_expires_at?: string;
status?: string;
source_note?: string | null;
source_reviewed_by?: string | null;
source_reviewed_at?: string | null;
poem_note?: string | null;
poem_reviewed_by?: string | null;
poem_reviewed_at?: string | null;
version?: number;
created_by?: string;
created_at?: string;
updated_at?: string;
};
Relationships: [];
};
finance_accounts: {
Row: {
id: string;
organization_id: string | null;
project_id: string | null;
user_id: string | null;
code: string;
name: string;
account_class: string;
purpose: string;
currency: string;
created_by: string;
created_at: string;
};
Insert: {
id?: string;
organization_id?: string | null;
project_id?: string | null;
user_id?: string | null;
code: string;
name: string;
account_class: string;
purpose: string;
currency: string;
created_by: string;
created_at?: string;
};
Update: {
id?: string;
organization_id?: string | null;
project_id?: string | null;
user_id?: string | null;
code?: string;
name?: string;
account_class?: string;
purpose?: string;
currency?: string;
created_by?: string;
created_at?: string;
};
Relationships: [];
};
finance_journals: {
Row: {
id: string;
organization_id: string | null;
project_id: string | null;
journal_type: string;
currency: string;
reference_type: string | null;
reference_id: string | null;
idempotency_key: string;
memo: string;
reverses_journal_id: string | null;
request_payload: Json;
created_by: string;
posted_at: string;
};
Insert: {
id?: string;
organization_id?: string | null;
project_id?: string | null;
journal_type: string;
currency: string;
reference_type?: string | null;
reference_id?: string | null;
idempotency_key: string;
memo: string;
reverses_journal_id?: string | null;
request_payload: Json;
created_by: string;
posted_at?: string;
};
Update: {
id?: string;
organization_id?: string | null;
project_id?: string | null;
journal_type?: string;
currency?: string;
reference_type?: string | null;
reference_id?: string | null;
idempotency_key?: string;
memo?: string;
reverses_journal_id?: string | null;
request_payload?: Json;
created_by?: string;
posted_at?: string;
};
Relationships: [];
};
finance_postings: {
Row: {
id: string;
journal_id: string;
line_no: number;
account_id: string;
direction: string;
amount: number;
memo: string;
created_at: string;
};
Insert: {
id?: string;
journal_id: string;
line_no: number;
account_id: string;
direction: string;
amount: number;
memo?: string;
created_at?: string;
};
Update: {
id?: string;
journal_id?: string;
line_no?: number;
account_id?: string;
direction?: string;
amount?: number;
memo?: string;
created_at?: string;
};
Relationships: [];
};
geographies: {
Row: {
id: string;
parent_id: string | null;
kind: string;
name: string;
code: string;
source_note: string;
active: boolean;
created_at: string;
};
Insert: {
id?: string;
parent_id?: string | null;
kind: string;
name: string;
code: string;
source_note?: string;
active?: boolean;
created_at?: string;
};
Update: {
id?: string;
parent_id?: string | null;
kind?: string;
name?: string;
code?: string;
source_note?: string;
active?: boolean;
created_at?: string;
};
Relationships: [];
};
independent_verification_events: {
Row: {
id: number;
verification_id: string;
actor_id: string;
action: string;
reason: string;
snapshot: Json;
created_at: string;
};
Insert: {
id?: number;
verification_id: string;
actor_id: string;
action: string;
reason: string;
snapshot: Json;
created_at?: string;
};
Update: {
id?: number;
verification_id?: string;
actor_id?: string;
action?: string;
reason?: string;
snapshot?: Json;
created_at?: string;
};
Relationships: [];
};
independent_verifications: {
Row: {
id: string;
kind: string;
organization_id: string | null;
volunteer_id: string | null;
canonical_id: string | null;
subject_snapshot: Json;
evidence_reference: string;
request_note: string;
status: string;
requested_by: string;
requested_at: string;
reviewed_by: string | null;
reviewed_at: string | null;
review_note: string | null;
method: string | null;
expires_at: string | null;
version: number;
};
Insert: {
id?: string;
kind: string;
organization_id?: string | null;
volunteer_id?: string | null;
canonical_id?: string | null;
subject_snapshot: Json;
evidence_reference: string;
request_note: string;
status?: string;
requested_by: string;
requested_at?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
review_note?: string | null;
method?: string | null;
expires_at?: string | null;
version?: number;
};
Update: {
id?: string;
kind?: string;
organization_id?: string | null;
volunteer_id?: string | null;
canonical_id?: string | null;
subject_snapshot?: Json;
evidence_reference?: string;
request_note?: string;
status?: string;
requested_by?: string;
requested_at?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
review_note?: string | null;
method?: string | null;
expires_at?: string | null;
version?: number;
};
Relationships: [];
};
need_assistance_links: {
Row: {
need_id: string;
assistance_id: string;
active: boolean;
version: number;
reason: string;
updated_by: string;
updated_at: string;
project_id: string;
person_id: string;
};
Insert: {
need_id: string;
assistance_id: string;
active?: boolean;
version?: number;
reason: string;
updated_by: string;
updated_at?: string;
project_id: string;
person_id: string;
};
Update: {
need_id?: string;
assistance_id?: string;
active?: boolean;
version?: number;
reason?: string;
updated_by?: string;
updated_at?: string;
project_id?: string;
person_id?: string;
};
Relationships: [];
};
need_link_revisions: {
Row: {
need_id: string;
assistance_id: string;
version: number;
snapshot: Json;
recorded_at: string;
};
Insert: {
need_id: string;
assistance_id: string;
version: number;
snapshot: Json;
recorded_at?: string;
};
Update: {
need_id?: string;
assistance_id?: string;
version?: number;
snapshot?: Json;
recorded_at?: string;
};
Relationships: [];
};
need_revisions: {
Row: {
need_id: string;
version: number;
snapshot: Json;
recorded_at: string;
};
Insert: {
need_id: string;
version: number;
snapshot: Json;
recorded_at?: string;
};
Update: {
need_id?: string;
version?: number;
snapshot?: Json;
recorded_at?: string;
};
Relationships: [];
};
notifications: {
Row: {
id: number;
user_id: string;
title: string;
body: string;
read_at: string | null;
created_at: string;
};
Insert: {
id?: number;
user_id: string;
title: string;
body: string;
read_at?: string | null;
created_at?: string;
};
Update: {
id?: number;
user_id?: string;
title?: string;
body?: string;
read_at?: string | null;
created_at?: string;
};
Relationships: [];
};
organization_areas: {
Row: {
organization_id: string;
geography_id: string;
};
Insert: {
organization_id: string;
geography_id: string;
};
Update: {
organization_id?: string;
geography_id?: string;
};
Relationships: [];
};
organization_memberships: {
Row: {
organization_id: string;
user_id: string;
role: string;
status: string;
};
Insert: {
organization_id: string;
user_id: string;
role: string;
status?: string;
};
Update: {
organization_id?: string;
user_id?: string;
role?: string;
status?: string;
};
Relationships: [];
};
organization_programs: {
Row: {
organization_id: string;
name: string;
};
Insert: {
organization_id: string;
name: string;
};
Update: {
organization_id?: string;
name?: string;
};
Relationships: [];
};
organizations: {
Row: {
id: string;
name: string;
registration_number: string;
contact_person: string;
email: string;
phone: string;
address: string;
areas: string;
programs: string;
status: string;
created_at: string;
operations_version: number;
verification_revision: number;
};
Insert: {
id?: string;
name: string;
registration_number?: string;
contact_person?: string;
email?: string;
phone?: string;
address?: string;
areas?: string;
programs?: string;
status?: string;
created_at?: string;
operations_version?: number;
verification_revision?: number;
};
Update: {
id?: string;
name?: string;
registration_number?: string;
contact_person?: string;
email?: string;
phone?: string;
address?: string;
areas?: string;
programs?: string;
status?: string;
created_at?: string;
operations_version?: number;
verification_revision?: number;
};
Relationships: [];
};
partner_ngo_application_documents: {
Row: {
id: string;
application_id: string;
applicant_user_id: string;
object_path: string;
file_name: string;
mime_type: string;
byte_size: number;
kind: string;
state: string;
review_status: string;
review_note: string;
reviewed_by: string | null;
reviewed_at: string | null;
version: number;
created_at: string;
};
Insert: {
id?: string;
application_id: string;
applicant_user_id: string;
object_path: string;
file_name: string;
mime_type: string;
byte_size: number;
kind: string;
state?: string;
review_status?: string;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
version?: number;
created_at?: string;
};
Update: {
id?: string;
application_id?: string;
applicant_user_id?: string;
object_path?: string;
file_name?: string;
mime_type?: string;
byte_size?: number;
kind?: string;
state?: string;
review_status?: string;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
version?: number;
created_at?: string;
};
Relationships: [];
};
partner_ngo_applications: {
Row: {
id: string;
applicant_user_id: string;
organization_id: string | null;
organization_name: string;
registration_number: string;
legal_type: string;
representative_name: string;
representative_title: string;
email: string;
phone: string;
address: string;
website: string;
operating_area_ids: (string)[];
program_names: (string)[];
status: string;
review_note: string;
reviewed_by: string | null;
reviewed_at: string | null;
submitted_at: string | null;
approved_at: string | null;
version: number;
created_at: string;
updated_at: string;
};
Insert: {
id?: string;
applicant_user_id: string;
organization_id?: string | null;
organization_name?: string;
registration_number?: string;
legal_type?: string;
representative_name?: string;
representative_title?: string;
email?: string;
phone?: string;
address?: string;
website?: string;
operating_area_ids?: (string)[];
program_names?: (string)[];
status?: string;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
submitted_at?: string | null;
approved_at?: string | null;
version?: number;
created_at?: string;
updated_at?: string;
};
Update: {
id?: string;
applicant_user_id?: string;
organization_id?: string | null;
organization_name?: string;
registration_number?: string;
legal_type?: string;
representative_name?: string;
representative_title?: string;
email?: string;
phone?: string;
address?: string;
website?: string;
operating_area_ids?: (string)[];
program_names?: (string)[];
status?: string;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
submitted_at?: string | null;
approved_at?: string | null;
version?: number;
created_at?: string;
updated_at?: string;
};
Relationships: [];
};
profile_shares: {
Row: {
user_id: string;
organization_id: string;
consent_version: string;
granted_at: string;
};
Insert: {
user_id: string;
organization_id: string;
consent_version?: string;
granted_at?: string;
};
Update: {
user_id?: string;
organization_id?: string;
consent_version?: string;
granted_at?: string;
};
Relationships: [];
};
project_policy_versions: {
Row: {
project_id: string;
version: number;
retention_days: number;
discovery: string;
require_ngo_verification: boolean;
require_volunteer_verification: boolean;
collection_paused: boolean;
purpose: string;
consent_version: string;
consent_notice: string;
reason: string;
published_by: string;
published_at: string;
};
Insert: {
project_id: string;
version: number;
retention_days: number;
discovery: string;
require_ngo_verification: boolean;
require_volunteer_verification: boolean;
collection_paused: boolean;
purpose: string;
consent_version: string;
consent_notice: string;
reason: string;
published_by: string;
published_at?: string;
};
Update: {
project_id?: string;
version?: number;
retention_days?: number;
discovery?: string;
require_ngo_verification?: boolean;
require_volunteer_verification?: boolean;
collection_paused?: boolean;
purpose?: string;
consent_version?: string;
consent_notice?: string;
reason?: string;
published_by?: string;
published_at?: string;
};
Relationships: [];
};
project_staff_areas: {
Row: {
assignment_id: string;
geography_id: string;
assigned_at: string;
};
Insert: {
assignment_id: string;
geography_id: string;
assigned_at?: string;
};
Update: {
assignment_id?: string;
geography_id?: string;
assigned_at?: string;
};
Relationships: [];
};
project_staff_assignments: {
Row: {
id: string;
project_id: string;
user_id: string;
role: string;
status: string;
starts_at: string;
ends_at: string | null;
assigned_by: string;
revoked_at: string | null;
revoked_by: string | null;
revoke_reason: string;
version: number;
created_at: string;
updated_at: string;
};
Insert: {
id?: string;
project_id: string;
user_id: string;
role: string;
status?: string;
starts_at: string;
ends_at?: string | null;
assigned_by: string;
revoked_at?: string | null;
revoked_by?: string | null;
revoke_reason?: string;
version?: number;
created_at?: string;
updated_at?: string;
};
Update: {
id?: string;
project_id?: string;
user_id?: string;
role?: string;
status?: string;
starts_at?: string;
ends_at?: string | null;
assigned_by?: string;
revoked_at?: string | null;
revoked_by?: string | null;
revoke_reason?: string;
version?: number;
created_at?: string;
updated_at?: string;
};
Relationships: [];
};
registry_households: {
Row: {
id: string;
project_id: string;
label: string;
geography_id: string;
created_by: string;
created_at: string;
};
Insert: {
id?: string;
project_id: string;
label: string;
geography_id: string;
created_by: string;
created_at?: string;
};
Update: {
id?: string;
project_id?: string;
label?: string;
geography_id?: string;
created_by?: string;
created_at?: string;
};
Relationships: [];
};
registry_match_decisions: {
Row: {
project_id: string;
person_a: string;
person_b: string;
status: string;
reason: string;
person_a_version: number;
person_b_version: number;
version: number;
reviewed_by: string;
reviewed_at: string;
};
Insert: {
project_id: string;
person_a: string;
person_b: string;
status: string;
reason: string;
person_a_version: number;
person_b_version: number;
version?: number;
reviewed_by: string;
reviewed_at?: string;
};
Update: {
project_id?: string;
person_a?: string;
person_b?: string;
status?: string;
reason?: string;
person_a_version?: number;
person_b_version?: number;
version?: number;
reviewed_by?: string;
reviewed_at?: string;
};
Relationships: [];
};
registry_match_revisions: {
Row: {
person_a: string;
person_b: string;
version: number;
snapshot: Json;
recorded_at: string;
};
Insert: {
person_a: string;
person_b: string;
version: number;
snapshot: Json;
recorded_at?: string;
};
Update: {
person_a?: string;
person_b?: string;
version?: number;
snapshot?: Json;
recorded_at?: string;
};
Relationships: [];
};
registry_person_revisions: {
Row: {
person_id: string;
version: number;
snapshot: Json;
reason: string;
actor_id: string | null;
recorded_at: string;
};
Insert: {
person_id: string;
version: number;
snapshot: Json;
reason: string;
actor_id?: string | null;
recorded_at?: string;
};
Update: {
person_id?: string;
version?: number;
snapshot?: Json;
reason?: string;
actor_id?: string | null;
recorded_at?: string;
};
Relationships: [];
};
registry_persons: {
Row: {
id: string;
registry_no: number;
project_id: string;
household_id: string;
full_name: string;
birth_date: string | null;
identity_status: string;
created_by: string;
created_at: string;
version: number;
};
Insert: {
id?: string;
registry_no?: number;
project_id: string;
household_id: string;
full_name: string;
birth_date?: string | null;
identity_status?: string;
created_by: string;
created_at?: string;
version?: number;
};
Update: {
id?: string;
registry_no?: number;
project_id?: string;
household_id?: string;
full_name?: string;
birth_date?: string | null;
identity_status?: string;
created_by?: string;
created_at?: string;
version?: number;
};
Relationships: [];
};
survey_assignments: {
Row: {
project_id: string;
user_id: string;
active: boolean;
collection_geography_id: string;
};
Insert: {
project_id: string;
user_id: string;
active?: boolean;
collection_geography_id: string;
};
Update: {
project_id?: string;
user_id?: string;
active?: boolean;
collection_geography_id?: string;
};
Relationships: [];
};
survey_capture_files: {
Row: {
id: string;
project_id: string;
collector_id: string;
question_id: string;
object_name: string;
filename: string;
mime_type: string;
size_bytes: number;
consent: Json;
created_at: string;
request_fingerprint: string | null;
collection_geography_id: string;
};
Insert: {
id?: string;
project_id: string;
collector_id: string;
question_id: string;
object_name: string;
filename: string;
mime_type: string;
size_bytes: number;
consent: Json;
created_at?: string;
request_fingerprint?: string | null;
collection_geography_id: string;
};
Update: {
id?: string;
project_id?: string;
collector_id?: string;
question_id?: string;
object_name?: string;
filename?: string;
mime_type?: string;
size_bytes?: number;
consent?: Json;
created_at?: string;
request_fingerprint?: string | null;
collection_geography_id?: string;
};
Relationships: [];
};
survey_project_drafts: {
Row: {
id: string;
organization_id: string;
created_by: string;
title: string;
template_id: string | null;
geography_id: string | null;
target: number | null;
start_date: string | null;
end_date: string | null;
purpose: string;
consent_version: string;
consent_notice: string;
review_status: string;
version: number;
submitted_at: string | null;
reviewed_at: string | null;
reviewed_by: string | null;
review_note: string;
approved_project_id: string | null;
created_at: string;
updated_at: string;
};
Insert: {
id?: string;
organization_id: string;
created_by: string;
title?: string;
template_id?: string | null;
geography_id?: string | null;
target?: number | null;
start_date?: string | null;
end_date?: string | null;
purpose?: string;
consent_version?: string;
consent_notice?: string;
review_status?: string;
version?: number;
submitted_at?: string | null;
reviewed_at?: string | null;
reviewed_by?: string | null;
review_note?: string;
approved_project_id?: string | null;
created_at?: string;
updated_at?: string;
};
Update: {
id?: string;
organization_id?: string;
created_by?: string;
title?: string;
template_id?: string | null;
geography_id?: string | null;
target?: number | null;
start_date?: string | null;
end_date?: string | null;
purpose?: string;
consent_version?: string;
consent_notice?: string;
review_status?: string;
version?: number;
submitted_at?: string | null;
reviewed_at?: string | null;
reviewed_by?: string | null;
review_note?: string;
approved_project_id?: string | null;
created_at?: string;
updated_at?: string;
};
Relationships: [];
};
survey_project_review_events: {
Row: {
id: number;
draft_id: string;
actor_id: string;
action: string;
note: string;
created_at: string;
};
Insert: {
id?: number;
draft_id: string;
actor_id: string;
action: string;
note?: string;
created_at?: string;
};
Update: {
id?: number;
draft_id?: string;
actor_id?: string;
action?: string;
note?: string;
created_at?: string;
};
Relationships: [];
};
survey_projects: {
Row: {
id: string;
organization_id: string;
title: string;
template_id: string;
geography_id: string;
target: number;
start_date: string;
end_date: string;
purpose: string;
consent_version: string;
consent_notice: string;
status: string;
created_by: string;
created_at: string;
sharing_discoverable: boolean;
governance_version: number;
governance_notice: string;
required_volunteers: number | null;
recruitment_status: string;
recruitment_version: number;
work_mode: string;
compensation_type: string;
compensation_currency: string;
compensation_rate: number | null;
compensation_note: string;
compensation_version: number;
};
Insert: {
id?: string;
organization_id: string;
title: string;
template_id: string;
geography_id: string;
target: number;
start_date: string;
end_date: string;
purpose: string;
consent_version: string;
consent_notice: string;
status?: string;
created_by: string;
created_at?: string;
sharing_discoverable?: boolean;
governance_version?: number;
governance_notice?: string;
required_volunteers?: number | null;
recruitment_status?: string;
recruitment_version?: number;
work_mode?: string;
compensation_type?: string;
compensation_currency?: string;
compensation_rate?: number | null;
compensation_note?: string;
compensation_version?: number;
};
Update: {
id?: string;
organization_id?: string;
title?: string;
template_id?: string;
geography_id?: string;
target?: number;
start_date?: string;
end_date?: string;
purpose?: string;
consent_version?: string;
consent_notice?: string;
status?: string;
created_by?: string;
created_at?: string;
sharing_discoverable?: boolean;
governance_version?: number;
governance_notice?: string;
required_volunteers?: number | null;
recruitment_status?: string;
recruitment_version?: number;
work_mode?: string;
compensation_type?: string;
compensation_currency?: string;
compensation_rate?: number | null;
compensation_note?: string;
compensation_version?: number;
};
Relationships: [];
};
survey_response_revisions: {
Row: {
response_id: string;
version: number;
snapshot: Json;
actor_id: string;
recorded_at: string;
};
Insert: {
response_id: string;
version: number;
snapshot: Json;
actor_id: string;
recorded_at?: string;
};
Update: {
response_id?: string;
version?: number;
snapshot?: Json;
actor_id?: string;
recorded_at?: string;
};
Relationships: [];
};
survey_responses: {
Row: {
id: string;
project_id: string;
person_id: string;
collector_id: string;
answers: Json;
consent: Json;
status: string;
version: number;
review_note: string;
reviewed_by: string | null;
reviewed_at: string | null;
created_at: string;
updated_at: string;
identity_snapshot: Json | null;
governance_version: number | null;
collection_geography_id: string;
};
Insert: {
id?: string;
project_id: string;
person_id: string;
collector_id: string;
answers: Json;
consent: Json;
status?: string;
version?: number;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
created_at?: string;
updated_at?: string;
identity_snapshot?: Json | null;
governance_version?: number | null;
collection_geography_id: string;
};
Update: {
id?: string;
project_id?: string;
person_id?: string;
collector_id?: string;
answers?: Json;
consent?: Json;
status?: string;
version?: number;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
created_at?: string;
updated_at?: string;
identity_snapshot?: Json | null;
governance_version?: number | null;
collection_geography_id?: string;
};
Relationships: [];
};
survey_save_receipts: {
Row: {
actor_id: string;
request_id: string;
project_id: string;
response_id: string;
payload_hash: string;
response_version: number;
created_at: string;
};
Insert: {
actor_id: string;
request_id: string;
project_id: string;
response_id: string;
payload_hash: string;
response_version: number;
created_at?: string;
};
Update: {
actor_id?: string;
request_id?: string;
project_id?: string;
response_id?: string;
payload_hash?: string;
response_version?: number;
created_at?: string;
};
Relationships: [];
};
survey_template_drafts: {
Row: {
id: string;
owner_id: string;
name: string;
questions: Json;
source: Json;
version: number;
published_id: string | null;
updated_at: string;
organization_id: string | null;
review_status: string;
submitted_at: string | null;
reviewed_at: string | null;
reviewed_by: string | null;
review_note: string;
};
Insert: {
id: string;
owner_id: string;
name?: string;
questions?: Json;
source?: Json;
version?: number;
published_id?: string | null;
updated_at?: string;
organization_id?: string | null;
review_status?: string;
submitted_at?: string | null;
reviewed_at?: string | null;
reviewed_by?: string | null;
review_note?: string;
};
Update: {
id?: string;
owner_id?: string;
name?: string;
questions?: Json;
source?: Json;
version?: number;
published_id?: string | null;
updated_at?: string;
organization_id?: string | null;
review_status?: string;
submitted_at?: string | null;
reviewed_at?: string | null;
reviewed_by?: string | null;
review_note?: string;
};
Relationships: [];
};
survey_template_review_events: {
Row: {
id: number;
draft_id: string;
actor_id: string;
action: string;
note: string;
created_at: string;
};
Insert: {
id?: number;
draft_id: string;
actor_id: string;
action: string;
note?: string;
created_at?: string;
};
Update: {
id?: number;
draft_id?: string;
actor_id?: string;
action?: string;
note?: string;
created_at?: string;
};
Relationships: [];
};
survey_templates: {
Row: {
id: string;
name: string;
version: number;
questions: Json;
created_by: string;
created_at: string;
organization_id: string | null;
source_draft_id: string | null;
};
Insert: {
id?: string;
name: string;
version: number;
questions: Json;
created_by: string;
created_at?: string;
organization_id?: string | null;
source_draft_id?: string | null;
};
Update: {
id?: string;
name?: string;
version?: number;
questions?: Json;
created_by?: string;
created_at?: string;
organization_id?: string | null;
source_draft_id?: string | null;
};
Relationships: [];
};
volunteer_documents: {
Row: {
id: string;
user_id: string;
object_path: string;
file_name: string;
mime_type: string;
byte_size: number;
kind: string;
state: string;
review_status: string;
review_note: string;
reviewed_by: string | null;
reviewed_at: string | null;
created_at: string;
version: number;
};
Insert: {
id?: string;
user_id: string;
object_path: string;
file_name: string;
mime_type: string;
byte_size: number;
kind: string;
state?: string;
review_status?: string;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
created_at?: string;
version?: number;
};
Update: {
id?: string;
user_id?: string;
object_path?: string;
file_name?: string;
mime_type?: string;
byte_size?: number;
kind?: string;
state?: string;
review_status?: string;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
created_at?: string;
version?: number;
};
Relationships: [];
};
volunteer_experiences: {
Row: {
id: string;
user_id: string;
organization_id: string;
volunteer_name: string;
role_title: string;
start_date: string;
end_date: string | null;
description: string;
status: string;
version: number;
reviewed_by: string | null;
reviewed_at: string | null;
review_note: string;
created_at: string;
updated_at: string;
};
Insert: {
id?: string;
user_id: string;
organization_id: string;
volunteer_name: string;
role_title: string;
start_date: string;
end_date?: string | null;
description: string;
status?: string;
version?: number;
reviewed_by?: string | null;
reviewed_at?: string | null;
review_note?: string;
created_at?: string;
updated_at?: string;
};
Update: {
id?: string;
user_id?: string;
organization_id?: string;
volunteer_name?: string;
role_title?: string;
start_date?: string;
end_date?: string | null;
description?: string;
status?: string;
version?: number;
reviewed_by?: string | null;
reviewed_at?: string | null;
review_note?: string;
created_at?: string;
updated_at?: string;
};
Relationships: [];
};
volunteer_profiles: {
Row: {
user_id: string;
details: Json;
status: string;
review_note: string;
reviewed_by: string | null;
reviewed_at: string | null;
version: number;
updated_at: string;
geography_id: string | null;
review_checks: Json;
photo_path: string | null;
photo_updated_at: string | null;
};
Insert: {
user_id: string;
details?: Json;
status?: string;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
version?: number;
updated_at?: string;
geography_id?: string | null;
review_checks?: Json;
photo_path?: string | null;
photo_updated_at?: string | null;
};
Update: {
user_id?: string;
details?: Json;
status?: string;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
version?: number;
updated_at?: string;
geography_id?: string | null;
review_checks?: Json;
photo_path?: string | null;
photo_updated_at?: string | null;
};
Relationships: [];
};
volunteer_shortlists: {
Row: {
organization_id: string;
user_id: string;
status: string;
note: string;
version: number;
updated_by: string;
updated_at: string;
};
Insert: {
organization_id: string;
user_id: string;
status: string;
note?: string;
version?: number;
updated_by: string;
updated_at?: string;
};
Update: {
organization_id?: string;
user_id?: string;
status?: string;
note?: string;
version?: number;
updated_by?: string;
updated_at?: string;
};
Relationships: [];
};
work_applications: {
Row: {
id: string;
opportunity_id: string;
organization_id: string;
survey_project_id: string;
user_id: string;
volunteer_name: string;
organization_name: string;
project_title: string;
opportunity_title: string;
note: string;
status: string;
review_note: string;
reviewed_by: string | null;
reviewed_at: string | null;
version: number;
created_at: string;
updated_at: string;
availability: string;
profile_share_consent: boolean;
consent_version: string;
profile_snapshot: Json;
withdrawn_at: string | null;
};
Insert: {
id?: string;
opportunity_id: string;
organization_id: string;
survey_project_id: string;
user_id: string;
volunteer_name: string;
organization_name: string;
project_title: string;
opportunity_title: string;
note?: string;
status?: string;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
version?: number;
created_at?: string;
updated_at?: string;
availability?: string;
profile_share_consent?: boolean;
consent_version?: string;
profile_snapshot?: Json;
withdrawn_at?: string | null;
};
Update: {
id?: string;
opportunity_id?: string;
organization_id?: string;
survey_project_id?: string;
user_id?: string;
volunteer_name?: string;
organization_name?: string;
project_title?: string;
opportunity_title?: string;
note?: string;
status?: string;
review_note?: string;
reviewed_by?: string | null;
reviewed_at?: string | null;
version?: number;
created_at?: string;
updated_at?: string;
availability?: string;
profile_share_consent?: boolean;
consent_version?: string;
profile_snapshot?: Json;
withdrawn_at?: string | null;
};
Relationships: [];
};
work_assignments: {
Row: {
id: string;
survey_project_id: string;
opportunity_id: string | null;
organization_id: string;
user_id: string;
volunteer_name: string;
organization_name: string;
project_title: string;
opportunity_title: string;
source_kind: string;
source_application_id: string | null;
source_invitation_id: string | null;
work_mode: string;
compensation_type: string;
currency: string;
rate: number | null;
target_surveys: number;
start_date: string;
end_date: string;
terms_note: string;
status: string;
version: number;
offered_by: string;
offered_at: string;
responded_at: string | null;
completed_at: string | null;
completed_by: string | null;
completion_feedback: Json;
completion_note: string;
cancelled_at: string | null;
cancelled_by: string | null;
cancellation_note: string;
created_at: string;
collection_geography_id: string;
compensation_source: string;
compensation_source_version: number | null;
compensation_note_snapshot: string;
};
Insert: {
id?: string;
survey_project_id: string;
opportunity_id?: string | null;
organization_id: string;
user_id: string;
volunteer_name: string;
organization_name: string;
project_title: string;
opportunity_title?: string;
source_kind: string;
source_application_id?: string | null;
source_invitation_id?: string | null;
work_mode: string;
compensation_type: string;
currency?: string;
rate?: number | null;
target_surveys: number;
start_date: string;
end_date: string;
terms_note?: string;
status?: string;
version?: number;
offered_by: string;
offered_at?: string;
responded_at?: string | null;
completed_at?: string | null;
completed_by?: string | null;
completion_feedback?: Json;
completion_note?: string;
cancelled_at?: string | null;
cancelled_by?: string | null;
cancellation_note?: string;
created_at?: string;
collection_geography_id: string;
compensation_source?: string;
compensation_source_version?: number | null;
compensation_note_snapshot?: string;
};
Update: {
id?: string;
survey_project_id?: string;
opportunity_id?: string | null;
organization_id?: string;
user_id?: string;
volunteer_name?: string;
organization_name?: string;
project_title?: string;
opportunity_title?: string;
source_kind?: string;
source_application_id?: string | null;
source_invitation_id?: string | null;
work_mode?: string;
compensation_type?: string;
currency?: string;
rate?: number | null;
target_surveys?: number;
start_date?: string;
end_date?: string;
terms_note?: string;
status?: string;
version?: number;
offered_by?: string;
offered_at?: string;
responded_at?: string | null;
completed_at?: string | null;
completed_by?: string | null;
completion_feedback?: Json;
completion_note?: string;
cancelled_at?: string | null;
cancelled_by?: string | null;
cancellation_note?: string;
created_at?: string;
collection_geography_id?: string;
compensation_source?: string;
compensation_source_version?: number | null;
compensation_note_snapshot?: string;
};
Relationships: [];
};
work_contract_amendments: {
Row: {
id: string;
assignment_id: string;
rate: number;
effective_on: string;
terms_note: string;
status: string;
offered_by: string;
offered_at: string;
responded_at: string | null;
};
Insert: {
id?: string;
assignment_id: string;
rate: number;
effective_on: string;
terms_note: string;
status?: string;
offered_by: string;
offered_at?: string;
responded_at?: string | null;
};
Update: {
id?: string;
assignment_id?: string;
rate?: number;
effective_on?: string;
terms_note?: string;
status?: string;
offered_by?: string;
offered_at?: string;
responded_at?: string | null;
};
Relationships: [];
};
work_invitations: {
Row: {
id: string;
opportunity_id: string;
organization_id: string;
user_id: string;
volunteer_name: string;
status: string;
version: number;
created_by: string;
created_at: string;
responded_at: string | null;
};
Insert: {
id?: string;
opportunity_id: string;
organization_id: string;
user_id: string;
volunteer_name: string;
status?: string;
version?: number;
created_by: string;
created_at?: string;
responded_at?: string | null;
};
Update: {
id?: string;
opportunity_id?: string;
organization_id?: string;
user_id?: string;
volunteer_name?: string;
status?: string;
version?: number;
created_by?: string;
created_at?: string;
responded_at?: string | null;
};
Relationships: [];
};
work_opportunities: {
Row: {
id: string;
organization_id: string;
title: string;
description: string;
geography_id: string;
start_date: string;
end_date: string;
reply_by: string;
payment_type: string;
payment_note: string;
status: string;
created_by: string;
created_at: string;
survey_project_id: string | null;
required_volunteers: number;
required_skill: string;
required_language: string;
visibility: string;
publication_state: string;
applications_open: boolean;
eligibility_note: string;
version: number;
published_at: string | null;
work_mode: string | null;
compensation_type: string | null;
currency: string | null;
rate: number | null;
compensation_note: string | null;
compensation_snapshot_version: number | null;
};
Insert: {
id?: string;
organization_id: string;
title: string;
description: string;
geography_id: string;
start_date: string;
end_date: string;
reply_by: string;
payment_type: string;
payment_note?: string;
status?: string;
created_by: string;
created_at?: string;
survey_project_id?: string | null;
required_volunteers?: number;
required_skill?: string;
required_language?: string;
visibility?: string;
publication_state?: string;
applications_open?: boolean;
eligibility_note?: string;
version?: number;
published_at?: string | null;
work_mode?: string | null;
compensation_type?: string | null;
currency?: string | null;
rate?: number | null;
compensation_note?: string | null;
compensation_snapshot_version?: number | null;
};
Update: {
id?: string;
organization_id?: string;
title?: string;
description?: string;
geography_id?: string;
start_date?: string;
end_date?: string;
reply_by?: string;
payment_type?: string;
payment_note?: string;
status?: string;
created_by?: string;
created_at?: string;
survey_project_id?: string | null;
required_volunteers?: number;
required_skill?: string;
required_language?: string;
visibility?: string;
publication_state?: string;
applications_open?: boolean;
eligibility_note?: string;
version?: number;
published_at?: string | null;
work_mode?: string | null;
compensation_type?: string | null;
currency?: string | null;
rate?: number | null;
compensation_note?: string | null;
compensation_snapshot_version?: number | null;
};
Relationships: [];
};
work_payable_events: {
Row: {
id: string;
unit_id: string;
assignment_id: string;
kind: string;
amount: number;
note: string;
reference: string | null;
occurred_on: string | null;
reverses: string | null;
actor_id: string | null;
created_at: string;
receipt_id: string | null;
request_id: string | null;
request_payload: Json | null;
};
Insert: {
id?: string;
unit_id: string;
assignment_id: string;
kind: string;
amount?: number;
note: string;
reference?: string | null;
occurred_on?: string | null;
reverses?: string | null;
actor_id?: string | null;
created_at?: string;
receipt_id?: string | null;
request_id?: string | null;
request_payload?: Json | null;
};
Update: {
id?: string;
unit_id?: string;
assignment_id?: string;
kind?: string;
amount?: number;
note?: string;
reference?: string | null;
occurred_on?: string | null;
reverses?: string | null;
actor_id?: string | null;
created_at?: string;
receipt_id?: string | null;
request_id?: string | null;
request_payload?: Json | null;
};
Relationships: [];
};
work_payable_receipts: {
Row: {
id: string;
assignment_id: string;
uploaded_by: string;
filename: string;
mime_type: string;
size_bytes: number;
created_at: string;
};
Insert: {
id?: string;
assignment_id: string;
uploaded_by: string;
filename: string;
mime_type: string;
size_bytes: number;
created_at?: string;
};
Update: {
id?: string;
assignment_id?: string;
uploaded_by?: string;
filename?: string;
mime_type?: string;
size_bytes?: number;
created_at?: string;
};
Relationships: [];
};
work_payable_units: {
Row: {
id: string;
assignment_id: string;
source_kind: string;
response_id: string | null;
work_date: string;
rate: number;
currency: string;
terms_snapshot: Json;
eligible: boolean;
status: string;
note: string;
created_by: string | null;
created_at: string;
version: number;
};
Insert: {
id?: string;
assignment_id: string;
source_kind: string;
response_id?: string | null;
work_date: string;
rate: number;
currency: string;
terms_snapshot: Json;
eligible?: boolean;
status?: string;
note: string;
created_by?: string | null;
created_at?: string;
version?: number;
};
Update: {
id?: string;
assignment_id?: string;
source_kind?: string;
response_id?: string | null;
work_date?: string;
rate?: number;
currency?: string;
terms_snapshot?: Json;
eligible?: boolean;
status?: string;
note?: string;
created_by?: string | null;
created_at?: string;
version?: number;
};
Relationships: [];
};
}; Views: { [_ in never]: never }; Functions: {
act_work_payable: { Args: {
p_unit: string | null;
p_action: string | null;
p_amount: number | null;
p_note: string | null;
p_reference: string | null;
p_date: string | null;
p_reverses: string | null;
p_version: number | null;
p_request: string | null;
p_receipt?: string | null;
}; Returns: string };
apply_canonical_review: { Args: {
p_preview: Json | null;
p_status: string | null;
p_reason: string | null;
}; Returns: string };
apply_work_opportunity: { Args: {
p_opportunity: string | null;
p_availability: string | null;
p_note: string | null;
p_profile_share_consent: boolean | null;
}; Returns: string };
assign_project_staff: { Args: {
p_project: string | null;
p_user: string | null;
p_role: string | null;
p_areas: (string)[] | null;
p_starts: string | null;
p_ends: string | null;
}; Returns: string };
authorize_data_access_request: { Args: {
p_request: string | null;
p_decision: string | null;
p_fields: (string)[] | null;
p_expires_at: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: string };
authorize_payable_receipt: { Args: {
p_receipt: string | null;
}; Returns: string };
authorize_survey_capture_view: { Args: {
p_id: string | null;
}; Returns: string };
available_work_opportunities: { Args: {
p_page?: number | null;
p_organization?: string | null;
p_area?: string | null;
p_payment?: string | null;
p_skill?: string | null;
p_work_date?: string | null;
p_deadline?: string | null;
}; Returns: Json };
begin_document_delete: { Args: {
p_id: string | null;
}; Returns: string };
begin_document_upload: { Args: {
p_name: string | null;
p_type: string | null;
p_bytes: number | null;
p_kind: string | null;
}; Returns: Json };
begin_partner_ngo_document_delete: { Args: {
p_id: string | null;
}; Returns: string };
begin_partner_ngo_document_upload: { Args: {
p_application: string | null;
p_name: string | null;
p_type: string | null;
p_bytes: number | null;
p_kind: string | null;
}; Returns: Json };
cancel_work_assignment: { Args: {
p_id: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: undefined };
cancel_work_invitation: { Args: {
p_id: string | null;
p_version: number | null;
}; Returns: undefined };
canonical_assistance_timeline: { Args: {
p_person: string | null;
}; Returns: Json };
canonical_match_candidates: { Args: {
p_person: string | null;
}; Returns: Json };
canonical_person_summary: { Args: {
p_person: string | null;
}; Returns: Json };
canonical_workbench_detail: { Args: {
p_canonical: string | null;
p_section: string | null;
p_offset: number | null;
p_limit: number | null;
}; Returns: Json };
check_existing_identity: { Args: {
p_project: string | null;
p_name: string | null;
p_birth: string | null;
}; Returns: Json };
claim_work_payable: { Args: {
p_assignment: string | null;
p_day: string | null;
p_note: string | null;
}; Returns: string };
close_opportunity: { Args: {
p_id: string | null;
}; Returns: undefined };
close_survey_project: { Args: {
p_id: string | null;
}; Returns: undefined };
complete_work_assignment: { Args: {
p_id: string | null;
p_feedback: Json | null;
p_note: string | null;
p_version: number | null;
}; Returns: undefined };
correct_registry_person: { Args: {
p_id: string | null;
p_name: string | null;
p_birth: string | null;
p_household: string | null;
p_reason: string | null;
p_version: number | null;
}; Returns: undefined };
create_beneficiary_need: { Args: {
p_id: string | null;
p_response: string | null;
p_category: string | null;
p_description: string | null;
p_priority: string | null;
p_follow_up: string | null;
p_reason: string | null;
}; Returns: string };
create_data_access_request: { Args: {
p_person: string | null;
p_source_org: string | null;
p_purpose: string | null;
p_fields: (string)[] | null;
p_expires_at: string | null;
}; Returns: string };
create_finance_account: { Args: {
p_organization: string | null;
p_project: string | null;
p_user: string | null;
p_code: string | null;
p_name: string | null;
p_account_class: string | null;
p_purpose: string | null;
p_currency: string | null;
}; Returns: string };
create_opportunity: { Args: {
p_org: string | null;
p_title: string | null;
p_description: string | null;
p_geography: string | null;
p_start: string | null;
p_end: string | null;
p_reply_by: string | null;
p_payment: string | null;
p_payment_note: string | null;
}; Returns: string };
create_project_opportunity: { Args: {
p_project: string | null;
p_title: string | null;
p_description: string | null;
p_geography: string | null;
p_start: string | null;
p_end: string | null;
p_reply_by: string | null;
p_payment: string | null;
p_payment_note: string | null;
p_required_volunteers: number | null;
p_required_skill: string | null;
p_required_language: string | null;
}; Returns: string };
create_recruitment_opportunity: { Args: {
p_project: string | null;
p_title: string | null;
p_description: string | null;
p_geography: string | null;
p_start: string | null;
p_end: string | null;
p_reply_by: string | null;
p_payment: string | null;
p_payment_note: string | null;
p_required_volunteers: number | null;
p_required_skill: string | null;
p_required_language: string | null;
p_visibility: string | null;
p_eligibility_note: string | null;
p_publish: boolean | null;
}; Returns: string };
create_survey_project: { Args: {
p_org: string | null;
p_title: string | null;
p_template: string | null;
p_geography: string | null;
p_target: number | null;
p_start: string | null;
p_end: string | null;
p_purpose: string | null;
p_consent_version: string | null;
p_consent_notice: string | null;
}; Returns: string };
create_work_assignment: { Args: {
p_project: string | null;
p_user: string | null;
p_source_kind: string | null;
p_source_id: string | null;
p_work_mode: string | null;
p_compensation_type: string | null;
p_currency: string | null;
p_rate: number | null;
p_target_surveys: number | null;
p_start: string | null;
p_end: string | null;
p_terms_note: string | null;
}; Returns: string };
data_access_request_context: { Args: {
p_request: string | null;
}; Returns: Json };
data_sharing_sources: { Args: {
p_person: string | null;
}; Returns: Json };
document_download_path: { Args: {
p_id: string | null;
}; Returns: string };
download_field_project: { Args: {
p_project: string | null;
}; Returns: Json };
finance_account_balance: { Args: {
p_account: string | null;
}; Returns: number };
finance_account_statement: { Args: {
p_account: string | null;
p_before?: string | null;
p_limit?: number | null;
}; Returns: Json };
finance_scope_summary: { Args: {
p_organization: string | null;
p_project?: string | null;
}; Returns: Json };
finish_document_delete: { Args: {
p_id: string | null;
}; Returns: undefined };
finish_document_upload: { Args: {
p_id: string | null;
}; Returns: undefined };
finish_partner_ngo_document_delete: { Args: {
p_id: string | null;
}; Returns: undefined };
finish_partner_ngo_document_upload: { Args: {
p_id: string | null;
}; Returns: undefined };
get_shared_beneficiary_summary: { Args: {
p_grant: string | null;
}; Returns: Json };
list_independent_verifications: { Args: {
p_kind: string | null;
p_offset: number | null;
p_limit: number | null;
}; Returns: Json };
mark_notification_read: { Args: {
p_id: number | null;
}; Returns: undefined };
offer_work_amendment: { Args: {
p_assignment: string | null;
p_rate: number | null;
p_effective: string | null;
p_note: string | null;
}; Returns: string };
offline_capture_upload_complete: { Args: {
p_id: string | null;
}; Returns: boolean };
partner_ngo_document_download_path: { Args: {
p_id: string | null;
}; Returns: string };
post_finance_journal: { Args: {
p_organization: string | null;
p_project: string | null;
p_journal_type: string | null;
p_currency: string | null;
p_reference_type: string | null;
p_reference_id: string | null;
p_idempotency_key: string | null;
p_memo: string | null;
p_postings: Json | null;
}; Returns: string };
preview_canonical_review: { Args: {
p_person: string | null;
p_other: string | null;
}; Returns: Json };
project_compensation_status: { Args: {
p_project: string | null;
}; Returns: Json };
project_needs_summary: { Args: {
p_project: string | null;
p_person?: string | null;
}; Returns: Json };
project_recruitment_status: { Args: {
p_project: string | null;
}; Returns: Json };
project_staff_candidates: { Args: {
p_project: string | null;
p_query?: string | null;
}; Returns: Json };
project_staff_roster: { Args: {
p_project: string | null;
}; Returns: Json };
project_workforce_candidates: { Args: {
p_project: string | null;
p_query?: string | null;
p_page?: number | null;
}; Returns: Json };
publish_my_profile: { Args: {
p_details: Json | null;
p_version: number | null;
p_geography: string | null;
}; Returns: undefined };
publish_project_policy: { Args: {
p_project: string | null;
p_version: number | null;
p_retention_days: number | null;
p_discovery: string | null;
p_require_ngo: boolean | null;
p_require_volunteer: boolean | null;
p_paused: boolean | null;
p_reason: string | null;
}; Returns: number };
publish_survey_template: { Args: {
p_name: string | null;
p_questions: Json | null;
}; Returns: string };
publish_template_draft: { Args: {
p_id: string | null;
p_version: number | null;
}; Returns: string };
reconcile_canonical_identity: { Args: {
p_person: string | null;
p_source_version: number | null;
p_canonical_version: number | null;
p_reason: string | null;
}; Returns: undefined };
reconcile_survey_payable: { Args: {
p_response: string | null;
}; Returns: string };
record_assistance: { Args: {
p_id: string | null;
p_person: string | null;
p_kind: string | null;
p_category: string | null;
p_program: string | null;
p_description: string | null;
p_amount: number | null;
p_quantity: number | null;
p_unit: string | null;
p_delivered: string | null;
p_funding: string | null;
p_evidence: string | null;
p_next: string | null;
}; Returns: string };
registry_match_candidates: { Args: {
p_person: string | null;
}; Returns: Json };
request_independent_verification: { Args: {
p_kind: string | null;
p_subject: string | null;
p_evidence: string | null;
p_note: string | null;
}; Returns: string };
reserve_offline_capture_file: { Args: {
p_id: string | null;
p_project: string | null;
p_question: string | null;
p_filename: string | null;
p_mime: string | null;
p_size: number | null;
p_consent: Json | null;
}; Returns: string };
reserve_payable_receipt: { Args: {
p_assignment: string | null;
p_filename: string | null;
p_mime: string | null;
p_size: number | null;
}; Returns: string };
reserve_survey_capture_file: { Args: {
p_project: string | null;
p_question: string | null;
p_filename: string | null;
p_mime: string | null;
p_size: number | null;
p_consent: Json | null;
}; Returns: string };
respond_work_amendment: { Args: {
p_amendment: string | null;
p_status: string | null;
}; Returns: undefined };
respond_work_assignment: { Args: {
p_id: string | null;
p_status: string | null;
p_version: number | null;
}; Returns: undefined };
respond_work_invitation: { Args: {
p_id: string | null;
p_status: string | null;
p_version: number | null;
}; Returns: undefined };
reverse_finance_journal: { Args: {
p_journal: string | null;
p_idempotency_key: string | null;
p_reason: string | null;
}; Returns: string };
revert_canonical_merge: { Args: {
p_event: string | null;
p_reason: string | null;
p_primary_version: number | null;
p_secondary_version: number | null;
}; Returns: undefined };
review_canonical_match: { Args: {
p_person: string | null;
p_other: string | null;
p_status: string | null;
p_reason: string | null;
p_person_version: number | null;
p_other_version: number | null;
p_version: number | null;
}; Returns: string };
review_data_access_request: { Args: {
p_request: string | null;
p_decision: string | null;
p_fields: (string)[] | null;
p_note: string | null;
p_version: number | null;
}; Returns: undefined };
review_document: { Args: {
p_id: string | null;
p_status: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: undefined };
review_experience: { Args: {
p_id: string | null;
p_status: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: undefined };
review_independent_verification: { Args: {
p_id: string | null;
p_decision: string | null;
p_method: string | null;
p_note: string | null;
p_expires: string | null;
p_version: number | null;
}; Returns: undefined };
review_partner_ngo_application: { Args: {
p_id: string | null;
p_decision: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: string };
review_partner_ngo_document: { Args: {
p_id: string | null;
p_status: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: undefined };
review_profile: { Args: {
p_user_id: string | null;
p_status: string | null;
p_note: string | null;
p_version: number | null;
p_checks: Json | null;
}; Returns: undefined };
review_project_draft: { Args: {
p_id: string | null;
p_decision: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: string };
review_registry_match: { Args: {
p_person: string | null;
p_other: string | null;
p_status: string | null;
p_reason: string | null;
p_person_version: number | null;
p_other_version: number | null;
p_version: number | null;
}; Returns: undefined };
review_survey_response: { Args: {
p_id: string | null;
p_status: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: undefined };
review_template_draft: { Args: {
p_id: string | null;
p_decision: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: string };
review_work_application: { Args: {
p_id: string | null;
p_status: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: undefined };
revoke_data_access_grant: { Args: {
p_grant: string | null;
p_reason: string | null;
p_version: number | null;
}; Returns: undefined };
revoke_project_staff: { Args: {
p_id: string | null;
p_reason: string | null;
p_version: number | null;
}; Returns: undefined };
save_experience: { Args: {
p_id: string | null;
p_org: string | null;
p_role: string | null;
p_start: string | null;
p_end: string | null;
p_description: string | null;
p_request: boolean | null;
p_version: number | null;
}; Returns: string };
save_geography: { Args: {
p_id: string | null;
p_parent: string | null;
p_kind: string | null;
p_name: string | null;
p_code: string | null;
p_source: string | null;
p_active: boolean | null;
}; Returns: string };
save_my_profile: { Args: {
p_details: Json | null;
p_submit: boolean | null;
p_version: number | null;
p_geography: string | null;
}; Returns: undefined };
save_ngo_operations: { Args: {
p_org: string | null;
p_areas: (string)[] | null;
p_programs: (string)[] | null;
p_version: number | null;
}; Returns: undefined };
save_organization: { Args: {
p_id: string | null;
p_data: Json | null;
}; Returns: string };
save_organization_project_draft: { Args: {
p_id: string | null;
p_organization: string | null;
p_title: string | null;
p_template: string | null;
p_geography: string | null;
p_target: number | null;
p_start: string | null;
p_end: string | null;
p_purpose: string | null;
p_consent_version: string | null;
p_consent_notice: string | null;
p_version: number | null;
}; Returns: number };
save_organization_template_draft: { Args: {
p_id: string | null;
p_organization: string | null;
p_name: string | null;
p_questions: Json | null;
p_source: Json | null;
p_version: number | null;
}; Returns: number };
save_partner_ngo_application: { Args: {
p_id: string | null;
p_data: Json | null;
p_areas: (string)[] | null;
p_programs: (string)[] | null;
p_version: number | null;
}; Returns: string };
save_shortlist: { Args: {
p_org: string | null;
p_user: string | null;
p_status: string | null;
p_note: string | null;
p_version: number | null;
}; Returns: undefined };
save_survey_response: { Args: {
p_id: string | null;
p_project: string | null;
p_person: string | null;
p_household: string | null;
p_name: string | null;
p_birth: string | null;
p_household_label: string | null;
p_answers: Json | null;
p_consent: Json | null;
p_submit: boolean | null;
p_version: number | null;
p_request_id: string | null;
}; Returns: string };
save_template_draft: { Args: {
p_id: string | null;
p_name: string | null;
p_questions: Json | null;
p_source: Json | null;
p_version: number | null;
}; Returns: number };
search_canonical_registry: { Args: {
p_query: string | null;
p_state: string | null;
p_after: number | null;
p_limit: number | null;
}; Returns: Json };
search_volunteers: { Args: {
p_org?: string | null;
p_query?: string | null;
p_geography?: string | null;
p_skill?: string | null;
p_language?: string | null;
p_availability?: string | null;
p_status?: string | null;
p_shortlist?: string | null;
p_page?: number | null;
}; Returns: Json };
send_work_invitation: { Args: {
p_opportunity: string | null;
p_user: string | null;
}; Returns: string };
set_account_access: { Args: {
p_user: string | null;
p_role: string | null;
p_status: string | null;
}; Returns: undefined };
set_membership: { Args: {
p_org: string | null;
p_user: string | null;
p_role: string | null;
p_status: string | null;
}; Returns: undefined };
set_need_assistance_link: { Args: {
p_need: string | null;
p_assistance: string | null;
p_active: boolean | null;
p_reason: string | null;
p_need_version: number | null;
p_link_version: number | null;
}; Returns: undefined };
set_profile_photo: { Args: {
p_present: boolean | null;
}; Returns: undefined };
set_profile_sharing: { Args: {
p_org: string | null;
p_allowed: boolean | null;
}; Returns: undefined };
set_project_compensation_defaults: { Args: {
p_project: string | null;
p_work_mode: string | null;
p_compensation_type: string | null;
p_currency: string | null;
p_rate: number | null;
p_note: string | null;
p_reason: string | null;
p_version: number | null;
}; Returns: number };
set_project_recruitment_plan: { Args: {
p_project: string | null;
p_target: number | null;
p_required_volunteers: number | null;
p_status: string | null;
p_reason: string | null;
p_version: number | null;
}; Returns: number };
set_project_sharing_discovery: { Args: {
p_project: string | null;
p_enabled: boolean | null;
p_reason: string | null;
}; Returns: undefined };
set_survey_assignment: { Args: {
p_project: string | null;
p_user: string | null;
p_active: boolean | null;
}; Returns: undefined };
set_survey_assignment_scope: { Args: {
p_project: string | null;
p_user: string | null;
p_geography: string | null;
p_active: boolean | null;
}; Returns: undefined };
set_work_opportunity_state: { Args: {
p_id: string | null;
p_state: string | null;
p_version: number | null;
}; Returns: undefined };
submit_partner_ngo_application: { Args: {
p_id: string | null;
p_version: number | null;
}; Returns: undefined };
submit_project_draft: { Args: {
p_id: string | null;
p_version: number | null;
}; Returns: number };
submit_template_draft: { Args: {
p_id: string | null;
p_version: number | null;
}; Returns: number };
survey_assignment_candidates: { Args: {
p_project: string | null;
p_query: string | null;
}; Returns: Json };
update_beneficiary_need: { Args: {
p_id: string | null;
p_description: string | null;
p_priority: string | null;
p_status: string | null;
p_follow_up: string | null;
p_reason: string | null;
p_version: number | null;
}; Returns: undefined };
verification_subjects: { Args: {
p_kind: string | null;
p_query: string | null;
}; Returns: Json };
void_assistance: { Args: {
p_id: string | null;
p_reason: string | null;
p_version: number | null;
}; Returns: undefined };
withdraw_partner_ngo_application: { Args: {
p_id: string | null;
p_version: number | null;
}; Returns: undefined };
withdraw_work_application: { Args: {
p_id: string | null;
p_version: number | null;
}; Returns: undefined };
work_experience_history: { Args: {
p_user?: string | null;
p_page?: number | null;
}; Returns: Json };
work_payable_statement: { Args: {
p_assignment: string | null;
p_page?: number | null;
}; Returns: Json };
}; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never } } };
