import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {AreaSelector} from '../geography/AreaSelector';
import {selectableArea} from '../geography/areaSelection';
import {geographyPath,type Geo} from '../geography/model';
import {db,rpc} from '../../lib/supabase/client';
import type {Database} from '../../lib/supabase/database.types';
import {Badge,human} from '../../shared/ui/FormFields';

type Project=Database['public']['Tables']['survey_projects']['Row'];
type StaffArea={id:string;name:string;kind:string};
type StaffRow={id:string;user_id:string;name:string|null;role:string;status:string;starts_at:string;ends_at:string|null;version:number;areas:StaffArea[]};
type Metrics={submitted:number;approved:number;correction:number;rejected:number;assignments:number};
type Candidate={user_id:string;name:string|null;email:string|null;membership_role:string};

export function ProjectTeamWorkspace({userId,organization,projectId,geographies,canManageTeam}:{userId:string;organization:string|null;projectId?:string|null;geographies:Geo[];canManageTeam:boolean}){
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState(projectId||''),[roster,setRoster]=useState<StaffRow[]>([]),[metrics,setMetrics]=useState<Metrics>({submitted:0,approved:0,correction:0,rejected:0,assignments:0}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[role,setRole]=useState('project_manager'),[person,setPerson]=useState(''),[area,setArea]=useState<string|null>(null),[areas,setAreas]=useState<string[]>([]),[starts,setStarts]=useState(''),[ends,setEnds]=useState(''),[candidateQuery,setCandidateQuery]=useState(''),[candidates,setCandidates]=useState<Candidate[]>([]);
 const project=projects.find(p=>p.id===selected)||null;
 const own=roster.find(r=>r.user_id===userId&&r.status==='active');
 const projectAreas=useMemo(()=>project?geographies.filter(g=>g.id===project.geography_id||geographyPath(g.id,geographies).some(x=>x.id===project.geography_id)):[],[project,geographies]);
 useEffect(()=>{let live=true;setError('');(async()=>{let q=db!.from('survey_projects').select('*').order('created_at',{ascending:false}).limit(500);if(organization)q=q.eq('organization_id',organization);if(projectId)q=q.eq('id',projectId);const r=await q;if(r.error)throw r.error;if(!live)return;setProjects(r.data||[]);setSelected(old=>projectId||old||(r.data?.[0]?.id||''));})().catch(e=>live&&setError(e.message));return()=>{live=false}},[organization,projectId]);
 async function loadDetail(){if(!selected){setRoster([]);return}setBusy(true);setError('');try{const r=await rpc('project_staff_roster',{p_project:selected}) as unknown as StaffRow[];setRoster(r||[]);const counts=await Promise.all(['submitted','approved','correction_required','rejected'].map(status=>db!.from('survey_responses').select('id',{count:'exact',head:true}).eq('project_id',selected).eq('status',status)));const a=await db!.from('survey_assignments').select('id',{count:'exact',head:true}).eq('project_id',selected).eq('active',true);for(const x of [...counts,a])if(x.error)throw x.error;setMetrics({submitted:counts[0].count||0,approved:counts[1].count||0,correction:counts[2].count||0,rejected:counts[3].count||0,assignments:a.count||0});}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void loadDetail()},[selected]);
 useEffect(()=>{if(!canManageTeam||!selected){setCandidates([]);return}let live=true;rpc('project_staff_candidates',{p_project:selected,p_query:candidateQuery}).then(r=>{if(live)setCandidates((r||[]) as unknown as Candidate[])}).catch(e=>{if(live)setError((e as Error).message)});return()=>{live=false}},[canManageTeam,selected,candidateQuery,roster.length]);
 useEffect(()=>{if(project&&!starts)setStarts(project.start_date)},[project,starts]);
 function addArea(){if(!selectableArea(area,geographies)){setError('Choose an active area inside the project geography.');return}if(area&&!areas.includes(area))setAreas(v=>[...v,area]);setArea(null)}
 async function assign(e:FormEvent){e.preventDefault();if(!project)return;setBusy(true);setError('');setMessage('');try{await rpc('assign_project_staff',{p_project:project.id,p_user:person,p_role:role,p_areas:role==='area_focal_person'?areas:[],p_starts:starts,p_ends:ends||null});setMessage('Project staff assignment created.');setPerson('');setAreas([]);setArea(null);await loadDetail();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function revoke(row:StaffRow){const reason=window.prompt(`Reason for revoking ${row.name||row.user_id}?`,'Project staffing changed');if(!reason)return;setBusy(true);setError('');try{await rpc('revoke_project_staff',{p_id:row.id,p_reason:reason,p_version:row.version});setMessage('Project staff access revoked.');await loadDetail();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!projects.length&&!error)return <section className="panel detail"><h2>Project workspace</h2><p>No authorized project workspace is available.</p></section>;
 return <section className="panel detail project-team-workspace">
  <div className="panel-title"><div><span className="eyebrow">PROJECT OPERATIONS</span><h2>{canManageTeam?'Project team management':'Project workspace'}</h2><p>Project-scoped access is enforced by POEM database permissions.</p></div>{own&&<Badge value={own.role}/>}</div>
  {error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice success" role="status">{message}</p>}
  {!projectId&&<label className="field">Project<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}
  {project&&<>
   <div className="project-context-banner"><div><strong>{project.title}</strong><span>{geographyPath(project.geography_id,geographies).map(g=>g.name).join(' / ')}</span></div><div><span>Role</span><strong>{own?human(own.role):canManageTeam?'NGO Admin':'Authorized staff'}</strong></div>{own?.areas?.length?<div><span>Assigned scope</span><strong>{own.areas.map(a=>a.name).join(', ')}</strong></div>:null}</div>
   <div className="stats project-team-stats"><article className="stat"><div>Active volunteers</div><b>{metrics.assignments}</b></article><article className="stat"><div>Submitted</div><b>{metrics.submitted}</b></article><article className="stat"><div>Approved</div><b>{metrics.approved}</b></article><article className="stat"><div>Corrections</div><b>{metrics.correction}</b></article><article className="stat"><div>Rejected</div><b>{metrics.rejected}</b></article></div>
   {canManageTeam&&<form className="project-staff-form" onSubmit={assign}><h3>Assign project staff</h3><div className="form-grid"><label className="field">Find member<input value={candidateQuery} maxLength={100} placeholder="Name or email" onChange={e=>setCandidateQuery(e.target.value)}/></label><label className="field">Organization member<select required value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose active member</option>{candidates.map(a=><option key={a.user_id} value={a.user_id}>{a.name||a.email||a.user_id}</option>)}</select></label><label className="field">Role<select value={role} onChange={e=>{setRole(e.target.value);setAreas([]);setArea(null)}}><option value="project_manager">Project Manager</option><option value="area_focal_person">Area Focal Person</option></select></label><label className="field">Starts<input required type="date" min={project.start_date} max={project.end_date} value={starts} onChange={e=>setStarts(e.target.value)}/></label><label className="field">Ends (optional)<input type="date" min={starts||project.start_date} max={project.end_date} value={ends} onChange={e=>setEnds(e.target.value)}/></label></div>{role==='area_focal_person'&&<><AreaSelector rows={projectAreas} value={area} onChange={setArea} title="Focal area" disabled={busy}/><button type="button" className="secondary" onClick={addArea} disabled={busy||!area}>Add area</button><div className="selected-chips">{areas.map(id=><span className="chip" key={id}>{geographyPath(id,geographies).map(g=>g.name).join(' / ')} <button type="button" className="link" onClick={()=>setAreas(v=>v.filter(x=>x!==id))}>Remove</button></span>)}</div></>}<button className="primary" disabled={busy||!person||(role==='area_focal_person'&&!areas.length)}>Assign staff</button></form>}
   <div className="table-wrap"><table><thead><tr><th>Person</th><th>Role</th><th>Scope</th><th>Status</th><th>Dates</th>{canManageTeam&&<th>Action</th>}</tr></thead><tbody>{roster.map(r=><tr key={r.id}><td>{r.name||r.user_id}</td><td>{human(r.role)}</td><td>{r.role==='project_manager'?'Whole project':r.areas.map(a=>a.name).join(', ')||'—'}</td><td><Badge value={r.status}/></td><td>{r.starts_at} → {r.ends_at||'project end'}</td>{canManageTeam&&<td>{r.status==='active'?<button className="secondary" disabled={busy} onClick={()=>void revoke(r)}>Revoke</button>:'—'}</td>}</tr>)}</tbody></table></div>
   {!roster.length&&!busy&&<p>No project staff assignments yet.</p>}
  </>}
 </section>
}
