import {useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import {AreaSelector} from '../geography/AreaSelector';
import {selectableArea} from '../geography/areaSelection';
import {geographyPath,type Geo} from '../geography/model';
import {db,rpc} from '../../lib/supabase/client';
import type {Database} from '../../lib/supabase/database.types';
import {Badge,human} from '../../shared/ui/FormFields';
import {ActionDialog} from '../../components/ui/ActionDialog';

type Project=Database['public']['Tables']['survey_projects']['Row'];
type StaffArea={id:string;name:string;kind:string};
type StaffRow={id:string;user_id:string;name:string|null;role:string;status:string;starts_at:string;ends_at:string|null;version:number;areas:StaffArea[]};
type Candidate={user_id:string;name:string|null;email:string|null;membership_role:string};
type Assignment=Pick<Database['public']['Tables']['survey_assignments']['Row'],'user_id'|'collection_geography_id'>;
type ResponseRow=Pick<Database['public']['Tables']['survey_responses']['Row'],'id'|'person_id'|'collector_id'|'status'|'updated_at'|'collection_geography_id'>;
type Metrics={submitted:number;approved:number;correction:number;rejected:number;assignments:number};
type RecruitmentPlan={project_id:string;target:number;approved:number;pending_review:number;correction_required:number;rejected:number;remaining_target:number;over_target:number;target_reached:boolean;required_volunteers:number|null;committed_volunteers:number;remaining_capacity:number|null;capacity_reached:boolean;manual_status:'open'|'closed';effective_open:boolean;version:number};
type CompensationPlan={project_id:string;work_mode:'volunteer'|'paid';compensation_type:'none'|'per_verified_survey'|'daily_rate'|'fixed_assignment';currency:string;rate:number|null;note:string;version:number;can_change:boolean};
type PendingAction={kind:'revoke';row:StaffRow}|{kind:'recruitment'}|{kind:'compensation'}|null;

export function ProjectTeamWorkspace({userId,organization,projectId,geographies,canManageTeam,openOperations,openNotifications}:{userId:string;organization:string|null;projectId?:string|null;geographies:Geo[];canManageTeam:boolean;openOperations?:()=>void;openNotifications?:()=>void}){
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState(projectId||''),[roster,setRoster]=useState<StaffRow[]>([]),[metrics,setMetrics]=useState<Metrics>({submitted:0,approved:0,correction:0,rejected:0,assignments:0}),[assignments,setAssignments]=useState<Assignment[]>([]),[recent,setRecent]=useState<ResponseRow[]>([]),[personNames,setPersonNames]=useState<Record<string,string>>({}),[recruitment,setRecruitment]=useState<RecruitmentPlan|null>(null),[compensation,setCompensation]=useState<CompensationPlan|null>(null),[planTarget,setPlanTarget]=useState(''),[planVolunteers,setPlanVolunteers]=useState(''),[planStatus,setPlanStatus]=useState<'open'|'closed'>('open'),[compMode,setCompMode]=useState<'volunteer'|'paid'>('volunteer'),[compType,setCompType]=useState<CompensationPlan['compensation_type']>('none'),[compCurrency,setCompCurrency]=useState('PKR'),[compRate,setCompRate]=useState(''),[compNote,setCompNote]=useState('Volunteer / unpaid project'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[role,setRole]=useState('project_manager'),[person,setPerson]=useState(''),[area,setArea]=useState<string|null>(null),[areas,setAreas]=useState<string[]>([]),[starts,setStarts]=useState(''),[ends,setEnds]=useState(''),[candidateQuery,setCandidateQuery]=useState(''),[candidates,setCandidates]=useState<Candidate[]>([]);
 const [pendingAction,setPendingAction]=useState<PendingAction>(null);
 const detailRequest=useRef(0);
 const project=projects.find(p=>p.id===selected)||null;
 const own=roster.find(r=>r.user_id===userId&&r.status==='active');
 const projectAreas=useMemo(()=>project?geographies.filter(g=>g.id===project.geography_id||geographyPath(g.id,geographies).some(x=>x.id===project.geography_id)):[],[project,geographies]);
 const visibleAreaSummary=useMemo(()=>{const counts=new Map<string,number>();for(const row of assignments)counts.set(row.collection_geography_id,(counts.get(row.collection_geography_id)||0)+1);return [...counts.entries()].map(([id,count])=>({id,count,name:geographyPath(id,geographies).map(g=>g.name).join(' / ')||id})).sort((a,b)=>a.name.localeCompare(b.name));},[assignments,geographies]);
 const completion=project?.target?Math.min(100,Math.round((metrics.approved/project.target)*100)):0;
 const remaining=project?Math.max(0,project.target-metrics.approved):0;
 useEffect(()=>{let live=true;setError('');(async()=>{let q=db!.from('survey_projects').select('*').order('created_at',{ascending:false}).limit(500);if(organization)q=q.eq('organization_id',organization);if(projectId)q=q.eq('id',projectId);const r=await q;if(r.error)throw r.error;if(!live)return;setProjects(r.data||[]);setSelected(old=>projectId||old||(r.data?.[0]?.id||''));})().catch(e=>live&&setError((e as Error).message));return()=>{live=false}},[organization,projectId]);
 async function loadDetail(){if(!selected){setRoster([]);setAssignments([]);setRecent([]);setPersonNames({});setRecruitment(null);setCompensation(null);return}const request=++detailRequest.current;setBusy(true);setError('');try{const [staff,submitted,approved,correction,rejected,assignmentRows,responseRows]=await Promise.all([
   rpc('project_staff_roster',{p_project:selected}) as unknown as Promise<StaffRow[]>,
   db!.from('survey_responses').select('id',{count:'exact',head:true}).eq('project_id',selected).eq('status','submitted'),
   db!.from('survey_responses').select('id',{count:'exact',head:true}).eq('project_id',selected).eq('status','approved'),
   db!.from('survey_responses').select('id',{count:'exact',head:true}).eq('project_id',selected).eq('status','correction_required'),
   db!.from('survey_responses').select('id',{count:'exact',head:true}).eq('project_id',selected).eq('status','rejected'),
   db!.from('survey_assignments').select('user_id,collection_geography_id',{count:'exact'}).eq('project_id',selected).eq('active',true).order('collection_geography_id').limit(500),
   db!.from('survey_responses').select('id,person_id,collector_id,status,updated_at,collection_geography_id').eq('project_id',selected).order('updated_at',{ascending:false}).limit(8),
 ]);
 for(const result of [submitted,approved,correction,rejected,assignmentRows,responseRows])if(result.error)throw result.error;
 const visibleResponses=(responseRows.data||[]) as ResponseRow[];const ids=[...new Set(visibleResponses.map(r=>r.person_id))];let names:Record<string,string>={};if(ids.length){const people=await db!.from('registry_persons').select('id,full_name').in('id',ids);if(people.error)throw people.error;names=Object.fromEntries((people.data||[]).map(p=>[p.id,p.full_name]));}
 const ownStaff=(staff||[]).find(row=>row.user_id===userId&&row.status==='active');let plan:RecruitmentPlan|null=null;let comp:CompensationPlan|null=null;if(canManageTeam||ownStaff?.role==='project_manager'){[plan,comp]=await Promise.all([rpc('project_recruitment_status',{p_project:selected}) as unknown as Promise<RecruitmentPlan>,rpc('project_compensation_status',{p_project:selected}) as unknown as Promise<CompensationPlan>]);}
 if(request!==detailRequest.current)return;setRoster(staff||[]);setAssignments((assignmentRows.data||[]) as Assignment[]);setRecent(visibleResponses);setPersonNames(names);setMetrics({submitted:submitted.count||0,approved:approved.count||0,correction:correction.count||0,rejected:rejected.count||0,assignments:assignmentRows.count||0});setRecruitment(plan);setCompensation(comp);if(plan){setPlanTarget(String(plan.target));setPlanVolunteers(plan.required_volunteers===null?'':String(plan.required_volunteers));setPlanStatus(plan.manual_status);}if(comp){setCompMode(comp.work_mode);setCompType(comp.compensation_type);setCompCurrency(comp.currency);setCompRate(comp.rate===null?'':String(comp.rate));setCompNote(comp.note);}
 }catch(e){if(request===detailRequest.current)setError((e as Error).message)}finally{if(request===detailRequest.current)setBusy(false)}}
 useEffect(()=>{void loadDetail()},[selected]);
 useEffect(()=>{if(!canManageTeam||!selected){setCandidates([]);return}let live=true;const timer=window.setTimeout(()=>{rpc('project_staff_candidates',{p_project:selected,p_query:candidateQuery}).then(r=>{if(live)setCandidates((r||[]) as unknown as Candidate[])}).catch(e=>{if(live)setError((e as Error).message)});},250);return()=>{live=false;window.clearTimeout(timer)}},[canManageTeam,selected,candidateQuery,roster.length]);
 useEffect(()=>{if(project&&!starts)setStarts(project.start_date)},[project,starts]);
 function addArea(){if(!selectableArea(area,geographies)){setError('Choose an active area inside the project geography.');return}if(area&&!areas.includes(area))setAreas(v=>[...v,area]);setArea(null)}
 async function assign(e:FormEvent){e.preventDefault();if(!project)return;setBusy(true);setError('');setMessage('');try{await rpc('assign_project_staff',{p_project:project.id,p_user:person,p_role:role,p_areas:role==='area_focal_person'?areas:[],p_starts:starts,p_ends:ends||null});setMessage('Project staff assignment created.');setPerson('');setAreas([]);setArea(null);await loadDetail();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function revoke(row:StaffRow){setPendingAction({kind:'revoke',row})}
 function saveRecruitmentPlan(e:FormEvent){e.preventDefault();if(!project||!recruitment)return;setPendingAction({kind:'recruitment'})}
 function saveCompensationPlan(e:FormEvent){e.preventDefault();if(!project||!compensation||!compensation.can_change)return;setPendingAction({kind:'compensation'})}
 async function confirmPendingAction(reason:string){
  if(!pendingAction||!project)return;
  setBusy(true);setError('');setMessage('');
  try{
   if(pendingAction.kind==='revoke'){
    await rpc('revoke_project_staff',{p_id:pendingAction.row.id,p_reason:reason,p_version:pendingAction.row.version});
    setMessage('Project staff access revoked.');
   }else if(pendingAction.kind==='recruitment'){
    if(!recruitment)return;
    await rpc('set_project_recruitment_plan',{p_project:project.id,p_target:Number(planTarget),p_required_volunteers:Number(planVolunteers),p_status:planStatus,p_reason:reason,p_version:recruitment.version});
    setMessage('Project target and recruitment capacity updated.');
   }else{
    if(!compensation||!compensation.can_change)return;
    await rpc('set_project_compensation_defaults',{p_project:project.id,p_work_mode:compMode,p_compensation_type:compMode==='paid'?compType:'none',p_currency:compCurrency.toUpperCase(),p_rate:compMode==='paid'?Number(compRate):null,p_note:compNote,p_reason:reason,p_version:compensation.version});
    setMessage('Project compensation defaults updated. Existing opportunity and assignment snapshots were not changed.');
   }
   setPendingAction(null);await loadDetail();
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 if(!projects.length&&!error)return <section className="panel detail"><h2>Project workspace</h2><p>No authorized project workspace is available.</p></section>;
 return <section className="panel detail project-team-workspace">
  <div className="panel-title"><div><span className="eyebrow">PROJECT OPERATIONS</span><h2>{canManageTeam?'Project team management':'Project operational dashboard'}</h2><p>All counts, queues and area coverage are returned through your current database permissions.</p></div><div className="project-toolbar"><button type="button" className="secondary" disabled={busy||!selected} onClick={()=>void loadDetail()}>Refresh</button>{own&&<Badge value={own.role}/>}</div></div>
  {error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice success" role="status">{message}</p>}
  {!projectId&&<label className="field">Project<select value={selected} onChange={e=>{setSelected(e.target.value);setStarts('');setEnds('');setMessage('')}}><option value="">Choose project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}
  {project&&<>
   <div className="project-context-banner"><div><strong>{project.title}</strong><span>{geographyPath(project.geography_id,geographies).map(g=>g.name).join(' / ')}</span></div><div><span>Role</span><strong>{own?human(own.role):canManageTeam?'NGO Admin':'Authorized staff'}</strong></div>{own?.areas?.length?<div><span>Assigned scope</span><strong>{own.areas.map(a=>a.name).join(', ')}</strong></div>:<div><span>Project period</span><strong>{project.start_date} → {project.end_date}</strong></div>}</div>
   <div className="project-progress-card"><div><span className="eyebrow">ACCEPTED WORK PROGRESS</span><strong>{metrics.approved.toLocaleString()} / {project.target.toLocaleString()}</strong><small>{remaining.toLocaleString()} target responses remaining</small></div><div className="project-progress-meter"><progress max={100} value={completion} aria-label="Approved response target completion"/><span>{completion}%</span></div></div>
   {recruitment&&<section className="project-recruitment-plan"><div className="panel-title"><div><span className="eyebrow">SOFT TARGET & RECRUITMENT CAPACITY</span><h3>{recruitment.effective_open?'Recruitment open':'Recruitment paused'}</h3></div><Badge value={recruitment.effective_open?'open':'closed'}/></div><div className="stats project-team-stats"><article className="stat"><div>Approved target</div><b>{recruitment.approved.toLocaleString()} / {recruitment.target.toLocaleString()}</b></article><article className="stat"><div>Remaining target</div><b>{recruitment.remaining_target.toLocaleString()}</b></article><article className="stat"><div>Committed volunteers</div><b>{recruitment.committed_volunteers}{recruitment.required_volunteers===null?'':` / ${recruitment.required_volunteers}`}</b></article><article className="stat"><div>Open capacity</div><b>{recruitment.remaining_capacity===null?'Not configured':recruitment.remaining_capacity}</b></article></div>{recruitment.over_target>0&&<p className="notice">Over-target approved responses: {recruitment.over_target}. Existing/offline field submissions are retained; review and close collection operationally when appropriate.</p>}{recruitment.target_reached&&<p className="notice">Approved target reached. New recruitment/offers are blocked, but existing active field work can still synchronize.</p>}{recruitment.capacity_reached&&<p className="notice">Volunteer capacity reached. Increase capacity before creating new assignment offers.</p>}<form className="project-recruitment-form" onSubmit={saveRecruitmentPlan}><div className="form-grid"><label className="field">Approved-response target<input type="number" min={recruitment.target} max={1000000} required value={planTarget} onChange={e=>setPlanTarget(e.target.value)}/></label><label className="field">Required volunteers<input type="number" min={Math.max(1,recruitment.committed_volunteers)} max={5000} required value={planVolunteers} onChange={e=>setPlanVolunteers(e.target.value)}/></label><label className="field">Manual recruitment gate<select value={planStatus} onChange={e=>setPlanStatus(e.target.value as 'open'|'closed')}><option value="open">Open when target/capacity allow</option><option value="closed">Closed by manager</option></select></label></div><p>Target counts approved responses only. Closing recruitment does not reject already-created/offline survey submissions.</p><button className="secondary" disabled={busy||!planTarget||!planVolunteers}>Update recruitment plan</button></form></section>}
   {compensation&&<section className="project-compensation-plan"><div className="panel-title"><div><span className="eyebrow">COMPENSATION DEFAULTS</span><h3>{compensation.work_mode==='paid'?`${compensation.currency} ${Number(compensation.rate||0).toLocaleString()} · ${human(compensation.compensation_type)}`:'Volunteer / unpaid'}</h3><p>Defaults are snapshotted into each new recruitment opportunity. Formal assignment offers then inherit that opportunity snapshot and remain immutable.</p></div><Badge value={compensation.work_mode}/></div><p>{compensation.note}</p>{compensation.can_change?<form className="project-recruitment-form" onSubmit={saveCompensationPlan}><div className="form-grid"><label className="field">Work mode<select value={compMode} onChange={e=>{const mode=e.target.value as 'volunteer'|'paid';setCompMode(mode);if(mode==='volunteer'){setCompType('none');setCompRate('');if(!compNote.trim()||compNote===compensation.note)setCompNote('Volunteer / unpaid project')}else if(compType==='none')setCompType('per_verified_survey')}}><option value="volunteer">Volunteer / unpaid</option><option value="paid">Paid</option></select></label>{compMode==='paid'&&<><label className="field">Compensation basis<select value={compType} onChange={e=>setCompType(e.target.value as CompensationPlan['compensation_type'])}><option value="per_verified_survey">Per verified survey</option><option value="daily_rate">Daily rate</option><option value="fixed_assignment">Fixed assignment</option></select></label><label className="field">Currency<input value={compCurrency} maxLength={3} onChange={e=>setCompCurrency(e.target.value.toUpperCase())}/></label><label className="field">Rate<input type="number" min="0.01" step="0.01" required value={compRate} onChange={e=>setCompRate(e.target.value)}/></label></>}</div><label className="field">Compensation note<textarea minLength={3} maxLength={1000} required value={compNote} onChange={e=>setCompNote(e.target.value)}/></label><p>Changing these defaults affects only future opportunity snapshots. Existing published opportunities, assignment contracts and payable units keep their original terms.</p><button className="secondary" disabled={busy||!compNote.trim()||(compMode==='paid'&&(!compRate||compType==='none'))}>Update compensation defaults</button></form>:<p className="notice">Project Managers can use these terms for recruitment and assignment offers but cannot change the compensation defaults. NGO Admin or FieldLance survey-management authority is required.</p>}</section>}
   <div className="stats project-team-stats"><article className="stat"><div>Active volunteers</div><b>{metrics.assignments}</b></article><article className="stat"><div>Pending review</div><b>{metrics.submitted}</b></article><article className="stat"><div>Approved</div><b>{metrics.approved}</b></article><article className="stat"><div>Corrections</div><b>{metrics.correction}</b></article><article className="stat"><div>Rejected</div><b>{metrics.rejected}</b></article></div>
   {!canManageTeam&&<div className="project-quick-actions" aria-label="Project quick actions"><button className="primary" type="button" onClick={openOperations}>Open responses & reviews</button>{openNotifications&&<button className="secondary" type="button" onClick={openNotifications}>Open notifications</button>}</div>}
   {!canManageTeam&&<div className="project-operations-grid"><section className="project-operations-card"><div className="panel-title"><div><span className="eyebrow">FIELD COVERAGE</span><h3>Visible assignment areas</h3></div><span>{visibleAreaSummary.length} area{visibleAreaSummary.length===1?'':'s'}</span></div>{visibleAreaSummary.map(row=><div className="project-area-row" key={row.id}><span>{row.name}</span><strong>{row.count} active</strong></div>)}{!visibleAreaSummary.length&&!busy&&<p className="empty-state">No active volunteer assignment is visible in your current scope.</p>}</section><section className="project-operations-card"><div className="panel-title"><div><span className="eyebrow">REVIEW QUEUE</span><h3>Latest visible responses</h3></div><button type="button" className="link" onClick={openOperations}>Open all</button></div>{recent.map(row=><div className="project-response-row" key={row.id}><div><strong>{personNames[row.person_id]||`Response ${row.id.slice(0,8)}`}</strong><span>{geographyPath(row.collection_geography_id,geographies).map(g=>g.name).join(' / ')||'Collection area'}</span></div><div><Badge value={row.status}/><small>{new Date(row.updated_at).toLocaleString()}</small></div></div>)}{!recent.length&&!busy&&<p className="empty-state">No response is visible in your current scope.</p>}</section></div>}
   {canManageTeam&&<form className="project-staff-form" onSubmit={assign}><h3>Assign project staff</h3><div className="form-grid"><label className="field">Find member<input value={candidateQuery} maxLength={100} placeholder="Name or email" onChange={e=>setCandidateQuery(e.target.value)}/></label><label className="field">Organization member<select required value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose active member</option>{candidates.map(a=><option key={a.user_id} value={a.user_id}>{a.name||a.email||a.user_id}</option>)}</select></label><label className="field">Role<select value={role} onChange={e=>{setRole(e.target.value);setAreas([]);setArea(null)}}><option value="project_manager">Project Manager</option><option value="area_focal_person">Area Focal Person</option></select></label><label className="field">Starts<input required type="date" min={project.start_date} max={project.end_date} value={starts} onChange={e=>setStarts(e.target.value)}/></label><label className="field">Ends (optional)<input type="date" min={starts||project.start_date} max={project.end_date} value={ends} onChange={e=>setEnds(e.target.value)}/></label></div>{role==='area_focal_person'&&<><AreaSelector rows={projectAreas} value={area} onChange={setArea} title="Focal area" disabled={busy}/><button type="button" className="secondary" onClick={addArea} disabled={busy||!area}>Add area</button><div className="selected-chips">{areas.map(id=><span className="chip" key={id}>{geographyPath(id,geographies).map(g=>g.name).join(' / ')} <button type="button" className="link" onClick={()=>setAreas(v=>v.filter(x=>x!==id))}>Remove</button></span>)}</div></>}<button className="primary" disabled={busy||!person||(role==='area_focal_person'&&!areas.length)}>Assign staff</button></form>}
   <div className="table-wrap project-team-table"><table><thead><tr><th>Person</th><th>Role</th><th>Scope</th><th>Status</th><th>Dates</th>{canManageTeam&&<th>Action</th>}</tr></thead><tbody>{roster.map(r=><tr key={r.id}><td data-label="Person">{r.name||r.user_id}</td><td data-label="Role">{human(r.role)}</td><td data-label="Scope">{r.role==='project_manager'?'Whole project':r.areas.map(a=>a.name).join(', ')||'—'}</td><td data-label="Status"><Badge value={r.status}/></td><td data-label="Dates">{r.starts_at} → {r.ends_at||'project end'}</td>{canManageTeam&&<td data-label="Action">{r.status==='active'?<button className="secondary" disabled={busy} onClick={()=>revoke(r)}>Revoke</button>:'—'}</td>}</tr>)}</tbody></table></div>
   {!roster.length&&!busy&&<p>No project staff assignments yet.</p>}
  </>}
  <ActionDialog
   open={Boolean(pendingAction)}
   title={pendingAction?.kind==='revoke'?`Revoke ${pendingAction.row.name||'project staff'} access?`:pendingAction?.kind==='recruitment'?'Update recruitment plan?':'Update compensation defaults?'}
   description={pendingAction?.kind==='revoke'?'This removes the active project-staff assignment. Existing audit history is retained.':pendingAction?.kind==='recruitment'?'The target and recruitment-capacity controls affect future recruitment decisions; existing field submissions are retained.':'New compensation defaults apply only to future opportunity snapshots and do not rewrite existing assignments or payables.'}
   confirmLabel={pendingAction?.kind==='revoke'?'Revoke access':'Confirm update'}
   danger={pendingAction?.kind==='revoke'}
   reasonLabel="Reason for change"
   initialReason={pendingAction?.kind==='revoke'?'Project staffing changed':pendingAction?.kind==='recruitment'?'Operational recruitment plan updated':'Project compensation terms updated for future recruitment'}
   minReasonLength={5}
   busy={busy}
   onCancel={()=>setPendingAction(null)}
   onConfirm={confirmPendingAction}
  />
 </section>
}
