import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {db,rpc} from '../../lib/supabase/client';
import type {Database} from '../../lib/supabase/database.types';
import {Badge,human} from '../../shared/ui/FormFields';

type Project=Pick<Database['public']['Tables']['survey_projects']['Row'],'id'|'organization_id'|'title'|'status'|'compensation_currency'>;
type Org=Pick<Database['public']['Tables']['organizations']['Row'],'id'|'name'>;
type FundingSource={id:string;organization_id:string;source_type:string;name:string;external_reference:string|null;currency:string;note:string;created_at:string};
type FundingStatus={project_id:string;project_title:string;organization_id:string;project_status:string;currency:string;organization_available:number;project_reserved:number;project_committed:number;project_spent:number;project_funding_total:number;can_manage:boolean;can_record_external:boolean};
type FundingHistory={project_id:string;currency:string;rows:Array<{id:string;journal_type:string;memo:string;posted_at:string;created_by:string;amount:number}>};

const money=(value:number|string,currency:string)=>`${currency} ${Number(value||0).toLocaleString(undefined,{maximumFractionDigits:4})}`;

export function ProjectFundingWorkspace({organization,platform,orgs}:{organization:string|null;platform:boolean;orgs:Org[]}){
 const [org,setOrg]=useState(organization||''),[projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState(''),[currency,setCurrency]=useState('PKR'),[status,setStatus]=useState<FundingStatus|null>(null),[history,setHistory]=useState<FundingHistory['rows']>([]),[sources,setSources]=useState<FundingSource[]>([]),[source,setSource]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const selected=useMemo(()=>projects.find(p=>p.id===project)||null,[projects,project]);
 useEffect(()=>{setOrg(organization||'');setProject('');setStatus(null);setHistory([])},[organization]);
 useEffect(()=>{let live=true;if(!org){setProjects([]);return}setError('');db!.from('survey_projects').select('id,organization_id,title,status,compensation_currency').eq('organization_id',org).order('created_at',{ascending:false}).limit(500).then(({data,error})=>{if(!live)return;if(error)setError(error.message);else{const rows=(data||[]) as Project[];setProjects(rows);setProject(old=>rows.some(p=>p.id===old)?old:(rows[0]?.id||''));}});return()=>{live=false}},[org]);
 useEffect(()=>{if(selected?.compensation_currency)setCurrency(selected.compensation_currency)},[selected?.id]);
 async function load(){if(!project){setStatus(null);setHistory([]);setSources([]);setSource('');return}setBusy(true);setError('');try{const [s,h]=await Promise.all([rpc('project_funding_status',{p_project:project,p_currency:currency}) as unknown as Promise<FundingStatus>,rpc('project_funding_history',{p_project:project,p_currency:currency,p_before:null,p_limit:50}) as unknown as Promise<FundingHistory>]);setStatus(s);setHistory(h.rows||[]);if(org){const q=await db!.from('finance_funding_sources').select('*').eq('organization_id',org).eq('currency',currency).order('created_at',{ascending:false}).limit(100);if(q.error)throw q.error;setSources((q.data||[]) as FundingSource[]);setSource(old=>(q.data||[]).some(x=>x.id===old)?old:(q.data?.[0]?.id||''));}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void load()},[project,currency]);
 async function act(fn:()=>Promise<unknown>,success:string){setBusy(true);setError('');setMessage('');try{await fn();setMessage(success);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function reserve(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const amount=Number(f.get('amount'));const reason=String(f.get('reason')||'');await act(()=>rpc('reserve_project_funding',{p_project:project,p_currency:currency,p_amount:amount,p_idempotency_key:crypto.randomUUID(),p_reason:reason}),'Project funding reserved.');form.reset()}
 async function release(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const amount=Number(f.get('amount'));const reason=String(f.get('reason')||'');await act(()=>rpc('release_project_funding',{p_project:project,p_currency:currency,p_amount:amount,p_idempotency_key:crypto.randomUUID(),p_reason:reason}),'Unused project reservation released.');form.reset()}
 async function createSource(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await act(async()=>{const id=await rpc('create_finance_funding_source',{p_organization:org,p_source_type:String(f.get('type')),p_name:String(f.get('name')),p_external_reference:String(f.get('reference')||'')||null,p_currency:currency,p_note:String(f.get('note')||'')});setSource(id as string)},'Funding source registered.');form.reset()}
 async function recordFunding(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await act(()=>rpc('record_organization_funding',{p_source:source,p_amount:Number(f.get('amount')),p_idempotency_key:crypto.randomUUID(),p_memo:String(f.get('memo'))}),'Organization funding recorded in the immutable ledger.');form.reset()}
 return <section className="panel detail">
   <div className="panel-title"><div><span className="eyebrow">DOUBLE-ENTRY PROJECT FUNDING</span><h2>Project funding & reservation</h2><p>Available, reserved, committed and spent values are derived from immutable finance postings. There is no editable balance field.</p></div>{status&&<Badge value={status.project_status}/>}</div>
   {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="success">{message}</p>}
   <div className="form-grid">{platform&&<label className="field">Organization<select value={org} onChange={e=>{setOrg(e.target.value);setProject('')}}><option value="">Choose organization</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}<label className="field">Project<select value={project} onChange={e=>setProject(e.target.value)} disabled={!org}><option value="">Choose project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="field">Currency<input value={currency} maxLength={3} pattern="[A-Z]{3}" onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label></div>
   {status&&<><div className="stats"><article className="stat"><div>Organization available</div><b>{money(status.organization_available,currency)}</b></article><article className="stat"><div>Project reserved</div><b>{money(status.project_reserved,currency)}</b></article><article className="stat"><div>Committed</div><b>{money(status.project_committed,currency)}</b></article><article className="stat"><div>Spent</div><b>{money(status.project_spent,currency)}</b></article></div><p className="notice">Project funding total: <strong>{money(status.project_funding_total,currency)}</strong>. Committed and spent buckets are created now but remain zero until the payable-to-finance bridge in 2.17.2.</p></>}
   {status?.can_manage&&<div className="project-operations-grid"><form className="project-operations-card" onSubmit={reserve}><span className="eyebrow">RESERVE</span><h3>Move available funds into this project</h3><label className="field">Amount<input name="amount" type="number" min="0.0001" step="0.0001" required/></label><label className="field">Reason<textarea name="reason" minLength={3} maxLength={1000} required/></label><button className="primary" disabled={busy||!project}>Reserve funding</button></form><form className="project-operations-card" onSubmit={release}><span className="eyebrow">RELEASE</span><h3>Return unused reservation</h3><label className="field">Amount<input name="amount" type="number" min="0.0001" step="0.0001" required/></label><label className="field">Reason<textarea name="reason" minLength={3} maxLength={1000} required/></label><button className="secondary" disabled={busy||!project||Number(status.project_reserved)<=0}>Release reservation</button></form></div>}
   {platform&&status?.can_record_external&&org&&<section className="panel detail"><span className="eyebrow">VERIFIED FUNDING INTAKE</span><h3>Organization funding source</h3><p>Only POEM finance authority can establish or credit an external/opening funding source. NGO Admins can reserve verified available funds but cannot manufacture a balance.</p><form onSubmit={createSource}><div className="form-grid"><label className="field">Source type<select name="type" defaultValue="grant"><option value="opening_balance">Opening balance</option><option value="grant">Grant</option><option value="donation">Donation</option><option value="contribution">Contribution</option><option value="other">Other</option></select></label><label className="field">Source name<input name="name" minLength={2} maxLength={160} required/></label><label className="field">External reference<input name="reference" maxLength={200}/></label></div><label className="field">Note<textarea name="note" maxLength={1000}/></label><button className="secondary" disabled={busy}>Register source</button></form><form onSubmit={recordFunding}><div className="form-grid"><label className="field">Funding source<select value={source} onChange={e=>setSource(e.target.value)} required><option value="">Choose source</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name} · {human(s.source_type)}</option>)}</select></label><label className="field">Verified amount<input name="amount" type="number" min="0.0001" step="0.0001" required/></label></div><label className="field">Receipt / verification memo<textarea name="memo" minLength={3} maxLength={1000} required/></label><button className="primary" disabled={busy||!source}>Record verified funding</button></form></section>}
   <section className="panel"><div className="panel-title"><div><span className="eyebrow">FUNDING HISTORY</span><h3>Latest reservation movements</h3></div><span>{history.length} entries</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Movement</th><th>Amount</th><th>Memo</th></tr></thead><tbody>{history.map(row=><tr key={row.id}><td>{new Date(row.posted_at).toLocaleString()}</td><td>{human(row.journal_type)}</td><td>{money(row.amount,currency)}</td><td>{row.memo}</td></tr>)}</tbody></table></div>{!history.length&&!busy&&<p className="empty-state">No project funding movements for this currency yet.</p>}</section>
 </section>
}
