import { useEffect, useState, type FormEvent } from "react";
import { db, rpc } from "../../lib/supabase/client";
import type { Database } from "../../lib/supabase/database.types";
type Project=Database["public"]["Tables"]["survey_projects"]["Row"];
type Policy=Database["public"]["Tables"]["project_policy_versions"]["Row"];
export function ProjectGovernance({manage,organization}:{manage:boolean;organization:string|null}) {
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<Project|null>(null),[history,setHistory]=useState<Policy[]>([]);
 const [offset,setOffset]=useState(0),[more,setMore]=useState(false),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{let live=true;setBusy(true);setError("");let query=db!.from("survey_projects").select("*").order("id").range(offset,offset+25);if(organization)query=query.eq("organization_id",organization);void query.then(r=>{if(!live)return;if(r.error)setError(r.error.message);else{setProjects((r.data||[]).slice(0,25));setMore((r.data||[]).length>25)}setBusy(false)});return()=>{live=false}},[organization,offset,revision]);
 useEffect(()=>{let live=true;setHistory([]);if(!selected)return;void db!.from("project_policy_versions").select("*").eq("project_id",selected.id).order("version",{ascending:false}).limit(25).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else setHistory(r.data||[])});return()=>{live=false}},[selected]);
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||busy||(selected.governance_version>0 && (history[0]?.project_id!==selected.id || history[0]?.version!==selected.governance_version)))return;const f=new FormData(e.currentTarget);if(f.get("ack")!=="on")return;setBusy(true);setError("");try{await rpc("publish_project_policy",{p_project:selected.id,p_version:selected.governance_version,p_retention_days:Number(f.get("retention")),p_discovery:String(f.get("discovery")),p_require_ngo:f.get("ngo")==="on",p_require_volunteer:f.get("volunteer")==="on",p_paused:f.get("paused")==="on",p_reason:String(f.get("reason"))});setMessage("New policy published. Reload survey forms before collecting. Existing grants require separate revocation if access must end.");setSelected(null);setRevision(v=>v+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const latest=history[0];
 return <section className="panel detail"><h1>Project governance</h1><p>FieldLance publishes policy revisions. NGOs and assigned collectors can inspect their project policies. Retention is a documented review schedule; deletion and exports are not automated by this release.</p>{error&&<p role="alert" className="error-text">{error}</p>}{message&&<p role="status">{message}</p>}
 {projects.map(p=><article className="document-row" key={p.id}><strong>{p.title}</strong><p>{p.status} · {p.governance_version?`Policy v${p.governance_version}`:"Legacy policy — no verification gate configured"}</p><button className="secondary" disabled={busy} onClick={()=>setSelected(p)}>Inspect policy</button></article>)}
 {!busy&&!projects.length&&<p>No accessible projects.</p>}<div className="document-actions"><button className="secondary" disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</button><button className="secondary" disabled={busy||!more} onClick={()=>setOffset(offset+25)}>Next</button><button className="secondary" disabled={busy} onClick={()=>{setSelected(null);setRevision(v=>v+1)}}>Reload</button></div>
 {selected&&<section className="panel detail"><h2>{selected.title}</h2><p>Organization: {selected.organization_id}</p><p>Purpose: {selected.purpose}</p><p>Consent {selected.consent_version}: {selected.consent_notice}</p><p>{selected.governance_notice||"Legacy project: existing collection rules remain active until a policy is published."}</p>
 {manage&&<form key={selected.id+":"+selected.governance_version+":"+(latest?.version||0)} onSubmit={publish}><h3>Publish policy v{selected.governance_version+1}</h3><label className="field">Retention review after days<input name="retention" type="number" min={1} max={3650} required defaultValue={latest?.retention_days||365}/></label><label className="field">Cross-NGO source discovery<select name="discovery" defaultValue={latest?.discovery||(selected.sharing_discoverable?"request_required":"none")}><option value="none">None</option><option value="request_required">NGO name only; request required</option></select></label><p><label><input name="ngo" type="checkbox" defaultChecked={latest?.require_ngo_verification}/> Require current independent NGO verification for collection</label></p><p><label><input name="volunteer" type="checkbox" defaultChecked={latest?.require_volunteer_verification}/> Require current independent volunteer verification for collection</label></p><p><label><input name="paused" type="checkbox" defaultChecked={latest?.collection_paused}/> Pause collection</label></p><label className="field">Policy reason<textarea name="reason" required minLength={5} maxLength={1000}/></label><label><input name="ack" type="checkbox" required/> I reviewed the collection gates and policy-change impact on pending offline work.</label><p>Unsent work with an older policy must be reviewed and consent confirmed again. Already acknowledged retries retain their original receipt.</p><button disabled={busy || (selected.governance_version>0 && (latest?.project_id!==selected.id || latest?.version!==selected.governance_version))}>Publish immutable policy revision</button></form>}
 <h3>Policy history (latest 25)</h3>{history.map(p=><details key={p.version}><summary>v{p.version} · {new Date(p.published_at).toLocaleString()} · {p.reason}</summary><p>Published by {p.published_by}</p><p>Retention: {p.retention_days} days · discovery: {p.discovery} · collection: {p.collection_paused?"paused":"enabled"}</p><p>NGO verification: {p.require_ngo_verification?"required":"optional"} · volunteer verification: {p.require_volunteer_verification?"required":"optional"}</p><p>Consent {p.consent_version}: {p.consent_notice}</p></details>)}</section>}
 </section>;
}
