import {useEffect,useState,type FormEvent} from 'react';
import {db,rpc} from '../../lib/supabase/client';
import type {Database} from '../../lib/supabase/database.types';
import type {Geo} from '../geography/model';
import {OperationsForm} from './NgoOperations';
import {VerificationWorkspace} from '../verification/VerificationWorkspace';
type Org=Database['public']['Tables']['organizations']['Row'];
type Doc=Database['public']['Tables']['organization_compliance_documents']['Row'];
type Invite=Database['public']['Tables']['organization_invitations']['Row'];
type Member={user_id:string;name:string;email:string;role:string;status:string;version:number};
export function OrganizationSettings({organization,userId,geographies,reviewer=false,onChanged}:{organization:string;userId:string;geographies:Geo[];reviewer?:boolean;onChanged:()=>void}){
 const [tab,setTab]=useState('Profile'),[org,setOrg]=useState<Org|null>(null),[members,setMembers]=useState<Member[]>([]),[invitations,setInvitations]=useState<Invite[]>([]),[docs,setDocs]=useState<Doc[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;setBusy(true);setError('');Promise.all([db!.from('organizations').select('*').eq('id',organization).single(),rpc('organization_team',{p_org:organization}),db!.from('organization_invitations').select('*').eq('organization_id',organization).eq('status','pending').order('created_at',{ascending:false}),db!.from('organization_compliance_documents').select('*').eq('organization_id',organization).order('created_at',{ascending:false})]).then(([o,m,i,d])=>{if(!live)return;for(const r of [o,i,d])if(r.error)throw r.error;setOrg(o.data);setMembers(m as unknown as Member[]);setInvitations(i.data||[]);setDocs(d.data||[])}).catch(e=>live&&setError(e.message)).finally(()=>live&&setBusy(false));return()=>{live=false}},[organization,revision]);
 async function act(fn:()=>Promise<unknown>,success:string){setBusy(true);setError('');setMessage('');try{await fn();setMessage(success);setRevision(n=>n+1);onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!org)return;const f=new FormData(e.currentTarget);void act(()=>rpc('save_organization_settings',{p_org:organization,p_data:Object.fromEntries(['name','registration_number','contact_person','email','phone','address'].map(k=>[k,String(f.get(k)||'')])),p_version:org.settings_version}),'Organization profile saved.');}
 function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>rpc('invite_organization_member',{p_org:organization,p_email:String(f.get('email')),p_role:String(f.get('role'))}),'Invitation is ready in the recipient’s account. No email has been sent.');}
 function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('file') as File;void act(async()=>{const d=await rpc('reserve_organization_document',{p_org:organization,p_name:file.name,p_type:file.type,p_bytes:file.size,p_expires:String(f.get('expires')||'')||null}) as unknown as Doc;const result=await db!.storage.from('fieldlance-org-compliance').upload(d.object_path,file,{contentType:file.type,upsert:false});if(result.error)throw result.error;await rpc('finish_organization_document',{p_id:d.id});},'Document uploaded for review.');}
 async function download(d:Doc){try{const result=await db!.storage.from('fieldlance-org-compliance').createSignedUrl(d.object_path,60);if(result.error)throw result.error;window.open(result.data.signedUrl,'_blank','noopener,noreferrer')}catch(e){setError((e as Error).message)}}
 return <section className="panel detail"><h1>Organization Settings</h1><p>{org?.name} · {org?.status}</p><nav className="actions" aria-label="Organization settings sections">{['Profile','Operating Areas & Programs','Team & Members','Documents & Compliance','Verification'].map(t=><button type="button" className={tab===t?'primary':'secondary'} aria-pressed={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</nav>{error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">Updating organization…</p>}
 {tab==='Profile'&&org&&<form key={org.settings_version} onSubmit={save}><div className="form-grid">{(['name','registration_number','contact_person','email','phone','address'] as const).map(k=><label className="field" key={k}>{k.replaceAll('_',' ')}<input name={k} defaultValue={org[k]} required={k==='name'} maxLength={k==='name'?200:1000} type={k==='email'?'email':'text'}/></label>)}</div><p>Registration and name edits may require a new independent verification review.</p><button disabled={busy}>Save organization profile</button></form>}
 {tab==='Operating Areas & Programs'&&<OperationsForm orgId={organization} geographies={geographies} editable/>}
 {tab==='Team & Members'&&<><h2>Team & Members</h2><p>Members use their own accounts. Project staff roles are assigned separately in Project Team. Removing membership access retains history.</p><form onSubmit={invite}><div className="form-grid"><label className="field">Registered member email<input name="email" type="email" required/></label><label className="field">Role<select name="role"><option value="member">Member</option><option value="ngo_admin">Organization Admin</option></select></label></div><button disabled={busy}>Create invitation</button></form>{members.map(m=><article className="document-row" key={m.user_id}><h3>{m.name||m.email}</h3><p>{m.role==='ngo_admin'?'Organization Admin':'Member'} · {m.status}</p><div className="actions"><button disabled={busy} onClick={()=>{if(window.confirm('Change this member’s organization role?'))void act(()=>rpc('manage_organization_member',{p_org:organization,p_user:m.user_id,p_role:m.role==='ngo_admin'?'member':'ngo_admin',p_status:m.status,p_version:m.version}),'Role updated.')}}>Change role</button><button disabled={busy} onClick={()=>{if(window.confirm('Change this member’s organization access?'))void act(()=>rpc('manage_organization_member',{p_org:organization,p_user:m.user_id,p_role:m.role,p_status:m.status==='active'?'suspended':'active',p_version:m.version}),'Membership updated.')}}>{m.status==='active'?'Suspend access':'Restore access'}</button></div></article>)}<h3>Pending invitations</h3>{invitations.map(i=><article className="document-row" key={i.id}><p>{i.recipient_name} · {i.role==='ngo_admin'?'Organization Admin':'Member'} invitation · {new Date(i.expires_at)<=new Date()?'Expired':'Awaiting acceptance'} · Created {new Date(i.created_at).toLocaleDateString()}</p><button disabled={busy} onClick={()=>void act(()=>rpc('respond_organization_invitation',{p_id:i.id,p_decision:'cancelled',p_version:i.version}),'Invitation cancelled.')}>Cancel invitation</button></article>)}{!invitations.length&&<p>No pending invitations.</p>}</>}
 {tab==='Documents & Compliance'&&<><h2>Documents & Compliance</h2><p>Upload current registration, authorization and compliance evidence. Acceptance of a document does not independently verify the organization.</p><form onSubmit={upload}><label className="field">Document (PDF, PNG or JPG; max 5 MiB)<input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required/></label><label className="field">Expiry date (optional)<input name="expires" type="date"/></label><button disabled={busy}>Upload private document</button></form>{docs.map(d=><article className="document-row" key={d.id}><h3>{d.file_name}</h3><p>{d.state==='ready'?d.review_status:'Upload incomplete'} {d.expires_on&&`· Expires ${d.expires_on}${d.expires_on<new Date().toISOString().slice(0,10)?' — renewal required':''}`}</p><p>{d.review_note}</p>{d.state==='ready'&&<button onClick={()=>void download(d)}>Open document</button>}{reviewer&&d.state==='ready'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>rpc('review_organization_document',{p_id:d.id,p_status:String(f.get('decision')),p_note:String(f.get('note')),p_version:d.version}),'Review recorded.')}}><select name="decision"><option value="accepted">Accept</option><option value="rejected">Reject</option></select><label className="field">Review reason<input name="note" minLength={5} maxLength={1000} required/></label><button disabled={busy}>Record independent review</button></form>}</article>)}{!docs.length&&<p>No compliance documents uploaded.</p>}</>}
 {tab==='Verification'&&<VerificationWorkspace userId={userId} managers={{organization:reviewer,volunteer:false,beneficiary:false}}/>}
 </section>;
}
export function OrganizationInvitationInbox({userId,onChanged}:{userId:string;onChanged:()=>void}){
 const [rows,setRows]=useState<Array<Invite&{organization_name?:string}>>([]),[error,setError]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;db!.from('organization_invitations').select('*').eq('user_id',userId).eq('status','pending').order('created_at',{ascending:false}).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else setRows(r.data||[])});return()=>{live=false}},[userId,revision]);
 async function respond(i:Invite,decision:string){setBusy(true);setError('');try{await rpc('respond_organization_invitation',{p_id:i.id,p_decision:decision,p_version:i.version});setRevision(n=>n+1);onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!rows.length&&!error)return null;
 return <section className="panel detail"><h2>Organization membership invitations</h2>{error&&<p role="alert">{error}</p>}{rows.map(i=><article key={i.id} className="document-row"><p>{i.organization_name} · Organization membership · {i.role==='ngo_admin'?'Organization Admin':'Member'} · Expires {new Date(i.expires_at).toLocaleDateString()}</p><details><summary>Organization reference</summary>{i.organization_id}</details><button disabled={busy||new Date(i.expires_at)<=new Date()} onClick={()=>void respond(i,'accepted')}>Accept membership</button><button disabled={busy||new Date(i.expires_at)<=new Date()} onClick={()=>void respond(i,'declined')}>Decline</button></article>)}</section>;
}
