// Generates the app's public schema from the PostgreSQL catalog after migrations.
// Uses PGlite locally; no running Docker or service-role key required.
import {schemaDb} from './schema-test-db.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
const db=await schemaDb();
try{
 const rows=(await db.query(`select table_name,column_name,udt_name,is_nullable,column_default,is_identity from information_schema.columns where table_schema='public' order by table_name,ordinal_position`)).rows;
 function type(t){if(t.startsWith('_'))return `(${type(t.slice(1))})[]`;if(['int2','int4','int8','float4','float8','numeric'].includes(t))return 'number';if(t==='bool')return 'boolean';if(['json','jsonb'].includes(t))return 'Json';if(t==='void')return 'undefined';if(['uuid','text','varchar','timestamptz','timestamp','date'].includes(t))return 'string';throw Error('Unsupported PostgreSQL type: '+t)}
 let out='// Generated by npm run types:generate from applied PostgreSQL migrations. Do not edit.\nexport type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\nexport type Database = { public: { Tables: {\n';
 for(const table of [...new Set(rows.map(r=>r.table_name))]){
  const cols=rows.filter(r=>r.table_name===table);out+=`${table}: {\n`;
  for(const mode of ['Row','Insert','Update']){out+=`${mode}: {\n`;for(const c of cols){const optional=mode==='Update'||(mode==='Insert'&&(c.is_nullable==='YES'||c.column_default!==null||c.is_identity==='YES'));out+=`${c.column_name}${optional?'?':''}: ${type(c.udt_name)}${c.is_nullable==='YES'?' | null':''};\n`;}out+='};\n'}out+='Relationships: [];\n};\n';
 }
 out+='}; Views: { [_ in never]: never }; Functions: {\n';
 const funcs=(await db.query(`select p.proname,p.proargnames,p.proargtypes::oid[] as types,p.pronargdefaults,t.typname as result from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_type t on t.oid=p.prorettype where n.nspname='public' order by p.proname`)).rows;
 const typenames=new Map((await db.query('select oid,typname from pg_type')).rows.map(t=>[t.oid,t.typname]));
 for(const f of funcs){out+=`${f.proname}: { Args: {\n`;for(let i=0;i<f.types.length;i++)out+=`${f.proargnames[i]}${i>=f.types.length-f.pronargdefaults?'?':''}: ${type(typenames.get(f.types[i]))} | null;\n`;out+=`}; Returns: ${type(f.result)} };\n`}
 out+='}; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never } } };\n';
 const file='src/database.types.ts';if(process.argv.includes('--check')){if(readFileSync(file,'utf8')!==out)throw Error('Database types are stale. Run npm run types:generate');console.log('Database-generated types match all migrations.')}else{writeFileSync(file,out);console.log('Generated '+file)}
}finally{await db.close()}
