import assert from 'node:assert/strict';import {schemaDb} from './schema-test-db.mjs';
const db=await schemaDb();let passed=0;const ids=Object.fromEntries(['super','manager','ngo','otherngo','a','b'].map((n,i)=>[n,`50000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`]));
const rows=async(q,p=[]) => (await db.query(q,p)).rows;async function as(n){await db.exec('RESET ROLE');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[n]||'']);await db.exec('SET ROLE '+(n?'authenticated':'anon'))}async function call(n,a){if(n==='save_survey_response')a=[...a,crypto.randomUUID()];return (await rows(`select public.${n}(${a.map((_,i)=>'$'+(i+1)).join(',')}) result`,a))[0].result}const deny=(f,re=/required|permission|unavailable|not found/i)=>assert.rejects(f,re);async function ok(n,f){await f();passed++;console.log('PASS '+n)}
try{
for(const [name,id] of Object.entries(ids))await db.query('insert into auth.users(id,email) values($1,$2)',[id,name+'@example.test']);await db.query("update public.accounts set platform_role='super_admin' where id=$1",[ids.super]);await as('super');await call('set_account_access',[ids.manager,'survey_manager','active']);const org=await call('save_organization',[null,{name:'Pilot NGO',status:'active'}]),other=await call('save_organization',[null,{name:'Other NGO',status:'active'}]);await call('set_membership',[org,ids.ngo,'ngo_admin','active']);await call('set_membership',[other,ids.otherngo,'ngo_admin','active']);const geo=await call('save_geography',[null,null,'province','Test Province','P21','Synthetic fixture',true]);
await db.exec('RESET ROLE');await db.query("update public.volunteer_profiles set status='verified' where user_id in ($1,$2)",[ids.a,ids.b]);await as('a');await call('set_profile_sharing',[org,true]);await as('b');await call('set_profile_sharing',[org,true]);
await as('manager');const qs=[{id:'need',label:'Main need',type:'choice',options:['Education','Food'],required:true},{id:'count',label:'Count',type:'number',required:false},{id:'yes',label:'Yes/no',type:'yesno',required:false},{id:'date',label:'Visit date',type:'date',required:false}];const t1=await call('publish_survey_template',['Household pilot',qs]);const t2=await call('publish_survey_template',['Household pilot',[...qs,{id:'note',label:'Note',type:'text',required:false}]]);
await ok('template versions immutable and sequential',async()=>{const v=await rows('select version from public.survey_templates order by version');assert.deepEqual(v.map(r=>r.version),[1,2]);await deny(()=>db.query('update public.survey_templates set questions=$1 where id=$2',[[],t1]),/permission/)});
await ok('invalid and duplicate question definitions rejected',async()=>{await deny(()=>call('publish_survey_template',['Bad form',[qs[0],qs[0]]]),/unique/);await deny(()=>call('publish_survey_template',['Bad form',[{...qs[0],label:{bad:true}}]]),/Invalid/);await deny(()=>call('publish_survey_template',['Bad form',[{...qs[0],options:['x','x']}]]),/unique/)});
const dates=(await rows("select ((now() at time zone 'UTC')::date-1)::text as start,((now() at time zone 'UTC')::date+3)::text as end"))[0];const project=await call('create_survey_project',[org,'Household pilot project',t1,geo,100,dates.start,dates.end,'Assess education and food needs','pilot-v1','Explain that POEM and the project NGO store the survey for needs assessment.']);
await ok('project pins original template and policy',async()=>{const p=(await rows('select * from public.survey_projects where id=$1',[project]))[0];assert.equal(p.template_id,t1);assert.equal(p.consent_version,'pilot-v1');await deny(()=>db.query('update public.survey_projects set template_id=$1 where id=$2',[t2,project]),/permission/)});
await call('set_survey_assignment',[project,ids.a,true]);
const consent={agreed:true,method:'verbal',representative:'Guardian Test',relationship:'Mother'};const answers={need:'Education',count:3,yes:false,date:'2026-01-01'};
const save=(opts={})=>{const o={id:null,person:null,house:null,name:'Child Test',birth:'2020-01-01',label:'Household Test',answers,consent,submit:true,version:0,...opts};return call('save_survey_response',[o.id,project,o.person,o.house,o.name,o.birth,o.label,o.answers,o.consent,o.submit,o.version])};
await as('b');await ok('unassigned volunteer cannot read project or submit',async()=>{assert.equal((await rows('select * from public.survey_projects')).length,0);await deny(()=>save())});
await as('a');await ok('assigned surveyor can read only project template',async()=>{assert.equal((await rows('select * from public.survey_projects')).length,1);assert.deepEqual((await rows('select id from public.survey_templates')).map(t=>t.id),[t1])});
await ok('consent and guardian required before personal data save',async()=>{await deny(()=>save({consent:{agreed:false,method:'verbal'}}),/consent/);await deny(()=>save({consent:{agreed:true,method:'verbal'}}),/Guardian/);assert.equal((await rows('select * from public.registry_persons')).length,0)});
await ok('typed answers and required fields enforced',async()=>{await deny(()=>save({answers:{need:'Invalid'}}),/choice/);await deny(()=>save({answers:{need:'Education',count:'3'}}),/Numeric/);await deny(()=>save({answers:{need:'Education',yes:'false'}}),/Yes/);await deny(()=>save({answers:{need:'Education',date:'2026-02-30'}}),/date/);await deny(()=>save({answers:{}}),/Required/);await deny(()=>save({answers:{need:'Education',unexpected:'x'}}),/Unknown/)});
const response=await save();const person=(await rows('select * from public.registry_persons'))[0];const household=(await rows('select * from public.registry_households'))[0];await ok('atomic person household response and consent provenance saved',async()=>{assert(person.registry_no);assert.equal(person.household_id,household.id);const r=(await rows('select * from public.survey_responses where id=$1',[response]))[0];assert.equal(r.consent.consent_version,'pilot-v1');assert.equal(r.consent.collector_id,ids.a);assert.equal(r.answers.yes,false);assert.equal((await rows('select * from public.survey_response_revisions')).length,1)});
await ok('submitted response cannot be edited directly',async()=>deny(()=>save({id:response,version:1}),/locked/));
await as('otherngo');await ok('other NGO cannot read registry responses or revisions',async()=>{for(const table of ['survey_projects','registry_persons','registry_households','survey_responses','survey_response_revisions'])assert.equal((await rows('select * from public.'+table)).length,0);await deny(()=>call('review_survey_response',[response,'approved','Forbidden',1]))});
await as('ngo');await call('review_survey_response',[response,'correction_required','Clarify the need',1]);await as('a');await ok('review correction visible with version and history',async()=>{const r=(await rows('select * from public.survey_responses where id=$1',[response]))[0];assert.equal(r.status,'correction_required');assert.equal(r.version,2);assert.equal((await rows('select * from public.survey_response_revisions')).length,2)});
await save({id:response,answers:{...answers,need:'Food'},version:2});await as('ngo');await ok('stale review blocked',async()=>deny(()=>call('review_survey_response',[response,'approved','Checked',2]),/current/));await call('review_survey_response',[response,'approved','Checked household need',3]);await ok('approved survey leaves identity provisional',async()=>{assert.equal((await rows('select identity_status from public.registry_persons where id=$1',[person.id]))[0].identity_status,'provisional');assert.equal((await rows('select * from public.survey_response_revisions where response_id=$1',[response])).length,4)});
await as('a');const draft=await save({person:person.id,answers:{},submit:false});await ok('reuse person avoids duplicate identity; online drafts permit missing answers',async()=>{assert.equal((await rows('select * from public.registry_persons')).length,1);assert.equal((await rows('select status from public.survey_responses where id=$1',[draft]))[0].status,'draft')});await save({house:household.id,name:'Second Child',submit:false,answers:{}});await ok('household supports multiple separate people',async()=>{assert.equal((await rows('select * from public.registry_persons')).length,2);assert.equal((await rows('select * from public.registry_households')).length,1)});
await as('ngo');await call('set_survey_assignment',[project,ids.b,true]);await as('b');await ok('second surveyor cannot browse or reuse first surveyor identities',async()=>{assert.equal((await rows('select * from public.registry_persons')).length,0);assert.equal((await rows('select * from public.survey_responses')).length,0);await deny(()=>save({person:person.id}))});
await as('super');await call('set_membership',[org,ids.a,'ngo_admin','active']);await as('a');await ok('collector cannot self-review even with NGO admin role',async()=>deny(()=>call('review_survey_response',[response,'approved','Self review',4]),/own/));
await as('ngo');await call('set_survey_assignment',[project,ids.b,false]);await as('b');await ok('revoked assignment removes old-session access',async()=>{assert.equal((await rows('select * from public.survey_projects')).length,0);await deny(()=>save())});
await as('manager');await call('close_survey_project',[project]);await as('a');await ok('closed project blocks collection while retaining history',async()=>{await deny(()=>save());assert((await rows('select * from public.survey_responses')).length>0)});
await as(null);await ok('anonymous denied pilot operations',async()=>{await deny(()=>save());await deny(()=>call('publish_survey_template',['No',qs]))});
console.log(`\n${passed} Phase 2.1 survey/registry tests passed.`);
}finally{await db.close()}
