import assert from 'node:assert/strict';
import {schemaDb} from './schema-test-db.mjs';
const db=await schemaDb();let passed=0;const ids={super:'40000000-0000-4000-8000-000000000001',ngo:'40000000-0000-4000-8000-000000000002',other:'40000000-0000-4000-8000-000000000003',a:'40000000-0000-4000-8000-000000000004',b:'40000000-0000-4000-8000-000000000005'};
const rows=async(q,p=[]) => (await db.query(q,p)).rows;
async function as(name){await db.exec('RESET ROLE');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[name]||'']);await db.exec('SET ROLE '+(name?'authenticated':'anon'))}
async function call(n,a){return (await rows(`select public.${n}(${a.map((_,i)=>'$'+(i+1)).join(',')}) result`,a))[0].result}
async function ok(n,f){await f();passed++;console.log('PASS '+n)}
const deny=(f,re=/required|denied|access|not found/i)=>assert.rejects(f,re);
try{
for(const [name,id] of Object.entries(ids))await db.query('insert into auth.users(id,email) values($1,$2)',[id,name+'@test.example']);await db.query("update public.accounts set platform_role='super_admin' where id=$1",[ids.super]);
await as('super');const org=await call('save_organization',[null,{name:'NGO A',status:'active'}]),orgB=await call('save_organization',[null,{name:'NGO B',status:'active'}]);await call('set_membership',[org,ids.ngo,'ngo_admin','active']);await call('set_membership',[orgB,ids.other,'ngo_admin','active']);const geo=await call('save_geography',[null,null,'province','Fixture Province','P14','Synthetic',true]);
await as('a');const exp=await call('save_experience',[null,org,'Field surveyor','2025-01-01','2025-02-01','Completed household survey work.',false,0]);
await as('ngo');await ok('unrequested experience remains private to owner/POEM',async()=>assert.equal((await rows('select * from public.volunteer_experiences')).length,0));
await as('a');await call('save_experience',[exp,org,'Field surveyor','2025-01-01','2025-02-01','Completed household survey work.',true,1]);
await as('ngo');await ok('explicit confirmation request shares entry without full CV',async()=>{assert.equal((await rows('select * from public.volunteer_experiences')).length,1);assert.equal((await rows('select * from public.volunteer_profiles where user_id=$1',[ids.a])).length,0);assert((await rows("select * from public.notifications where title='Experience confirmation requested'")).length>0)});
await as('other');await ok('unrelated NGO cannot review requested experience',async()=>{assert.equal((await rows('select * from public.volunteer_experiences')).length,0);await deny(()=>call('review_experience',[exp,'verified','Confirmed',2]))});
await as('super');await ok('platform Super Admin cannot impersonate confirming NGO',async()=>deny(()=>call('review_experience',[exp,'verified','Confirmed',2])));
await as('ngo');await call('review_experience',[exp,'verified','Records checked',2]);await as('a');await ok('verified badge has reviewer timestamp and notification',async()=>{const e=(await rows('select * from public.volunteer_experiences where id=$1',[exp]))[0];assert.equal(e.status,'verified');assert(e.reviewed_at);assert.equal(e.reviewed_by,ids.ngo);assert((await rows("select * from public.notifications where title='Experience review'")).length>0)});
await ok('stale experience edit rejected',async()=>deny(()=>call('save_experience',[exp,org,'Surveyor','2025-01-01',null,'Updated work description',true,2]),/changed/));
await call('save_experience',[exp,org,'Senior surveyor','2025-01-01',null,'Updated work description',true,3]);await ok('editing verified experience clears previous confirmation',async()=>{const e=(await rows('select * from public.volunteer_experiences where id=$1',[exp]))[0];assert.equal(e.status,'pending');assert.equal(e.reviewed_by,null);assert.equal(e.reviewed_at,null)});
await as('ngo');await call('review_experience',[exp,'rejected','Cannot substantiate changed role',4]);await ok('rejected experience cannot be silently re-reviewed',async()=>deny(()=>call('review_experience',[exp,'verified','Reconsidered',5]),/not pending/));
const own=await call('save_experience',[null,org,'NGO manager','2025-01-01',null,'Managed local NGO operations.',true,0]);await ok('NGO admin cannot confirm own experience',async()=>deny(()=>call('review_experience',[own,'verified','Self review',1]),/own/));
await as('a');await ok('future/reversed dates rejected',async()=>{await deny(()=>call('save_experience',[null,org,'Surveyor','2099-01-01',null,'Detailed work description',false,0]),/dates/);await deny(()=>call('save_experience',[null,org,'Surveyor','2025-02-01','2025-01-01','Detailed work description',false,0]),/dates/)});
await as('ngo');const future=(await rows("select ((now() at time zone 'UTC')::date+2)::text as start,((now() at time zone 'UTC')::date+5)::text as end,(now()+interval '1 day')::text as deadline"))[0];
const newOp=(title='Field opportunity')=>call('create_opportunity',[org,title,'Assist with household assessments.',geo,future.start,future.end,future.deadline,'paid','Proposed rate subject to separate agreement']);
const op=await newOp();await ok('NGO creates immutable opportunity with explicit terms',async()=>{assert.equal((await rows('select * from public.work_opportunities where id=$1',[op]))[0].payment_type,'paid');await deny(()=>db.query('update public.work_opportunities set title=$1 where id=$2',['Changed',op]),/permission/)});
await ok('invitation requires profile grant',async()=>deny(()=>call('send_work_invitation',[op,ids.a])));
await as('a');await call('set_profile_sharing',[org,true]);await as('ngo');await ok('invitation also requires shortlist',async()=>deny(()=>call('send_work_invitation',[op,ids.a]),/Shortlist/));await call('save_shortlist',[org,ids.a,'shortlisted','Suitable candidate',0]);const inv=await call('send_work_invitation',[op,ids.a]);
await ok('duplicate invitation blocked without extra record',async()=>{await deny(()=>call('send_work_invitation',[op,ids.a]),/already/);assert.equal((await rows('select * from public.work_invitations where opportunity_id=$1',[op])).length,1)});
await as('b');await ok('uninvited user cannot read opportunity or respond',async()=>{assert.equal((await rows('select * from public.work_opportunities')).length,0);assert.equal((await rows('select * from public.work_invitations')).length,0);await deny(()=>call('respond_work_invitation',[inv,'accepted',1]))});
await as('a');await ok('recipient sees immutable opportunity details',async()=>assert.equal((await rows('select * from public.work_opportunities where id=$1',[op])).length,1));
await call('respond_work_invitation',[inv,'accepted',1]);await ok('accepted response stored and repeat/stale response denied',async()=>{assert.equal((await rows('select * from public.work_invitations where id=$1',[inv]))[0].status,'accepted');await deny(()=>call('respond_work_invitation',[inv,'declined',1]),/changed/)});
await as('ngo');await ok('response notifies NGO and accepted invitation cannot be cancelled',async()=>{assert((await rows("select * from public.notifications where title='Invitation response'")).length>0);await deny(()=>call('cancel_work_invitation',[inv,2]),/pending/)});
const op2=await newOp('Second opportunity');const inv2=await call('send_work_invitation',[op2,ids.a]);await call('close_opportunity',[op2]);await as('a');await ok('closing opportunity cancels its pending invitations',async()=>{assert.equal((await rows('select * from public.work_invitations where id=$1',[inv2]))[0].status,'cancelled');await deny(()=>call('respond_work_invitation',[inv2,'accepted',1]),/changed/)});
await as('ngo');const op3=await newOp('Expired opportunity');const inv3=await call('send_work_invitation',[op3,ids.a]);await db.exec('RESET ROLE');await db.query("update public.work_opportunities set reply_by=now()-interval '1 second' where id=$1",[op3]);await as('a');await ok('server rejects expired invitation response',async()=>deny(()=>call('respond_work_invitation',[inv3,'accepted',1]),/expired/));await as('ngo');await ok('server rejects new invitation for expired opportunity',async()=>deny(()=>call('send_work_invitation',[op3,ids.a]),/expired/));
const op4=await newOp('Revoked invitation');const inv4=await call('send_work_invitation',[op4,ids.a]);await as('a');await call('set_profile_sharing',[org,false]);await ok('sharing revocation cancels pending but preserves accepted history',async()=>{assert.equal((await rows('select * from public.work_invitations where id=$1',[inv4]))[0].status,'cancelled');assert.equal((await rows('select * from public.work_invitations where id=$1',[inv]))[0].status,'accepted')});await as('ngo');await ok('revocation hides recipient invitation records from NGO',async()=>assert.equal((await rows('select * from public.work_invitations')).length,0));
await as('a');await call('set_profile_sharing',[org,true]);await as('ngo');await call('save_shortlist',[org,ids.a,'shortlisted','New permission',0]);const op5=await newOp('Cancellation opportunity');const inv5=await call('send_work_invitation',[op5,ids.a]);await call('cancel_work_invitation',[inv5,1]);await ok('explicit NGO cancellation is versioned',async()=>assert.equal((await rows('select version from public.work_invitations where id=$1',[inv5]))[0].version,2));
const declinedOp=await newOp('Declined opportunity');const declinedInvite=await call('send_work_invitation',[declinedOp,ids.a]);await as('a');await call('respond_work_invitation',[declinedInvite,'declined',1]);await ok('recipient can decline and retains history',async()=>assert.equal((await rows('select status from public.work_invitations where id=$1',[declinedInvite]))[0].status,'declined'));
await as('ngo');const suspendedOp=await newOp('Suspended organization');const suspendedInvite=await call('send_work_invitation',[suspendedOp,ids.a]);await as('super');await call('save_organization',[org,{name:'NGO A',status:'suspended'}]);await as('a');await ok('suspended organization prevents recipient acceptance',async()=>deny(()=>call('respond_work_invitation',[suspendedInvite,'accepted',1])));await as('super');await call('save_organization',[org,{name:'NGO A',status:'active'}]);
await as('super');await call('set_membership',[org,ids.ngo,'ngo_admin','suspended']);await as('ngo');await ok('suspended NGO membership cannot create opportunities',async()=>deny(()=>newOp()));
await as(null);await ok('anonymous denied all new operations',async()=>{await deny(()=>newOp());await deny(()=>call('review_experience',[exp,'verified','Forbidden',5]));await deny(()=>call('respond_work_invitation',[inv,'accepted',1]))});
console.log(`\n${passed} Phase 1.4 experience/invitation tests passed.`);
}finally{await db.close()}
