import assert from 'node:assert/strict';
import {schemaDb} from './schema-test-db.mjs';
const db=await schemaDb();let count=0;
const ids=Object.fromEntries(['super','vm','nm','auditor','ngo','ngo2','a','b'].map((name,i)=>[name,`20000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`]));
const rows=async(q,p=[]) => (await db.query(q,p)).rows;
async function as(name){await db.exec('RESET ROLE');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[name]||'']);await db.exec('SET ROLE '+(name?'authenticated':'anon'))}
async function call(name,args){return (await rows(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args))[0].result}
const search=(org=null,over={})=>{const f={query:'',geo:null,skill:'',lang:'',available:'',status:'',shortlist:'',page:0,...over};return call('search_volunteers',[org,f.query,f.geo,f.skill,f.lang,f.available,f.status,f.shortlist,f.page])};
const check=async(name,fn)=>{await fn();console.log('PASS '+name);count++};
const denied=(fn,re=/permission|access|required|denied/i)=>assert.rejects(fn,re);
try{
for(const [name,id] of Object.entries(ids))await db.query('insert into auth.users(id,email) values($1,$2)',[id,name+'@example.test']);
await db.query("update public.accounts set platform_role='super_admin' where id=$1",[ids.super]);
await as('super');for(const [key,role] of [['vm','volunteer_manager'],['nm','ngo_manager'],['auditor','auditor']])await call('set_account_access',[ids[key],role,'active']);
const org=await call('save_organization',[null,{name:'NGO One',status:'active'}]);const org2=await call('save_organization',[null,{name:'NGO Two',status:'active'}]);
await call('set_membership',[org,ids.ngo,'ngo_admin','active']);await call('set_membership',[org2,ids.ngo,'ngo_admin','active']);await call('set_membership',[org2,ids.ngo2,'ngo_admin','active']);
const province=await call('save_geography',[null,null,'province','Fixture Province','P13','Synthetic test',true]);const division=await call('save_geography',[null,province,'division','Fixture Division','D13','Synthetic test',true]);const district=await call('save_geography',[null,division,'district','Fixture District','DIST13','Synthetic test',true]);const taluka=await call('save_geography',[null,district,'taluka','Fixture Taluka','T13','Synthetic test',true]);
await as('a');await call('save_my_profile',[{full_name:'Ayesha Field',phone:'03000000000',area:'Fixture',skills:'Survey, first aid',languages:'Sindhi, Urdu',availability:'Weekends'},true,1,taluka]);await call('set_profile_sharing',[org,true]);
const doc=await call('begin_document_upload',['test.pdf','application/pdf',12,'cv']);await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['poem-private-documents',doc.object_path,{size:12,mimetype:'application/pdf'}]);await call('finish_document_upload',[doc.id]);
await as('b');await call('save_my_profile',[{full_name:'Bilal',phone:'03000000000',area:'Fixture'},true,1,district]);await call('set_profile_sharing',[org2,true]);
await as('vm');await check('volunteer manager reads profiles and supporting files',async()=>{assert.equal((await rows('select * from public.volunteer_documents where id=$1',[doc.id])).length,1);assert((await search()).total>=8)});
await check('volunteer manager reviews evidence and profile',async()=>{await call('review_document',[doc.id,'accepted','Evidence reviewed',2]);const v=(await rows('select version from public.volunteer_profiles where user_id=$1',[ids.a]))[0].version;await call('review_profile',[ids.a,'verified','Checks completed',v,{profile_complete:true,contact_checked:true,location_checked:true}]);});
await check('volunteer manager cannot manage NGO or platform access',async()=>{await denied(()=>call('save_organization',[null,{name:'Forbidden'}]));await denied(()=>call('set_membership',[org,ids.b,'ngo_admin','active']));await denied(()=>call('set_account_access',[ids.b,'super_admin','active']));await denied(()=>call('save_geography',[null,null,'province','Other Province','FORBIDDEN','',true]))});
await as('nm');await check('NGO manager cannot read volunteer evidence or private CV',async()=>{assert.equal((await rows('select * from public.volunteer_profiles where user_id=$1',[ids.a])).length,0);assert.equal((await rows('select * from public.volunteer_documents where id=$1',[doc.id])).length,0);assert.equal((await rows('select * from storage.objects where name=$1',[doc.object_path])).length,0);await denied(()=>search());await denied(()=>call('review_document',[doc.id,'accepted','Forbidden',3]))});
await check('NGO manager saves structured areas/programs',async()=>{await call('save_ngo_operations',[org,[district,taluka],['Education','Health','Education'],1]);assert.equal((await rows('select * from public.organization_areas where organization_id=$1',[org])).length,2);assert.equal((await rows('select * from public.organization_programs where organization_id=$1',[org])).length,2)});
await check('stale operation version and invalid geography rejected atomically',async()=>{await denied(()=>call('save_ngo_operations',[org,[],[],1]),/changed/);await denied(()=>call('save_ngo_operations',[org,[province],['Health'],2]),/districts/);assert.equal((await rows('select operations_version from public.organizations where id=$1',[org]))[0].operations_version,2)});
await check('NGO manager can assign memberships but cannot assign staff roles',async()=>{await call('set_membership',[org,ids.b,'member','active']);await denied(()=>call('set_account_access',[ids.b,'auditor','active']))});
await as('auditor');await check('auditor sees audit history but not others CVs or files',async()=>{assert((await rows('select * from public.audit_events')).length>10);assert.equal((await rows('select * from public.volunteer_profiles where user_id=$1',[ids.a])).length,0);assert.equal((await rows('select * from storage.objects where name=$1',[doc.object_path])).length,0);await denied(()=>search());await denied(()=>call('save_ngo_operations',[org,[],[],2]));await denied(()=>call('review_document',[doc.id,'accepted','Forbidden',3]))});
await as('ngo');await check('same account in two NGOs receives only selected NGO grants',async()=>{assert.deepEqual((await search(org)).rows.map(r=>r.user_id),[ids.a]);assert.deepEqual((await search(org2)).rows.map(r=>r.user_id),[ids.b]);await denied(()=>search());});
await check('name skill language availability status and ancestor filters combine',async()=>{assert.equal((await search(org,{query:'AYESHA',skill:'aid',lang:'sindhi',available:'Weekends',geo:province,status:'verified'})).total,1);assert.equal((await search(org,{lang:'Arabic'})).total,0);assert.equal((await search(org,{query:'%'})).total,0)});
await check('invalid directory arguments rejected',async()=>{await denied(()=>search(org,{page:-1}),/Invalid/);await denied(()=>search(org,{status:'forged'}),/Invalid/)});
await check('NGO shortlist adds and updates with optimistic version',async()=>{await call('save_shortlist',[org,ids.a,'shortlisted','Local volunteer',0]);await call('save_shortlist',[org,ids.a,'considering','Discuss availability',1]);await denied(()=>call('save_shortlist',[org,ids.a,'selected','Old tab',1]),/changed/);const p=(await search(org,{shortlist:'any'})).rows[0];assert.equal(p.shortlist_status,'considering');assert.equal(p.shortlist_version,2)});
await check('NGO cannot shortlist another NGO grant or access evidence',async()=>{await denied(()=>call('save_shortlist',[org,ids.b,'selected','Forbidden',0]));assert.equal((await rows('select * from public.volunteer_documents')).length,0);await denied(()=>call('document_download_path',[doc.id]))});
await as('ngo2');await check('other NGO cannot see or modify private shortlist',async()=>{assert.equal((await rows('select * from public.volunteer_shortlists')).length,0);await denied(()=>call('save_shortlist',[org,ids.a,'selected','Forbidden',2]));await denied(()=>search(org))});
await as('a');await check('profile owner cannot read internal selection notes',async()=>{assert.equal((await rows('select * from public.volunteer_shortlists')).length,0);await denied(()=>call('save_shortlist',[org,ids.a,'selected','Self',2]))});
await call('set_profile_sharing',[org,false]);await as('ngo');await check('revocation immediately removes directory and shortlist visibility',async()=>{assert.equal((await search(org)).total,0);assert.equal((await rows('select * from public.volunteer_shortlists')).length,0);await denied(()=>call('save_shortlist',[org,ids.a,'selected','Stale access',2]))});
await as('a');await call('set_profile_sharing',[org,true]);await as('ngo');await check('regrant does not resurrect old private notes',async()=>{assert.equal((await search(org)).rows[0].shortlist_note,null)});
await db.exec('RESET ROLE');for(let i=0;i<61;i++){const id=`30000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`;await db.query('insert into auth.users(id,email) values($1,$2)',[id,`bulk${i}@example.test`]);await db.query("update public.volunteer_profiles set details=$1,geography_id=$2 where user_id=$3",[{full_name:'Paged Volunteer '+String(i).padStart(2,'0'),skills:'Mapping',languages:'Urdu'},district,id]);}
await as('vm');await check('server pagination returns 50 then 11 without duplicate IDs',async()=>{const a=await search(null,{query:'Paged Volunteer'}),b=await search(null,{query:'Paged Volunteer',page:1});assert.equal(a.total,61);assert.equal(a.rows.length,50);assert.equal(b.rows.length,11);assert.equal(new Set([...a.rows,...b.rows].map(r=>r.user_id)).size,61);assert.equal((await search(null,{query:'Paged Volunteer',page:2})).rows.length,0)});
await as('super');await call('set_membership',[org,ids.ngo,'ngo_admin','suspended']);await as('ngo');await check('membership suspension blocks old-session NGO search',async()=>denied(()=>search(org)));await as('super');await call('set_membership',[org,ids.ngo,'ngo_admin','active']);await call('set_account_access',[ids.vm,'volunteer_manager','suspended']);await as('vm');await check('staff suspension removes old-session privileged access',async()=>{await denied(()=>search());assert.equal((await rows('select * from public.volunteer_documents')).length,0)});
await as('super');await call('save_organization',[org,{name:'NGO One',status:'suspended'}]);await as('ngo');await check('NGO suspension blocks directory',async()=>denied(()=>search(org)));
await as(null);await check('anonymous has no new RPC access',async()=>{await denied(()=>search(org));await denied(()=>call('save_ngo_operations',[org,[],[],2]));await denied(()=>call('save_shortlist',[org,ids.a,'selected','',0]))});
console.log(`\n${count} Phase 1.3 role, directory and NGO operations tests passed.`);
}finally{await db.close()}
