import { useEffect, useState, type FormEvent } from "react";
import { db, rpc } from "../../lib/supabase/client";
import type { Database } from "../../lib/supabase/database.types";
type Case = Database["public"]["Tables"]["independent_verifications"]["Row"] & {effective_status:string};
type Event = Database["public"]["Tables"]["independent_verification_events"]["Row"];
type Kind = "organization"|"volunteer"|"beneficiary";
const kinds:Kind[]=["organization","volunteer","beneficiary"];
const labels={organization:"NGO registration",volunteer:"Volunteer identity",beneficiary:"Beneficiary identity"};
export function VerificationWorkspace({userId,managers}:{userId:string;managers:Record<Kind,boolean>}) {
 const [query,setQuery]=useState("");
 const [kind,setKind]=useState<Kind>("volunteer");
 const [rows,setRows]=useState<Case[]>([]),[subjects,setSubjects]=useState<{id:string;label:string}[]>([]);
 const [offset,setOffset]=useState(0),[more,setMore]=useState(false),[revision,setRevision]=useState(0);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [events,setEvents]=useState<Record<string,Event[]>>({});
 useEffect(()=>{let live=true;setBusy(true);setRows([]);setSubjects([]);setEvents({});setError("");
  Promise.all([rpc("list_independent_verifications",{p_kind:kind,p_offset:offset,p_limit:25}),rpc("verification_subjects",{p_kind:kind,p_query:query})]).then(([list,subjects])=>{if(!live)return;const r=list as unknown as {rows:Case[];has_more:boolean};setRows(r.rows);setMore(r.has_more);setSubjects(subjects as unknown as {id:string;label:string}[])}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setBusy(false)});return()=>{live=false};
 },[kind,offset,revision,query]);
 async function act(task:()=>Promise<unknown>){if(busy)return;setBusy(true);setError("");setMessage("");try{await task();setMessage("Saved. Verification is separate from operational status and profile publication.");setRevision(v=>v+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function request(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>rpc("request_independent_verification",{p_kind:kind,p_subject:String(f.get("subject")),p_evidence:String(f.get("evidence")),p_note:String(f.get("note"))}));}
 function review(e:FormEvent<HTMLFormElement>,c:Case){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("ack")!=="on")return;const expiry=String(f.get("expiry")||"");void act(()=>rpc("review_independent_verification",{p_id:c.id,p_decision:String(f.get("decision")),p_method:String(f.get("method")||"document_review"),p_note:String(f.get("note")),p_expires:expiry?new Date(expiry+"T23:59:59Z").toISOString():new Date().toISOString(),p_version:c.version}));}
 async function history(id:string){try{const r=await db!.from("independent_verification_events").select("*").eq("verification_id",id).order("id",{ascending:false}).limit(50);if(r.error)throw r.error;setEvents(x=>({...x,[id]:r.data||[]}))}catch(e){setError((e as Error).message)}}
 return <section className="panel detail"><h1>Independent verification</h1><p>Record a separate evidence review for NGO registration or identity. Publishing a profile, approving a survey or activating an NGO does not verify it. A different authorized reviewer must assess the request.</p>
 <nav className="document-actions" aria-label="Verification category">{kinds.map(k=><button key={k} className="secondary" disabled={busy} aria-pressed={kind===k} onClick={()=>{setKind(k);setQuery("");setOffset(0);setMessage("")}}>{labels[k]}</button>)}</nav>
 {error&&<p role="alert" className="error-text">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">Loading…</p>}
 <details><summary>Request {labels[kind].toLowerCase()} verification</summary><p>Use an existing private document or offline evidence reference. Do not paste identity numbers, document contents, credentials or public document links here. Reviewers must inspect the evidence through an authorized channel.</p>
 <form onSubmit={e=>{e.preventDefault();setQuery(String(new FormData(e.currentTarget).get("query")||""));}}><label className="field">Find a permitted subject (up to 25 results)<input name="query" maxLength={200}/></label><button className="secondary" disabled={busy}>Find subject</button></form>
 <form key={kind+revision} onSubmit={request}><label className="field">Subject<select name="subject" required><option value="">Select subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.label||s.id}</option>)}</select></label><label className="field">Private evidence reference<input name="evidence" required minLength={5} maxLength={1000}/></label><label className="field">Request note<textarea name="note" required minLength={5} maxLength={1000}/></label><button disabled={busy||!subjects.length}>Request independent review</button></form></details>
 {!busy&&!rows.length&&<p>No accessible verification cases in this category.</p>}
 {rows.map(c=><article className="document-row" key={c.id}><h3>{labels[c.kind as Kind]} · {c.effective_status.replaceAll("_"," ")}</h3><p>Case {c.id} · revision {c.version}</p><p>Subject {c.organization_id||c.volunteer_id||c.canonical_id}</p><p>Evidence reference: {c.evidence_reference}</p><p>{c.request_note}</p><p>Requested by {c.requested_by} · {new Date(c.requested_at).toLocaleString()}</p>{c.reviewed_by&&<p>Reviewed by {c.reviewed_by} · {c.method||"Decision"} · {c.review_note}</p>}{c.expires_at&&<p>Expiry: {new Date(c.expires_at).toLocaleString()}</p>}
 {c.effective_status==="stale"&&<p>Subject data changed. This case no longer provides current verification; submit a fresh case.</p>}
 <details><summary>Submitted subject snapshot</summary><pre className="survey-json">{JSON.stringify(c.subject_snapshot,null,2)}</pre></details>
 {(managers[c.kind as Kind]||c.requested_by===userId)&&((c.status==="pending")||(managers[c.kind as Kind]&&c.status==="verified"))&&<details><summary>Review / withdraw / revoke</summary><form onSubmit={e=>review(e,c)}><label className="field">Decision<select name="decision" required defaultValue=""><option value="">Choose decision</option>{managers[c.kind as Kind]&&c.status==="pending"&&c.requested_by!==userId&&c.volunteer_id!==userId&&<><option value="verified">Verify from inspected evidence</option><option value="rejected">Reject</option></>}{c.status==="pending"&&c.requested_by===userId&&<option value="withdrawn">Withdraw request</option>}{managers[c.kind as Kind]&&c.status==="verified"&&<option value="revoked">Revoke verification</option>}</select></label><label className="field">Review method<select name="method"><option value="document_review">Document review</option><option value="issuer_check">Issuer/registry check</option><option value="in_person_check">In-person check</option></select></label><label className="field">Expiry (required for verification, within one year)<input name="expiry" type="date"/></label><label className="field">Decision reason<textarea name="note" required minLength={5} maxLength={1000}/></label><label><input name="ack" type="checkbox" required/> I reviewed the evidence and the effect of this decision.</label><p><button disabled={busy}>Record decision</button></p></form></details>}
 <button className="secondary" onClick={()=>void history(c.id)}>Load history (latest 50)</button>{events[c.id]?.map(e=><p key={e.id}>{new Date(e.created_at).toLocaleString()} · {e.action} · {e.actor_id} · {e.reason}</p>)}</article>)}
 <div className="document-actions"><button className="secondary" disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</button><span>Page {offset/25+1}</span><button className="secondary" disabled={busy||!more} onClick={()=>setOffset(offset+25)}>Next</button><button className="secondary" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Refresh</button></div>
 </section>;
}
