import {useEffect,useState,type FormEvent,type ReactNode} from 'react';
import type {Session} from '@supabase/supabase-js';
import {HeartHandshake,LayoutDashboard,Users,Building2,ShieldCheck,Activity,LogOut,UserRound,Search,Plus,ArrowRight,MapPin,Menu,CheckCircle,Clock,KeyRound,Bell} from 'lucide-react';
import {db,configured,rpc} from './client';
import {Documents,GeographyManager,GeographyPicker,Notifications,geographyPath,type Geo} from './Phase12';
import {Directory,NgoOperations} from './Phase13';
import {ExperiencePanel,InvitationsPanel} from './Phase14';
type Row=Record<string,any>;
const fields=[['full_name','Full name'],['phone','Phone'],['area','Current town / area'],['education','Education'],['skills','Skills (comma separated)'],['languages','Languages'],['experience','Work and survey experience'],['preferred_areas','Preferred work areas'],['references','References'],['bio','About you']];
const options:Record<string,string[]>={availability:['Part-time','Full-time','Weekends','Unavailable'],preference:['Volunteer','Paid','Paid or volunteer'],transport:['None','Public transport','Motorcycle','Car'],smartphone:['Available','Not available']};
const human=(s:string)=>s.replaceAll('_',' ');
function Badge({value}:{value:string}){return <span className={'badge '+value}>{human(value)}</span>}
function Field({label,children}:{label:string,children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Select({value,onChange,values,label}:{value:string,onChange:(s:string)=>void,values:string[],label:string}){return <Field label={label}><select value={value} onChange={e=>onChange(e.target.value)}>{values.map(v=><option key={v} value={v}>{human(v)}</option>)}</select></Field>}
export default function App(){
 const [session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[recovery,setRecovery]=useState(location.pathname==='/reset'),[error,setError]=useState('');
 useEffect(()=>{if(!db){setReady(true);return}let alive=true;db.auth.getSession().then(({data,error})=>{if(alive){setSession(data.session);setReady(true);if(error)setError(error.message)}}).catch(e=>{if(alive){setError(e.message);setReady(true)}});const {data}=db.auth.onAuthStateChange((event,s)=>{setSession(s);setReady(true);if(event==='PASSWORD_RECOVERY')setRecovery(true)});return()=>{alive=false;data.subscription.unsubscribe()}},[]);
 if(!configured)return <div className="setup"><HeartHandshake size={42}/><h1>Connect your POEM workspace</h1><p>Copy <code>.env.example</code> to <code>.env.local</code> and enter your Supabase URL and public key, then restart the development server.</p><p>For local Supabase, run <code>npm run env:local</code> after starting Supabase.</p></div>;
 if(!ready)return <div className="setup" role="status">Opening POEM…</div>;
 return session&&!recovery?<Workspace session={session}/>:<Auth session={session} recovery={recovery} error={error} done={()=>{setRecovery(false);history.replaceState({},'', '/')}}/>;
}
function Auth({session,recovery,error:initialError,done}:{session:Session|null,recovery:boolean,error:string,done:()=>void}){
 const [mode,setMode]=useState(recovery?'reset':'login'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(initialError);
 useEffect(()=>{if(recovery)setMode('reset')},[recovery]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');const f=new FormData(e.currentTarget),email=String(f.get('email')||''),password=String(f.get('password')||'');try{
 if(mode==='login'){const r=await db!.auth.signInWithPassword({email,password});if(r.error)throw r.error;}
 if(mode==='signup'){const r=await db!.auth.signUp({email,password,options:{data:{full_name:String(f.get('full_name'))},emailRedirectTo:location.origin+'/auth/callback'}});if(r.error)throw r.error;setMessage('Account created. Check your email to confirm your address, then sign in.');}
 if(mode==='forgot'){const r=await db!.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/reset'});if(r.error)throw r.error;setMessage('If this email is registered, a reset link will arrive shortly.');}
 if(mode==='reset'){if(!session)throw Error('Open the latest reset link from your email.');if(password!==f.get('confirm'))throw Error('Passwords do not match.');const r=await db!.auth.updateUser({password});if(r.error)throw r.error;done();}
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="auth-shell"><section className="auth-story"><div className="logo"><HeartHandshake/><b>POEM</b></div><span className="eyebrow">PEOPLE. PURPOSE. IMPACT.</span><h1>Local people.<br/>Lasting possibilities.</h1><p>Bring your skills, experience and commitment to a network that puts communities first.</p><div className="auth-points"><span><CheckCircle/>Your own volunteer profile</span><span><ShieldCheck/>POEM-reviewed information</span><span><Users/>NGO access you control</span></div><small>Volunteer Network · Phase 1.4</small></section><section className="auth-form"><div className="auth-card"><span className="eyebrow">WELCOME TO POEM</span><h2>{mode==='signup'?'Join the volunteer network':mode==='forgot'?'Reset your password':mode==='reset'?'Choose a new password':'Sign in to your workspace'}</h2><p>{mode==='signup'?'Create your account. You can complete your CV-style profile after signing in.':'Use your POEM account to continue.'}</p>{error&&<div role="alert" className="notice error">{error}</div>}{message&&<div role="status" className="notice success">{message}</div>}<form onSubmit={submit}>{mode==='signup'&&<Field label="Full name"><input name="full_name" required minLength={2} maxLength={200} autoComplete="name"/></Field>}{mode!=='reset'&&<Field label="Email address"><input name="email" type="email" required autoComplete="email"/></Field>}{mode!=='forgot'&&<Field label="Password"><input name="password" type="password" required minLength={mode==='login'?1:12} autoComplete={mode==='login'?'current-password':'new-password'}/>{mode!=='login'&&<small>At least 12 characters.</small>}</Field>}{mode==='reset'&&<Field label="Confirm password"><input name="confirm" type="password" required minLength={12} autoComplete="new-password"/></Field>}<button className="primary wide" disabled={busy}>{busy?'Please wait…':mode==='signup'?'Create volunteer account':mode==='forgot'?'Send reset link':mode==='reset'?'Update password':'Sign in'}<ArrowRight size={16}/></button></form>{mode==='login'?<><button className="link" onClick={()=>{setMode('forgot');setError('');setMessage('')}}>Forgot password?</button><div className="auth-bottom">New to POEM? <button onClick={()=>{setMode('signup');setError('');setMessage('')}}>Create an account</button></div></>:<button className="link" onClick={()=>{setMode('login');setError('');setMessage('');if(recovery)done()}}>Back to sign in</button>}<p className="fine">Volunteer signup does not grant admin access. Profile verification is completed separately by POEM.</p></div></section></div>
}
function Workspace({session}:{session:Session}){
 const [account,setAccount]=useState<Row|null>(null),[profiles,setProfiles]=useState<Row[]>([]),[orgs,setOrgs]=useState<Row[]>([]),[members,setMembers]=useState<Row[]>([]),[accounts,setAccounts]=useState<Row[]>([]),[shares,setShares]=useState<Row[]>([]),[events,setEvents]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState('Overview'),[scope,setScope]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<Row|null>(null),[orgEdit,setOrgEdit]=useState<Row|null>(null),[menu,setMenu]=useState(false),[geographies,setGeographies]=useState<Geo[]>([]),[notifications,setNotifications]=useState<Row[]>([]);
 const admin=account&&['admin','super_admin','volunteer_manager','ngo_manager','auditor'].includes(account.platform_role),poem=admin&&scope==='poem',superAdmin=poem&&account?.platform_role==='super_admin';
 const volunteers=poem&&['admin','super_admin','volunteer_manager'].includes(account?.platform_role),ngos=poem&&['admin','super_admin','ngo_manager'].includes(account?.platform_role);
 const [revision,setRevision]=useState(0);
 async function load(){setError('');try{
 const a=await db!.from('accounts').select('*').eq('id',session.user.id).single();if(a.error)throw a.error;setAccount(a.data);if(a.data.status==='suspended'){setProfiles([]);setOrgs([]);setLoading(false);return}
 const res=await Promise.all([db!.from('volunteer_profiles').select('*').eq('user_id',session.user.id),db!.from('organizations').select('*').order('name').limit(500),db!.from('organization_memberships').select('*').limit(1000),db!.from('profile_shares').select('*').limit(1000),db!.from('audit_events').select('*').order('created_at',{ascending:false}).limit(100),db!.from('accounts').select('*').order('full_name').limit(500),db!.from('notifications').select('*').order('created_at',{ascending:false}).limit(100),db!.from('volunteer_profiles').select('*').eq('user_id',session.user.id).single()]);
 for(const r of res)if(r.error)throw r.error;
 setProfiles([res[7].data!,...(res[0].data||[]).filter((p:Row)=>p.user_id!==session.user.id)]);setOrgs(res[1].data||[]);setMembers(res[2].data||[]);setShares(res[3].data||[]);setEvents(res[4].data||[]);setAccounts(res[5].data||[]);setNotifications(res[6].data||[]);setRevision(n=>n+1);
 const geoRows:Geo[]=[];for(let offset=0;;offset+=1000){const g=await db!.from('geographies').select('*').order('id').range(offset,offset+999);if(g.error)throw g.error;geoRows.push(...(g.data||[]));if((g.data||[]).length<1000)break;}setGeographies(geoRows);
 setScope(old=>old||(['admin','super_admin','volunteer_manager','ngo_manager','auditor'].includes(a.data.platform_role)?'poem':(res[2].data||[]).find(m=>m.user_id===session.user.id&&m.role==='ngo_admin'&&m.status==='active'&&(res[1].data||[]).some(o=>o.id===m.organization_id&&o.status==='active'))?.organization_id||'personal'));
 }catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[session.user.id]);
 async function act(fn:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{await fn();await load();setNotice(message);return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 async function logout(){const {error}=await db!.auth.signOut();if(error)setError(error.message)}
 const my=profiles.find(p=>p.user_id===session.user.id),myOrgs=orgs.filter(o=>o.status==='active'&&members.some(m=>m.organization_id===o.id&&m.user_id===session.user.id&&m.role==='ngo_admin'&&m.status==='active'));
 const validScope=poem||scope==='personal'||myOrgs.some(o=>o.id===scope);
 const nav=[['Overview',LayoutDashboard],['My profile',UserRound],...((volunteers||(!poem&&scope!=='personal'))?[['Volunteers',Users]]:[]),...(volunteers?[['Verification',ShieldCheck]]:[]),['Partner NGOs',Building2],...(!poem?[['Work experience',Users],['Invitations',Bell]]:[]),...(ngos?[['Memberships',Users]]:[]),...(superAdmin?[['Accounts',KeyRound]]:[]),...(ngos?[['Geography',MapPin]]:[]),['Notifications',Bell],['Activity',Activity]] as const;
 const change=(p:string)=>{setPage(p);setQuery('');setFilter('all');setMenu(false);setSelected(null);setOrgEdit(null)};
 if(loading)return <div className="setup" role="status">Loading your workspace…</div>;
 if(!account)return <div className="setup"><h2>Unable to open your account</h2><p role="alert">{error||'Account setup is incomplete. Check that database migrations have been applied.'}</p><button className="primary" onClick={load}>Retry</button><button onClick={logout}>Sign out</button></div>;
 if(account.status==='suspended')return <div className="setup"><ShieldCheck size={40}/><h1>Account suspended</h1><p>Contact POEM to request a review. Data access has been disabled.</p><button onClick={logout}>Sign out</button></div>;
 return <div className="app"><aside className={menu?'sidebar open':'sidebar'}><div className="logo"><HeartHandshake/><b>POEM</b></div><div className="workspace-select"><label htmlFor="scope">WORKSPACE</label><select id="scope" value={scope} onChange={e=>{setScope(e.target.value);change('Overview')}}>{admin&&<option value="poem">POEM administration</option>}<option value="personal">My volunteer workspace</option>{myOrgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div><nav>{nav.map(([name,Icon]:any)=><button key={name} className={page===name?'active':''} onClick={()=>change(name)}><Icon size={19}/>{name}{name==='Notifications'&&notifications.some(n=>!n.read_at)&&<span className="nav-count">{notifications.filter(n=>!n.read_at).length}</span>}</button>)}</nav><div className="trust"><ShieldCheck/><strong>A network built on trust.</strong><p>Your information. Clear permissions. Accountable decisions.</p></div><div className="identity"><span className="avatar">{(account.full_name||account.email)[0].toUpperCase()}</span><div><strong>{account.full_name||'POEM member'}</strong><small>{human(account.platform_role)}</small></div></div><button className="logout" onClick={logout}><LogOut size={17}/>Sign out</button></aside><main><header><button className="mobile-toggle" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}><Menu/></button><span>Workspace <b>/</b> {page}</span><span className="release">PHASE 1.4</span></header><div className="content"><div className="heading"><div><span className="eyebrow">PEOPLE AT THE HEART OF IMPACT</span><h1>{page==='Overview'?'Your community, connected.':page}</h1><p>{poem?'Manage the network, review profiles and support your partner NGOs.':scope==='personal'?'Build your profile and choose who can access it.':'View volunteers who have shared their profiles with your NGO.'}</p></div>{page==='Partner NGOs'&&ngos&&<button className="primary" onClick={()=>setOrgEdit({name:'',status:'pending'})}><Plus size={17}/>Add partner NGO</button>}</div>{error&&<div className="notice error" role="alert">{error}<button onClick={load}>Reload</button></div>}{notice&&<div className="notice success" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss">×</button></div>}{!validScope&&<div className="notice error">This workspace is no longer available. Switch to your personal workspace.</div>}
 {page==='Overview'&&<><section className="panel detail"><h2>{poem?'POEM staff workspace':scope==='personal'?'Your volunteer workspace':'NGO workforce workspace'}</h2><p>{poem?'Your staff role determines which records and actions are available.':scope==='personal'?'Keep your profile and sharing preferences current.':'Search shared volunteers and manage your NGO shortlist.'}</p>{(volunteers||(!poem&&scope!=='personal'))&&<button className="primary" onClick={()=>change('Volunteers')}>Search volunteers</button>}</section><div className="overview-grid"><section className="hero-panel"><span className="eyebrow">THE NEXT STEP STARTS WITH YOU</span><h2>Local people.<br/>Lasting possibilities.</h2><p>Keep your information up to date and turn your experience into meaningful community work.</p><button onClick={()=>change('My profile')}>Complete your profile <ArrowRight size={17}/></button></section><section className="panel attention"><ShieldCheck size={32}/><h2>{volunteers?'Profile verification':'Your verification status'}</h2>{volunteers?<><p>Open the review queue to see the current authorized count and submitted profiles.</p><button onClick={()=>change('Verification')}>Open review queue <ArrowRight size={16}/></button></>:<><Badge value={my?.status||'draft'}/><p>{my?.review_note||'Save your profile and submit it to POEM for review.'}</p><button onClick={()=>change('My profile')}>View my profile <ArrowRight size={16}/></button></>}</section></div><section className="panel"><div className="panel-title"><h2>Recent activity</h2><button className="link" onClick={()=>change('Activity')}>View activity</button></div><EventList events={events.slice(0,4)}/></section></>}
 {page==='My profile'&&my&&<><ProfileForm key={my.version} profile={my} geographies={geographies} busy={busy} save={(details,submit,geography)=>act(()=>rpc('save_my_profile',{p_details:details,p_submit:submit,p_version:my.version,p_geography:geography}),submit?'Profile submitted to POEM.':'Draft saved. Submit when ready.')}/><Documents userId={session.user.id} owner={true} reviewer={false} onChanged={load}/><section className="panel sharing"><h2>NGO profile access</h2><p>Documents remain private to you and POEM. Allow an active NGO’s administrators to view your full volunteer profile, including phone, education, experience and references. This is optional and does not affect POEM verification. Revocation stops future platform access; it cannot recall information already viewed.</p>{orgs.filter(o=>o.status==='active'||shares.some(s=>s.organization_id===o.id&&s.user_id===session.user.id)).map(o=>{const granted=shares.some(s=>s.user_id===session.user.id&&s.organization_id===o.id);return <div className="share-row" key={o.id}><span>{o.name} <Badge value={o.status}/></span><button disabled={busy} className={granted?'secondary':'primary'} onClick={()=>act(()=>rpc('set_profile_sharing',{p_org:o.id,p_allowed:!granted}),granted?'NGO access revoked.':'Profile access granted to this NGO.')}>{granted?'Revoke access':'Allow profile access'}</button></div>})}{!orgs.length&&<p>No active partner NGOs yet.</p>}</section></>}
 {(page==='Volunteers'||page==='Verification')&&validScope&&(volunteers||(!poem&&scope!=='personal'))&&<><Directory key={scope+page} organization={poem?null:scope} geographies={geographies} reviewQueue={page==='Verification'} onSelect={setSelected} revision={revision}/ >{selected&&<section className="panel detail"><div className="panel-title"><h2>{selected.details.full_name||'Volunteer profile'}</h2><button onClick={()=>setSelected(null)} aria-label="Close profile">Close ×</button></div><div className="detail-fields">{Object.entries(selected.details).map(([k,v])=><div key={k}><small>{human(k)}</small><p>{String(v)||'—'}</p></div>)}</div><ExperiencePanel key={selected.user_id} userId={selected.user_id} organization={null} orgs={orgs as any} readonly/>{volunteers&&selected.user_id!==session.user.id&&<><Documents userId={selected.user_id} owner={false} reviewer={true} onChanged={async()=>{await load();const r=await db!.from('volunteer_profiles').select('*').eq('user_id',selected.user_id).single();if(r.error)throw r.error;setSelected(r.data)}}/><ReviewForm key={selected.user_id+selected.version} busy={busy} submit={async(status,note,checks)=>{const ok=await act(()=>rpc('review_profile',{p_user_id:selected.user_id,p_status:status,p_note:note,p_version:selected.version,p_checks:checks}),'Review decision saved.');if(ok)setSelected(null)}}/></>}</section>}</>}
 {page==='Partner NGOs'&&<>{orgEdit&&ngos&&<OrgForm value={orgEdit} busy={busy} cancel={()=>setOrgEdit(null)} save={async d=>{if(await act(()=>rpc('save_organization',{p_id:orgEdit.id||null,p_data:d}),'Organization saved.'))setOrgEdit(null)}}/>}<div className="org-grid">{orgs.map(o=><section className="panel org" key={o.id}><Building2 size={26}/><Badge value={o.status}/><h2>{o.name}</h2><p>{o.programs||'Programs not yet specified'}</p><dl><dt>Areas</dt><dd>{o.areas||'—'}</dd><dt>Contact</dt><dd>{o.contact_person||'—'}</dd><dt>Email</dt><dd>{o.email||'—'}</dd><dt>Registration</dt><dd>{o.registration_number||'—'}</dd></dl>{ngos&&<button className="secondary" onClick={()=>setOrgEdit(o)}>Edit organization</button>}<NgoOperations orgId={o.id} geographies={geographies} editable={Boolean(ngos)}/></section>)}</div>{!orgs.length&&<div className="panel empty"><Building2/><h3>No organizations yet</h3></div>}</>}
 {page==='Memberships'&&ngos&&<section className="panel detail"><h2>Organization memberships</h2><p>Assign an existing registered account to an NGO. Membership does not automatically share the volunteer’s profile.</p><MembershipForm orgs={orgs} accounts={accounts} busy={busy} save={(org,user,role,status)=>act(()=>rpc('set_membership',{p_org:org,p_user:user,p_role:role,p_status:status}),'Membership updated.')}/><div className="table-wrap"><table><thead><tr><th>Organization</th><th>Account</th><th>Role</th><th>Status</th></tr></thead><tbody>{members.map(m=><tr key={m.organization_id+m.user_id}><td>{orgs.find(o=>o.id===m.organization_id)?.name}</td><td>{accounts.find(a=>a.id===m.user_id)?.email}</td><td>{human(m.role)}</td><td><Badge value={m.status}/></td></tr>)}</tbody></table></div></section>}
 {page==='Accounts'&&superAdmin&&<section className="panel detail"><h2>Platform access</h2><p>Platform roles are separate from NGO memberships. Suspend an account to stop its database access immediately.</p>{accounts.filter(a=>a.id!==session.user.id).map(a=><AccountAccess key={a.id+a.platform_role+a.status} account={a} busy={busy} save={(role,status)=>act(()=>rpc('set_account_access',{p_user:a.id,p_role:role,p_status:status}),'Account access updated.')}/>)}</section>}
 {page==='Geography'&&ngos&&<GeographyManager rows={geographies} refresh={load}/>}
 {page==='Work experience'&&!poem&&validScope&&<ExperiencePanel key={scope} userId={session.user.id} organization={scope==='personal'?null:scope} orgs={orgs as any}/> }
 {page==='Invitations'&&!poem&&validScope&&<InvitationsPanel key={scope} userId={session.user.id} organization={scope==='personal'?null:scope} orgs={orgs as any} geographies={geographies}/> }
 {page==='Notifications'&&<Notifications rows={notifications} refresh={load}/>}
 {page==='Activity'&&<section className="panel"><div className="panel-title"><h2>Audit history</h2><span>Latest 100 authorized events</span></div><EventList events={events}/></section>}
 <footer><span>POEM · Volunteer Network</span><span>Phase 1.4 · Surveys and beneficiary registry are planned next.</span></footer></div></main></div>
}
function ProfileForm({profile,busy,save,geographies}:{profile:Row,busy:boolean,geographies:Geo[],save:(d:Row,s:boolean,g:string|null)=>Promise<boolean>}){const [d,setD]=useState<Row>(profile.details),[geo,setGeo]=useState<string|null>(profile.geography_id||null);return <section className="panel detail"><div className="panel-title"><h2>My volunteer profile</h2><Badge value={profile.status}/></div>{profile.review_note&&<div className="notice">POEM review: {profile.review_note}</div>}<p>Save a draft at any time. Submit once your full name, phone and location are complete. Editing a verified profile requires a new review.</p><form onSubmit={e=>{e.preventDefault();save(d,true,geo)}}><GeographyPicker rows={geographies} value={geo} onChange={setGeo}/><div className="form-grid">{fields.map(([k,l])=><Field key={k} label={l+(k==='full_name'||k==='phone'||k==='area'?' *':'')}>{['experience','references','bio'].includes(k)?<textarea maxLength={4000} value={d[k]||''} onChange={e=>setD({...d,[k]:e.target.value})}/>:<input maxLength={k==='full_name'?200:1000} value={d[k]||''} onChange={e=>setD({...d,[k]:e.target.value})}/>}</Field>)}{Object.entries(options).map(([k,vals])=><Select key={k} label={human(k)} value={d[k]||''} values={['',...vals]} onChange={v=>setD({...d,[k]:v})}/>)}</div><div className="actions"><button type="button" className="secondary" disabled={busy||profile.status==='suspended'} onClick={()=>save(d,false,geo)}>Save draft</button><button className="primary" disabled={busy||profile.status==='suspended'}>{busy?'Saving…':'Submit for verification'}</button></div><p className="fine">Provide only information and references you are authorized to share. Upload supporting evidence in the Private documents section below.</p></form></section>}
function ReviewForm({busy,submit}:{busy:boolean,submit:(s:string,n:string,c:Row)=>void}){const [status,setStatus]=useState('verified');return <form className="review" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);submit(status,String(f.get('note')),{profile_complete:f.get('profile_complete')==='on',contact_checked:f.get('contact_checked')==='on',location_checked:f.get('location_checked')==='on'})}}><h3>POEM review decision</h3><p className="fine">For approval, review all current documents and complete these checks. These checks do not certify legal identity.</p>{["profile_complete","contact_checked","location_checked"].map(k=><label key={k} className="checklabel"><input name={k} type="checkbox" required={status==="verified"}/>{human(k)}</label>)}<Select label="Decision" value={status} onChange={setStatus} values={['verified','correction_required','suspended']}/><Field label="Review note"><textarea name="note" minLength={3} maxLength={2000} required placeholder="State what you checked or what needs correction."/></Field><button className="primary" disabled={busy}>Save decision</button></form>}
function OrgForm({value,busy,cancel,save}:{value:Row,busy:boolean,cancel:()=>void,save:(d:Row)=>void}){const [d,setD]=useState(value);useEffect(()=>setD(value),[value]);return <section className="panel detail"><h2>{value.id?'Edit organization':'Add partner NGO'}</h2><form onSubmit={e=>{e.preventDefault();save(d)}}><div className="form-grid">{['name','registration_number','contact_person','email','phone','address','areas','programs'].map(k=><Field key={k} label={human(k)}><input required={k==='name'} minLength={k==='name'?2:undefined} maxLength={k==='name'?200:1000} type={k==='email'?'email':'text'} value={d[k]||''} onChange={e=>setD({...d,[k]:e.target.value})}/></Field>)}<Select label="Status" values={['pending','active','inactive','suspended']} value={d.status} onChange={v=>setD({...d,status:v})}/></div><div className="actions"><button type="button" className="secondary" onClick={cancel}>Cancel</button><button className="primary" disabled={busy}>Save NGO</button></div></form></section>}
function MembershipForm({orgs,accounts,busy,save}:{orgs:Row[],accounts:Row[],busy:boolean,save:(o:string,u:string,r:string,s:string)=>void}){return <form className="membership" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save(String(f.get('org')),String(f.get('user')),String(f.get('role')),String(f.get('status')))}}><Field label="Organization"><select name="org" required><option value="">Choose NGO</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field><Field label="Registered account"><select name="user" required><option value="">Choose account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.email}</option>)}</select></Field><Field label="Role"><select name="role"><option value="ngo_admin">NGO admin</option><option value="member">Member</option></select></Field><Field label="Status"><select name="status"><option>active</option><option>suspended</option></select></Field><button className="primary" disabled={busy}>Save membership</button></form>}
function AccountAccess({account,busy,save}:{account:Row,busy:boolean,save:(r:string,s:string)=>void}){const [role,setRole]=useState(account.platform_role),[status,setStatus]=useState(account.status);return <form className="account-row" onSubmit={e=>{e.preventDefault();save(role,status)}}><strong>{account.email}</strong><Select label="Platform role" value={role} onChange={setRole} values={['volunteer','volunteer_manager','ngo_manager','auditor','admin','super_admin']}/><Select label="Account status" value={status} onChange={setStatus} values={['active','suspended']}/><button className="secondary" disabled={busy}>Update access</button></form>}
function EventList({events}:{events:Row[]}){return events.length?<div>{events.map(e=><div className="event" key={e.id}><Activity size={18}/><div><strong>{human(e.action)}</strong><p>{Object.entries(e.detail||{}).map(([k,v])=>`${human(k)}: ${v}`).join(' · ')}</p><small>{new Date(e.created_at).toLocaleString()} · Actor: {e.actor_id||'System'}</small></div></div>)}</div>:<div className="empty"><Activity/><h3>No activity yet</h3><p>Profile updates and access decisions will appear here.</p></div>}
