import {useEffect,useState,useRef,type FormEvent} from 'react';
import {NeedsPanel} from './Phase23';
import {db,rpc} from './client';
import type {Database} from './database.types';
type T=Database['public']['Tables'];type Person=T['registry_persons']['Row'];type Entry=T['assistance_entries']['Row'];
type Candidate={id:string;registry_no:number;full_name:string;birth_date:string|null;household_id:string;version:number;signals:string[];status:string|null;reason:string|null;decision_version:number|null;stale:boolean};
const text=(f:FormData,k:string)=>String(f.get(k)||'').trim();
const ben=(n:number)=>'POEM-BEN-'+String(n).padStart(8,'0');
const label=(s:string)=>s.replaceAll('_',' ');
export function RegistryOperations({personId,close,changed,refreshKey=0}:{personId:string;close:()=>void;changed:()=>void;refreshKey?:number}){
 const panel=useRef<HTMLElement>(null);useEffect(()=>{panel.current?.focus()},[personId]);
 const [person,setPerson]=useState<Person|null>(null),[history,setHistory]=useState<T['registry_person_revisions']['Row'][]>([]),[entries,setEntries]=useState<Entry[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[houses,setHouses]=useState<T['registry_households']['Row'][]>([]),[houseQuery,setHouseQuery]=useState(''),[matchHistory,setMatchHistory]=useState<T['registry_match_revisions']['Row'][]>([]),[matchOpen,setMatchOpen]=useState(''),[page,setPage]=useState(0),[more,setMore]=useState(false),[rev,setRev]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[kind,setKind]=useState('cash'),[requestId,setRequestId]=useState(()=>crypto.randomUUID()),[correction,setCorrection]=useState(false);
 useEffect(()=>{let live=true;setBusy(true);setError('');setMatchOpen('');setMatchHistory([]);async function load(){const results=await Promise.all([db!.from('registry_persons').select('*').eq('id',personId).single(),db!.from('registry_person_revisions').select('*').eq('person_id',personId).order('version',{ascending:false}).limit(50),db!.from('assistance_entries').select('*').eq('person_id',personId).order('delivered_on',{ascending:false}).order('id').range(page*50,page*50+50)]);for(const r of results)if(r.error)throw r.error;const matches=await rpc('registry_match_candidates',{p_person:personId});if(live){setPerson(results[0].data);setHistory(results[1].data||[]);setEntries((results[2].data||[]).slice(0,50));setMore((results[2].data||[]).length>50);setCandidates(matches as unknown as Candidate[])}}load().catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[personId,page,rev,refreshKey]);
 useEffect(()=>{if(!person||!correction)return;let live=true;db!.from('registry_households').select('*').eq('project_id',person.project_id).ilike('label','%'+houseQuery.replaceAll('%','').replaceAll('_','')+'%').order('label').order('id').limit(50).then(r=>{if(!live)return;if(r.error)setError(r.error.message);else setHouses(r.data||[])});return()=>{live=false}},[person?.project_id,houseQuery,correction]);
 async function act(task:()=>Promise<unknown>,msg:string,done?:()=>void){setBusy(true);setError('');setMessage('');try{await task();done?.();setMessage(msg);setRev(n=>n+1);changed()}catch(e){setError((e as Error).message);setBusy(false)}}
 function correct(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!person)return;const f=new FormData(e.currentTarget);void act(()=>rpc('correct_registry_person',{p_id:person.id,p_name:text(f,'name'),p_birth:text(f,'birth')||null,p_household:text(f,'household'),p_reason:text(f,'reason'),p_version:person.version}),'Identity corrected; earlier survey and assistance snapshots remain unchanged.',()=>setCorrection(false))}
 function record(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),form=e.currentTarget;void act(()=>rpc('record_assistance',{p_id:requestId,p_person:personId,p_kind:kind,p_category:text(f,'category'),p_program:text(f,'program'),p_description:text(f,'description'),p_amount:kind==='cash'?Number(text(f,'amount')):null,p_quantity:kind!=='cash'?Number(text(f,'quantity')):null,p_unit:kind!=='cash'?text(f,'unit'):null,p_delivered:text(f,'delivered'),p_funding:text(f,'funding'),p_evidence:text(f,'evidence'),p_next:text(f,'next')||null}),'Assistance recorded.',()=>{form.reset();setRequestId(crypto.randomUUID());setKind('cash');setPage(0)})}
 async function showHistory(c:Candidate){setError('');setMatchOpen('');const [a,b]=[personId,c.id].sort();const r=await db!.from('registry_match_revisions').select('*').eq('person_a',a).eq('person_b',b).order('version',{ascending:false}).limit(50);if(r.error)setError(r.error.message);else{setMatchHistory(r.data||[]);setMatchOpen(c.id)}}
 return <section ref={panel} tabIndex={-1} className="registry-operations" aria-label="Registry review and assistance"><div className="panel-title"><h3>{person?`${ben(person.registry_no)} · ${person.full_name}`:'Registry record'}</h3><button className="secondary" onClick={close}>Close record</button></div>{error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">Loading record…</p>}{person&&<><p>{person.birth_date||'Birth date unknown'} · Identity provisional · Revision {person.version}</p>
 <details className="survey-question" open={correction} onToggle={e=>setCorrection(e.currentTarget.open)}><summary>Correct identity details</summary><form key={person.version} onSubmit={correct}><fieldset disabled={busy}><div className="form-grid"><label className="field">Full name<input name="name" required minLength={2} maxLength={200} defaultValue={person.full_name}/></label><label className="field">Birth date (blank if unknown)<input name="birth" type="date" defaultValue={person.birth_date||''}/></label></div><label className="field">Find household in this project (first 50 matches)<input value={houseQuery} onChange={e=>setHouseQuery(e.target.value)} maxLength={100}/></label><label className="field">Household<select name="household" defaultValue={person.household_id}><option value={person.household_id}>Current household</option>{houses.filter(h=>h.id!==person.household_id).map(h=><option key={h.id} value={h.id}>{h.label}</option>)}</select></label><label className="field">Correction reason<textarea name="reason" minLength={5} maxLength={1000} required/></label><button className="primary">Save correction</button></fieldset></form></details>
 <details className="survey-question"><summary>Identity history · latest 50 revisions</summary>{history.map(h=><details key={h.version}><summary>v{h.version} · {h.reason} · {new Date(h.recorded_at).toLocaleString()}</summary><pre className="survey-json">{JSON.stringify(h.snapshot,null,2)}</pre><p>Recorded by: {h.actor_id||'Upgrade baseline'}</p></details>)}</details>
 <NeedsPanel refreshKey={rev+refreshKey} projectId={person.project_id} personId={person.id} onChanged={()=>{setRev(n=>n+1);changed()}}/><h3>Possible identity matches</h3><p>Compare the evidence before deciding. A shared household or birth date alone does not establish identity. Decisions do not merge records or combine assistance histories.</p>{!busy&&!candidates.length&&<p>No candidates found by the current rules. This does not establish that the person is unique.</p>}{candidates.length>50&&<p role="status">Showing the first 50 candidates. Additional candidates exist; use registry search to inspect other records.</p>}{candidates.slice(0,50).map(c=><article className="survey-question" key={c.id}><h4>{ben(c.registry_no)} · {c.full_name}</h4><p>{c.birth_date||'Birth date unknown'}</p><p>{c.signals.join(' · ')||'Previously reviewed pair'}</p><p>Decision: {c.status?label(c.status):'Not reviewed'}{c.stale?' — identity changed; review again':''}</p>{c.reason&&<p>{c.reason}</p>}<form key={`${c.decision_version}-${c.version}-${person.version}`} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>rpc('review_registry_match',{p_person:personId,p_other:c.id,p_status:text(f,'status'),p_reason:text(f,'reason'),p_person_version:person.version,p_other_version:c.version,p_version:c.decision_version||0}),'Match decision saved. Both records remain separate.')}}><fieldset disabled={busy}><label className="field">Decision<select name="status" defaultValue={c.stale?'needs_review':c.status||'needs_review'}><option value="needs_review">Needs review</option><option value="different_people">Different people</option><option value="same_person">Same person — flag only</option></select></label><label className="field">Evidence / reason<textarea name="reason" minLength={5} maxLength={1000} required/></label><button className="secondary">Save decision</button></fieldset></form>{c.decision_version&&<button className="link" disabled={busy} onClick={()=>void showHistory(c)}>Show decision history</button>}{matchOpen===c.id&&matchHistory.map(h=><details key={h.version}><summary>Decision v{h.version} · {new Date(h.recorded_at).toLocaleString()}</summary><pre className="survey-json">{JSON.stringify(h.snapshot,null,2)}</pre></details>)}</article>)}
 <h3>Assistance timeline</h3><p>Recorded deliveries for this person in this project. Voided entries remain in history. Recording requires at least one approved survey; it does not verify identity or execute payment.</p>{!busy&&!entries.length&&<p>No assistance entries on this page.</p>}{entries.map(a=><article className="document-row" key={a.id}><h4>{a.description}</h4><p><strong>{a.kind==='cash'?`PKR ${Number(a.amount_pkr).toLocaleString(undefined,{minimumFractionDigits:2})}`:`${a.quantity} ${a.unit}`}</strong> · {a.category} · {a.status}</p><p>{a.delivered_on} · {a.program} · Funded by {a.funding_source}</p><p>Evidence reference: {a.evidence_reference}</p>{a.next_eligible_on&&<p>Next eligibility date: {a.next_eligible_on} (recorded guidance)</p>}<details><summary>Record and identity snapshot</summary><p>Recorded by {a.created_by} · {new Date(a.created_at).toLocaleString()} · Reference {a.id}</p><pre className="survey-json">{JSON.stringify(a.identity_snapshot,null,2)}</pre></details>{a.status==='void'?<p>Voided: {a.void_reason} · {a.voided_at&&new Date(a.voided_at).toLocaleString()} · {a.voided_by}</p>:<details><summary>Void incorrect entry</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>rpc('void_assistance',{p_id:a.id,p_reason:text(f,'reason'),p_version:a.version}),'Entry voided. Its original details remain in history.')}}><label className="field">Reason<textarea name="reason" required minLength={5} maxLength={1000}/></label><button className="secondary" disabled={busy}>Void entry</button></form></details>}</article>)}<div className="actions"><button className="secondary" disabled={busy||page===0} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page+1}</span><button className="secondary" disabled={busy||!more} onClick={()=>setPage(n=>n+1)}>Next 50</button></div>
 <details className="survey-question"><summary>Record delivered assistance</summary><form onSubmit={record}><fieldset disabled={busy}><div className="form-grid"><label className="field">Type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="cash">Cash (PKR)</option><option value="goods">Goods</option><option value="service">Service</option></select></label><label className="field">Category<select name="category">{['food','education','health','housing','livelihood','other'].map(c=><option key={c}>{c}</option>)}</select></label><label className="field">Program<input name="program" required minLength={2} maxLength={150}/></label>{kind==='cash'?<label className="field">Amount in PKR<input name="amount" type="number" min="0.01" max="1000000000" step="0.01" required/></label>:<><label className="field">Quantity<input name="quantity" type="number" min="0.001" max="1000000" step="0.001" required/></label><label className="field">Unit (e.g. packages, sessions)<input name="unit" required maxLength={30}/></label></>}<label className="field">Delivery date<input name="delivered" type="date" required/></label><label className="field">Next eligibility date (optional)<input name="next" type="date"/></label><label className="field">Funding source<input name="funding" required minLength={2} maxLength={200}/></label><label className="field">Evidence reference<input name="evidence" required minLength={3} maxLength={500} placeholder="Receipt or distribution register reference"/></label></div><label className="field">Delivered item / description<textarea name="description" required minLength={3} maxLength={1000}/></label><p>Check this timeline and possible matches first. After an uncertain save, retry the same form without editing; the request reference prevents a second entry while this form stays open.</p><button className="primary">Record delivery</button></fieldset></form></details></>}</section>
}
