import {useEffect,useState,type FormEvent} from 'react';
import {rpc} from '../../lib/supabase/client';
type Summary={completed_assignments:number;approved_surveys:number;reviewed_surveys:number;review_count:number;average_rating:number|null;average_quality:number|null;average_reliability:number|null;average_communication:number|null;verified_experiences:number};
type Review={id:string;organization_name:string;rating:number;note:string;created_at:string;version:number};
type Certificate={id:string;certificate_no:string;verification_code:string;worker_name:string;title:string;issuer_label:string;status:string;issued_at:string;expires_at:string|null;evidence_note:string;public_sharing:boolean;version:number};
type Candidate={id:string;name:string;project_title?:string;review_id?:string;review_version?:number;review_status?:string};
type PublicCertificate={valid:boolean;status:string;worker_name?:string;certificate_no?:string;title?:string;issuer_label?:string;issued_at?:string;expires_at?:string|null};
const rating=(v:number|null)=>v===null?'Not rated':`${Number(v).toFixed(2)} / 5`;
const certificateURL=(code:string)=>`${location.origin}/?certificate=${encodeURIComponent(code)}`;
function printCertificate(c:Certificate){const w=window.open('','_blank','width=900,height=700');if(!w){window.alert('Allow popups to print your certificate.');return;}w.document.title=c.certificate_no;const style=w.document.createElement('style');style.textContent='body{font-family:Georgia,serif;padding:48px;color:#142b43}main{border:3px solid #214f6d;padding:40px;text-align:center}h1{font-size:34px}h2{font-size:28px}p{line-height:1.8}';w.document.head.append(style);const main=w.document.createElement('main');for(const [tag,text] of [['h2',c.issuer_label],['h1',c.title],['p','Awarded to'],['h2',c.worker_name],['p',c.evidence_note],['p',`Certificate: ${c.certificate_no}`],['p',`Issued: ${new Date(c.issued_at).toLocaleDateString()}${c.expires_at?` · Expires: ${new Date(c.expires_at).toLocaleDateString()}`:''}`],['p',c.public_sharing?`Verify current status: ${certificateURL(c.verification_code)}`:'Public verification is disabled by the certificate owner.']]){const e=w.document.createElement(tag);e.textContent=text;main.append(e)}w.document.body.append(main);w.focus();w.print();}
export function CertificateVerification(){const [code,setCode]=useState(new URLSearchParams(location.search).get('certificate')||''),[result,setResult]=useState<PublicCertificate|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');async function verify(e:FormEvent){e.preventDefault();setBusy(true);setResult(null);setError('');try{setResult(await rpc('verify_field_worker_certificate',{p_code:code.trim()}) as unknown as PublicCertificate)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <section className="panel detail"><h1>Verify a FieldLance certificate</h1><p>Enter the verification code shared by the certificate holder.</p><form onSubmit={verify}><label className="field">Verification code<input value={code} onChange={e=>setCode(e.target.value)} required maxLength={32}/></label><button disabled={busy}>Verify certificate</button></form>{error&&<p role="alert">{error}</p>}{result&&<article className="document-row" role="status"><h2>{result.valid?'Valid certificate':result.status==='unavailable'?'Certificate unavailable':`Certificate ${result.status}`}</h2>{result.worker_name&&<><h3>{result.title}</h3><p>{result.worker_name} · {result.issuer_label}</p><p>{result.certificate_no}</p><p>Issued {result.issued_at&&new Date(result.issued_at).toLocaleDateString()}{result.expires_at&&` · Expires ${new Date(result.expires_at).toLocaleDateString()}`}</p></>}</article>}<a href="/">Return to FieldLance</a></section>}
export function ReputationCertificates({userId,organization,canManage}:{userId:string;organization:string|null;canManage:boolean}){
 const [target,setTarget]=useState(canManage?'':userId),[candidates,setCandidates]=useState<Candidate[]>([]),[query,setQuery]=useState(''),[summary,setSummary]=useState<Summary|null>(null),[reviews,setReviews]=useState<Review[]>([]),[certs,setCerts]=useState<Certificate[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{if(!organization&&!canManage)return;let live=true;const timer=setTimeout(()=>{rpc('reputation_candidates',{p_org:organization,p_query:query}).then(r=>{if(live)setCandidates(r as unknown as Candidate[])}).catch(e=>live&&setError(e.message))},250);return()=>{live=false;clearTimeout(timer)}},[organization,canManage,query,revision]);
 useEffect(()=>{setSummary(null);setReviews([]);setCerts([]);if(organization||!target)return;let live=true;setBusy(true);setError('');Promise.all([rpc('field_worker_reputation',{p_user:target}),rpc('field_worker_reputation_reviews',{p_user:target}),rpc('field_worker_certificates',{p_user:target})]).then(([s,r,c])=>{if(live){setSummary(s as unknown as Summary);setReviews(r as unknown as Review[]);setCerts(c as unknown as Certificate[])}}).catch(e=>live&&setError(e.message)).finally(()=>live&&setBusy(false));return()=>{live=false}},[target,organization,revision]);
 async function act(fn:()=>Promise<unknown>,success:string){setBusy(true);setError('');setMessage('');try{await fn();setMessage(success);setRevision(n=>n+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function review(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>rpc('submit_field_worker_review',{p_assignment:String(f.get('assignment')),p_rating:Number(f.get('rating')),p_quality:Number(f.get('quality')),p_reliability:Number(f.get('reliability')),p_communication:Number(f.get('communication')),p_note:String(f.get('note'))}),'Assignment review published.');}
 function issue(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),expiry=String(f.get('expires')||'');void act(()=>rpc('issue_field_worker_certificate',{p_user:target,p_type:String(f.get('type')),p_title:String(f.get('title')),p_note:String(f.get('note')),p_expires:expiry?new Date(expiry).toISOString():null}),'Certificate issued privately to the worker.');}
 return <section className="panel detail"><span className="eyebrow">FIELDLANCE VERIFY</span><h1>Reputation & Certificates</h1><p>Completed work, reviewed surveys and organization feedback.</p>{error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">Loading…</p>}{(canManage||organization)&&<label className="field">Find Field Worker by name<input value={query} onChange={e=>setQuery(e.target.value)}/><small>Up to 100 matching records. Refine your search if needed.</small></label>}
 {canManage&&!organization&&<label className="field">Field Worker<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose Field Worker</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.name||'Unnamed account'}</option>)}</select></label>}
 {organization&&<><h2>Completed-assignment reviews</h2><form onSubmit={review}><label className="field">Completed assignment<select name="assignment" required><option value="">Choose worker and project</option>{candidates.filter(c=>!c.review_id).map(c=><option key={c.id} value={c.id}>{c.name} · {c.project_title}</option>)}</select></label><div className="form-grid">{['rating','quality','reliability','communication'].map(k=><label className="field" key={k}>{k==='rating'?'Overall rating':k}<select name={k} required defaultValue=""><option value="">Choose rating</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label>)}</div><label className="field">Feedback<textarea name="note" minLength={5} maxLength={2000} required/></label><button disabled={busy}>Publish review</button></form>{!candidates.length&&<p>No completed assignments match.</p>}{candidates.filter(c=>c.review_id).map(c=><article key={c.id} className="document-row"><p>{c.name} · {c.project_title} · Review {c.review_status}</p>{c.review_status==='published'&&<button disabled={busy} onClick={()=>{const note=window.prompt('Reason for withdrawing this review:');if(note)void act(()=>rpc('withdraw_field_worker_review',{p_id:c.review_id!,p_note:note,p_version:c.review_version!}),'Review withdrawn; retained in audit history.')}}>Withdraw review</button>}</article>)}</>}
 {summary&&<><div className="stats"><article className="stat"><div>Completed assignments</div><b>{summary.completed_assignments}</b></article><article className="stat"><div>Approved surveys</div><b>{summary.approved_surveys}</b></article><article className="stat"><div>Approval rate</div><b>{summary.reviewed_surveys?`${Math.round(100*summary.approved_surveys/summary.reviewed_surveys)}%`:'Not available'}</b><small>Approved / reviewed responses ({summary.reviewed_surveys})</small></article><article className="stat"><div>Overall rating</div><b>{rating(summary.average_rating)}</b><small>{summary.review_count} published reviews</small></article></div><p>Quality: {rating(summary.average_quality)} · Reliability: {rating(summary.average_reliability)} · Communication: {rating(summary.average_communication)}</p><p>Ratings are feedback from completed assignments. No review means not rated. Survey approval is separate from identity verification.</p><h2>Verified reviews</h2><p>Latest 100 published reviews.</p>{reviews.map(r=><article className="document-row" key={r.id}><h3>{r.organization_name} · {r.rating}/5</h3><p>{r.note}</p><small>{new Date(r.created_at).toLocaleDateString()}</small>{canManage&&<button disabled={busy} onClick={()=>{const note=window.prompt('Reason for withdrawing this review:');if(note)void act(()=>rpc('withdraw_field_worker_review',{p_id:r.id,p_note:note,p_version:r.version}),'Review withdrawn.')}}>Withdraw review</button>}</article>)}{!reviews.length&&<p>No reviews yet.</p>}</>}
 {!organization&&target&&<><h2>Certificates</h2><p>Latest 100 certificates. Public sharing is off until the worker enables it. Shared verification shows the worker name, certificate title, issuer and dates.</p>{certs.map(c=><article className="document-row" key={c.id}><h3>{c.title}</h3><p>{c.worker_name} · {c.status} · {c.issuer_label}</p><p>{c.certificate_no}</p><p>Issued {new Date(c.issued_at).toLocaleDateString()}{c.expires_at&&` · Expires ${new Date(c.expires_at).toLocaleDateString()}`}</p><p>{c.evidence_note}</p><div className="actions">{c.status==='active'&&<button onClick={()=>printCertificate(c)}>Print / Save as PDF</button>}{target===userId&&<button disabled={busy} onClick={()=>void act(()=>rpc('share_field_worker_certificate',{p_id:c.id,p_share:!c.public_sharing,p_version:c.version}),'Certificate sharing updated.')}>{c.public_sharing?'Disable public verification':'Enable public verification'}</button>}{canManage&&c.status!=='revoked'&&<button disabled={busy} onClick={()=>{const note=window.prompt('Certificate revocation reason:');if(note)void act(()=>rpc('revoke_field_worker_certificate',{p_id:c.id,p_note:note,p_version:c.version}),'Certificate revoked.')}}>Revoke certificate</button>}</div>{c.public_sharing&&<><p>Verification code: <code>{c.verification_code}</code></p><a href={certificateURL(c.verification_code)} target="_blank" rel="noreferrer">Open public verification</a></>}</article>)}{!certs.length&&<p>No certificates issued.</p>}</>}
 {canManage&&!organization&&target&&<form onSubmit={issue}><h2>Issue certificate</h2><label className="field">Type<select name="type"><option value="field_professional">Field Professional</option><option value="survey_quality">Survey Quality</option><option value="project_completion">Project Completion</option><option value="custom">Custom work evidence</option></select></label><label className="field">Certificate title<input name="title" required minLength={3} maxLength={160}/></label><label className="field">Evidence and award scope<textarea name="note" required minLength={5} maxLength={2000}/></label><p>State the work substantiated by the record. Issuance snapshots current platform work counts.</p><label className="field">Expiry (optional)<input type="datetime-local" name="expires"/></label><button disabled={busy}>Issue certificate</button></form>}
 </section>;
}
